using GITProtocol;
using SlotGamesNode.GameLogics.BaseClasses;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SlotGamesNode.GameLogics
{
    internal class CashConnectionBookOfRaGameLogic : BaseGreenSlotGame
    {
        #region
        protected override string ScatterSymbol {
            get
            {
                return "D";
            }
        }

        protected override int MinCountToFreespin
        {
            get
            {
                return 6;
            }
        }

        protected override string VersionCheckString
        {
            get
            {
                return "\b0ÿ2.5.16ÿCasino-Lobbymanager-Serverÿ11289ÿ1.10.54.0ÿGTATCashConnectionServerÿ11772ÿ1.0.0ÿCash Connection - Book of Ra Linked 95%ÿ1.118.0_2025-03-28_090804ÿ1.51.0";
            }
        }

        protected override string GameUniqueString
        {
            get
            {
                return "\u0006S0ÿA1ÿRÿM,10,10000,1,-1,0ÿI00ÿH,0,0,0,0,0,0ÿ:n,Cash Connection - Book of Ra Linked 95%ÿ:v,3ÿ:l,-----ÿ:l,^^^^^ÿ:l,_____ÿ:l,^-_-^ÿ:l,_-^-_ÿ:l,-___-ÿ:l,-^^^-ÿ:l,__-^^ÿ:l,^^-__ÿ:l,_---^ÿ:r,0,AQDDTBJQTKMJQEATSQTKCJQDDAQTMKJEASKJQCAKDDDAQTBJTKMJQEATSQTKAQTBJTKMJQEATSQTKCJQDDATQMKJASKJQCAKDDDAQTBJTKMJQEATSQTKAQTBJTKMJQEATSQTKCJQDDATMKJASKJQCAKDDDAQTBJTKMJQEATSQTKÿ:r,0,TQSKABTJMQDDKJQKEAJMQKCTJASKTACTADDDJKQATJASJKQMTQASQKAJBTAJQDDKJQEAQKCTJASKTACJTADDDJKQMTCJKAQKJMQKSTAKBTJQCKJQEAJMQKCTJASKTACTAKDDDJKQMTJASJKQMTQASKAJBTJQDDKJQEAQKCTJASKTACJTAJKQMTJKSACQKJMTQSKAQBTJQDDKJQEAJMQKCTJASKTACTADDDJKQATJASTJKQMTQASKAJQBTJQDDKJQEAQKCTJASKTACMJTADDDCJKQMTJKAQKJMQKTAKBTJQKJQEAJMQKCTJASKTACTAKDDDJKQMTJQASJKQCMTQAJSKAJMBTJQDDKSJQEAQKCTJASKTACJTAJKQMTJKSAQKJMTQSKABTCJQDDKJQEAJMQKCQTJASKTACTADDDJKQATJASJKQMTQCASKAJBTJQDDKJQEAQKCTJASKTACJKTADDDJKQSMTJKAQKJMQKTAKBTJQKJQEAJMQKACTJASMKTACTAKDDDJKQMTJASJKQMTQASKAJBTJQDDKJQEAQKCTJASKTACJTAJKQMTAJKSAQKJMÿ:r,0,TEJQTSDDDQASQJTSKQJCTAQEJTMQAKTSQATESJATBKQAMJKDDKJQEKJTKSQATJSQJEKTASJQCATJSTAQCKJCQTAMJTEJSQTDDDQAKSQJATSKQJCTAQEJTMQAKSQATSCJATBKQAMJKDDKJSQEKJTSQATJSQJEKTASJQCATJSTAQCKJCQTAMJTEJQTDDDQASQJTSKQJCTAQEJTMQAKSQATSJATBKQAMJKDDKJQEKJTSQATJSQJEKTASJQCATJSTAQCKJCQTAMJÿ:r,0,KACJTSKQCJKSATCKTDDKAQBJTEKJAETJBKTSKTCQASJKMATQEKAMJTCKABMJQSAKJCQKDDDJEQMAKEJTCQJKACJTSKQCJKSATCKTDDKAQKBJTEJAETJBKTSKTCQASJKMATQEKAMEJTCKAMJQSAKCQKDDDJQMAKEJTCQJKACJTSKQCJKSATCKTDDKMAQBCJTEJAETJBKTSKTCKQASJKMATQEKAMJTBCKAMJQTSAKCQKDDDTJQMAKEJTKCQJÿ:r,0,JCQMTJBKAEQKSJQETASQJMTKCAJSTQDDAJSATCKACTJCKQCJTKMQKDDQCAJMKQCJKMATEKADDQCKTQSAJDDTKSJQMTJBKAEQKSJQETASQJMTKECAJSTQDDAJMSATCKACTEJCKQCJKMQKDDQTCAJMKQCJKMATEADDQCKTSAJDDTKSJQMTAJBKAEQKSJQETCASQJMTKCEAJSCTQDDAJSATCKACTJCKQCJKMQKDDQCAJMKQCJKMATEADDQCEKTSAJDDTKSÿ:r,1,AQDDTBJQTKMJQEATSQTKCJQDDAQTMKJEASKJQCAKDDDAQTBJTKMJQEATSQTKAQTBJTKMJQEATSQTKCJQDDATQMKJASKJQCAKDDDAQTBJTKMJQEATSQTKAQTBJTKMJQEATSQTKCJQDDATMKJASKJQCAKDDDAQTBJTKMJQEATSQTKÿ:r,1,TQSKABTJMQDDKJQKEAJMQKCTJASKTACTADDDJKQATJASJKQMTQASQKAJBTAJQDDKJQEAQKCTJASKTACJTADDDJKQMTCJKAQKJMQKSTAKBTJQCKJQEAJMQKCTJASKTACTAKDDDJKQMTJASJKQMTQASKAJBTJQDDKJQEAQKCTJASKTACJTAJKQMTJKSACQKJMTQSKAQBTJQDDKJQEAJMQKCTJASKTACTADDDJKQATJASTJKQMTQASKAJQBTJQDDKJQEAQKCTJASKTACMJTADDDCJKQMTJKAQKJMQKTAKBTJQKJQEAJMQKCTJASKTACTAKDDDJKQMTJQASJKQCMTQAJSKAJMBTJQDDKSJQEAQKCTJASKTACJTAJKQMTJKSAQKJMTQSKABTCJQDDKJQEAJMQKCQTJASKTACTADDDJKQATJASJKQMTQCASKAJBTJQDDKJQEAQKCTJASKTACJKTADDDJKQSMTJKAQKJMQKTAKBTJQKJQEAJMQKACTJASMKTACTAKDDDJKQMTJASJKQMTQASKAJBTJQDDKJQEAQKCTJASKTACJTAJKQMTAJKSAQKJMÿ:r,1,TEJQTSDDDQASQJTSKQJCTAQEJTMQAKTSQATESJATBKQAMJKDDKJQEKJTKSQATJSQJEKTASJQCATJSTAQCKJCQTAMJTEJSQTDDDQAKSQJATSKQJCTAQEJTMQAKSQATSCJATBKQAMJKDDKJSQEKJTSQATJSQJEKTASJQCATJSTAQCKJCQTAMJTEJQTDDDQASQJTSKQJCTAQEJTMQAKSQATSJATBKQAMJKDDKJQEKJTSQATJSQJEKTASJQCATJSTAQCKJCQTAMJÿ:r,1,KACJTSKQCJKSATCKTDDKAQBJTEKJAETJBKTSKTCQASJKMATQEKAMJTCKABMJQSAKJCQKDDDJEQMAKEJTCQJKACJTSKQCJKSATCKTDDKAQKBJTEJAETJBKTSKTCQASJKMATQEKAMEJTCKAMJQSAKCQKDDDJQMAKEJTCQJKACJTSKQCJKSATCKTDDKMAQBCJTEJAETJBKTSKTCKQASJKMATQEKAMJTBCKAMJQTSAKCQKDDDTJQMAKEJTKCQJÿ:r,1,JCQMTJBKAEQKSJQETASQJMTKCAJSTQDDAJSATCKACTJCKQCJTKMQKDDQCAJMKQCJKMATEKADDQCKTQSAJDDTKSJQMTJBKAEQKSJQETASQJMTKECAJSTQDDAJMSATCKACTEJCKQCJKMQKDDQTCAJMKQCJKMATEADDQCKTSAJDDTKSJQMTAJBKAEQKSJQETCASQJMTKCEAJSCTQDDAJSATCKACTJCKQCJKMQKDDQCAJMKQCJKMATEADDQCEKTSAJDDTKSÿ:r,2,AQDDTBJQTKMJQEATSQTKCJQDDAQTMKJEASKJQCAKDDDAQTBJTKMJQEATSQTKAQTBJTKMJQEATSQTKCJQDDATQMKJASKJQCAKDDDAQTBJTKMJQEATSQTKAQTBJTKMJQEATSQTKCJQDDATMKJASKJQCAKDDDAQTBJTKMJQEATSQTKÿ:r,2,TQSKABTJMQDDKJQKEAJMQKCTJASKTACTADDDJKQATJASJKQMTQASQKAJBTAJQDDKJQEAQKCTJASKTACJTADDDJKQMTCJKAQKJMQKSTAKBTJQCKJQEAJMQKCTJASKTACTAKDDDJKQMTJASJKQMTQASKAJBTJQDDKJQEAQKCTJASKTACJTAJKQMTJKSACQKJMTQSKAQBTJQDDKJQEAJMQKCTJASKTACTADDDJKQATJASTJKQMTQASKAJQBTJQDDKJQEAQKCTJASKTACMJTADDDCJKQMTJKAQKJMQKTAKBTJQKJQEAJMQKCTJASKTACTAKDDDJKQMTJQASJKQCMTQAJSKAJMBTJQDDKSJQEAQKCTJASKTACJTAJKQMTJKSAQKJMTQSKABTCJQDDKJQEAJMQKCQTJASKTACTADDDJKQATJASJKQMTQCASKAJBTJQDDKJQEAQKCTJASKTACJKTADDDJKQSMTJKAQKJMQKTAKBTJQKJQEAJMQKACTJASMKTACTAKDDDJKQMTJASJKQMTQASKAJBTJQDDKJQEAQKCTJASKTACJTAJKQMTAJKSAQKJMÿ:r,2,TEJQTSDDDQASQJTSKQJCTAQEJTMQAKTSQATESJATBKQAMJKDDKJQEKJTKSQATJSQJEKTASJQCATJSTAQCKJCQTAMJTEJSQTDDDQAKSQJATSKQJCTAQEJTMQAKSQATSCJATBKQAMJKDDKJSQEKJTSQATJSQJEKTASJQCATJSTAQCKJCQTAMJTEJQTDDDQASQJTSKQJCTAQEJTMQAKSQATSJATBKQAMJKDDKJQEKJTSQATJSQJEKTASJQCATJSTAQCKJCQTAMJÿ:r,2,KACJTSKQCJKSATCKTDDKAQBJTEKJAETJBKTSKTCQASJKMATQEKAMJTCKABMJQSAKJCQKDDDJEQMAKEJTCQJKACJTSKQCJKSATCKTDDKAQKBJTEJAETJBKTSKTCQASJKMATQEKAMEJTCKAMJQSAKCQKDDDJQMAKEJTCQJKACJTSKQCJKSATCKTDDKMAQBCJTEJAETJBKTSKTCKQASJKMATQEKAMJTBCKAMJQTSAKCQKDDDTJQMAKEJTKCQJÿ:r,2,JCQMTJBKAEQKSJQETASQJMTKCAJSTQDDAJSATCKACTJCKQCJTKMQKDDQCAJMKQCJKMATEKADDQCKTQSAJDDTKSJQMTJBKAEQKSJQETASQJMTKECAJSTQDDAJMSATCKACTEJCKQCJKMQKDDQTCAJMKQCJKMATEADDQCKTSAJDDTKSJQMTAJBKAEQKSJQETCASQJMTKCEAJSCTQDDAJSATCKACTJCKQCJKMQKDDQCAJMKQCJKMATEADDQCEKTSAJDDTKSÿ:r,3,AQDDTBJQTKMJQEATSQTKCJQDDAQTMKJEASKJQCAKDDDAQTBJTKMJQEATSQTKAQTBJTKMJQEATSQTKCJQDDATQMKJASKJQCAKDDDAQTBJTKMJQEATSQTKAQTBJTKMJQEATSQTKCJQDDATMKJASKJQCAKDDDAQTBJTKMJQEATSQTKÿ:r,3,TQSKABTJMQDDKJQKEAJMQKCTJASKTACTADDDJKQATJASJKQMTQASQKAJBTAJQDDKJQEAQKCTJASKTACJTADDDJKQMTCJKAQKJMQKSTAKBTJQCKJQEAJMQKCTJASKTACTAKDDDJKQMTJASJKQMTQASKAJBTJQDDKJQEAQKCTJASKTACJTAJKQMTJKSACQKJMTQSKAQBTJQDDKJQEAJMQKCTJASKTACTADDDJKQATJASTJKQMTQASKAJQBTJQDDKJQEAQKCTJASKTACMJTADDDCJKQMTJKAQKJMQKTAKBTJQKJQEAJMQKCTJASKTACTAKDDDJKQMTJQASJKQCMTQAJSKAJMBTJQDDKSJQEAQKCTJASKTACJTAJKQMTJKSAQKJMTQSKABTCJQDDKJQEAJMQKCQTJASKTACTADDDJKQATJASJKQMTQCASKAJBTJQDDKJQEAQKCTJASKTACJKTADDDJKQSMTJKAQKJMQKTAKBTJQKJQEAJMQKACTJASMKTACTAKDDDJKQMTJASJKQMTQASKAJBTJQDDKJQEAQKCTJASKTACJTAJKQMTAJKSAQKJMÿ:r,3,TEJQTSDDDQASQJTSKQJCTAQEJTMQAKTSQATESJATBKQAMJKDDKJQEKJTKSQATJSQJEKTASJQCATJSTAQCKJCQTAMJTEJSQTDDDQAKSQJATSKQJCTAQEJTMQAKSQATSCJATBKQAMJKDDKJSQEKJTSQATJSQJEKTASJQCATJSTAQCKJCQTAMJTEJQTDDDQASQJTSKQJCTAQEJTMQAKSQATSJATBKQAMJKDDKJQEKJTSQATJSQJEKTASJQCATJSTAQCKJCQTAMJÿ:r,3,KACJTSKQCJKSATCKTDDKAQBJTEKJAETJBKTSKTCQASJKMATQEKAMJTCKABMJQSAKJCQKDDDJEQMAKEJTCQJKACJTSKQCJKSATCKTDDKAQKBJTEJAETJBKTSKTCQASJKMATQEKAMEJTCKAMJQSAKCQKDDDJQMAKEJTCQJKACJTSKQCJKSATCKTDDKMAQBCJTEJAETJBKTSKTCKQASJKMATQEKAMJTBCKAMJQTSAKCQKDDDTJQMAKEJTKCQJÿ:r,3,JCQMTJBKAEQKSJQETASQJMTKCAJSTQDDAJSATCKACTJCKQCJTKMQKDDQCAJMKQCJKMATEKADDQCKTQSAJDDTKSJQMTJBKAEQKSJQETASQJMTKECAJSTQDDAJMSATCKACTEJCKQCJKMQKDDQTCAJMKQCJKMATEADDQCKTSAJDDTKSJQMTAJBKAEQKSJQETCASQJMTKCEAJSCTQDDAJSATCKACTJCKQCJKMQKDDQCAJMKQCJKMATEADDQCEKTSAJDDTKSÿ:r,4,BEMSCDAKQJTBEBMBSBCBDBABKBQBJBTÿ:r,4,BEMSCDAKQJTBEBMBSBCBDBABKBQBJBTÿ:r,4,BEMSCDAKQJTBEBMBSBCBDBABKBQBJBTÿ:r,4,BEMSCDAKQJTBEBMBSBCBDBABKBQBJBTÿ:r,4,BEMSCDAKQJTBEBMBSBCBDBABKBQBJBTÿ:r,5,BEMSCDAKQJTÿ:r,5,BEMSCDAKQJTÿ:r,5,BEMSCDAKQJTÿ:r,5,BEMSCDAKQJTÿ:r,5,BEMSCDAKQJTÿ:r,6,EMSCDAKQJTÿ:r,6,EMSCDAKQJTÿ:r,6,EMSCDAKQJTÿ:r,6,EMSCDAKQJTÿ:r,6,EMSCDAKQJTÿ:j,B,1,0,ÿ:u,APPPP.PP.PP.PPPPÿ:w,D,103,-12500,99.0:Major,12500.0ÿ:w,D,102,-75000,99.0:Grand,75000.0ÿ:w,D,14,-1,0ÿ:w,D,13,-1,0ÿ:w,D,12,-1,0ÿ:w,D,11,-1,0ÿ:w,D,10,-1,0ÿ:w,D,9,-1,0ÿ:w,D,8,-1,0ÿ:w,D,7,-1,0ÿ:w,D,6,-1,0ÿ:w,B,2,10,0ÿ:w,B,3,100,0ÿ:w,B,4,1000,0ÿ:w,B,5,5000,0ÿ:w,E,2,10,0ÿ:w,E,3,100,0ÿ:w,E,4,1000,0ÿ:w,E,5,5000,0ÿ:w,M,2,5,0ÿ:w,M,3,40,0ÿ:w,M,4,400,0ÿ:w,M,5,2000,0ÿ:w,S,2,5,0ÿ:w,S,3,30,0ÿ:w,S,4,100,0ÿ:w,S,5,750,0ÿ:w,C,2,5,0ÿ:w,C,3,30,0ÿ:w,C,4,100,0ÿ:w,C,5,750,0ÿ:w,A,3,5,0ÿ:w,A,4,40,0ÿ:w,A,5,150,0ÿ:w,K,3,5,0ÿ:w,K,4,40,0ÿ:w,K,5,150,0ÿ:w,Q,3,5,0ÿ:w,Q,4,25,0ÿ:w,Q,5,100,0ÿ:w,J,3,5,0ÿ:w,J,4,25,0ÿ:w,J,5,100,0ÿ:w,T,3,5,0ÿ:w,T,4,25,0ÿ:w,T,5,100,0ÿ:wa,D,103,-12500,99.0:Major,12500.0,0,0:1,-1,0ÿ:wa,D,102,-75000,99.0:Grand,75000.0,0,0:1,-1,0ÿ:wa,D,14,-1,0,0,0,0:1,-1,0ÿ:wa,D,13,-1,0,0,0,0:1,-1,0ÿ:wa,D,12,-1,0,0,0,0:1,-1,0ÿ:wa,D,11,-1,0,0,0,0:1,-1,0ÿ:wa,D,10,-1,0,0,0,0:1,-1,0ÿ:wa,D,9,-1,0,0,0,0:1,-1,0ÿ:wa,D,8,-1,0,0,0,0:1,-1,0ÿ:wa,D,7,-1,0,0,0,0:1,-1,0ÿ:wa,D,6,-1,0,0,0,0:1,-1,0ÿ:wa,B,2,10,0,0,0,0:1,-1,0ÿ:wa,B,3,100,0,0,0,0:1,-1,0ÿ:wa,B,4,1000,0,0,0,0:1,-1,0ÿ:wa,B,5,5000,0,0,0,0:1,-1,0ÿ:wa,E,2,10,0,0,0,0:1,-1,0ÿ:wa,E,3,100,0,0,0,0:1,-1,0ÿ:wa,E,4,1000,0,0,0,0:1,-1,0ÿ:wa,E,5,5000,0,0,0,0:1,-1,0ÿ:wa,M,2,5,0,0,0,0:1,-1,0ÿ:wa,M,3,40,0,0,0,0:1,-1,0ÿ:wa,M,4,400,0,0,0,0:1,-1,0ÿ:wa,M,5,2000,0,0,0,0:1,-1,0ÿ:wa,S,2,5,0,0,0,0:1,-1,0ÿ:wa,S,3,30,0,0,0,0:1,-1,0ÿ:wa,S,4,100,0,0,0,0:1,-1,0ÿ:wa,S,5,750,0,0,0,0:1,-1,0ÿ:wa,C,2,5,0,0,0,0:1,-1,0ÿ:wa,C,3,30,0,0,0,0:1,-1,0ÿ:wa,C,4,100,0,0,0,0:1,-1,0ÿ:wa,C,5,750,0,0,0,0:1,-1,0ÿ:wa,A,3,5,0,0,0,0:1,-1,0ÿ:wa,A,4,40,0,0,0,0:1,-1,0ÿ:wa,A,5,150,0,0,0,0:1,-1,0ÿ:wa,K,3,5,0,0,0,0:1,-1,0ÿ:wa,K,4,40,0,0,0,0:1,-1,0ÿ:wa,K,5,150,0,0,0,0:1,-1,0ÿ:wa,Q,3,5,0,0,0,0:1,-1,0ÿ:wa,Q,4,25,0,0,0,0:1,-1,0ÿ:wa,Q,5,100,0,0,0,0:1,-1,0ÿ:wa,J,3,5,0,0,0,0:1,-1,0ÿ:wa,J,4,25,0,0,0,0:1,-1,0ÿ:wa,J,5,100,0,0,0,0:1,-1,0ÿ:wa,T,3,5,0,0,0,0:1,-1,0ÿ:wa,T,4,25,0,0,0,0:1,-1,0ÿ:wa,T,5,100,0,0,0,0:1,-1,0ÿ:s,0ÿ:i,10ÿ:m,10ÿ:a,0,0ÿ:g,5,1000,-1,false,0,falseÿ:es,0,0ÿ:mbnr,0.0ÿ:fs,0,0,0,0,0,0ÿbs,0,1,0ÿ:k,nullÿe,10,0,0,-1ÿb,0,0,0ÿs,1ÿr,0,5,51,78,36,153,20ÿx,2,,lv:1;2;10ÿrw,0";
            }
        }
        #endregion

        public CashConnectionBookOfRaGameLogic()
        {
            _gameID = GAMEID.CashConnectionBookOfRa;
            GameName = "CashConnectionBookOfRa";
        }

        protected override string buildLineBetString(string strGlobalUserID, double balance)
        {
            return string.Format("\u0006S{0}ÿA0ÿC,100.0,,1,ÿT,0,0,0ÿRÿM,10,5000,1,-1,0ÿI00ÿH,0,0,0,0,0,0ÿY,7200,10ÿ:i,10ÿ:m,10ÿ:b,19,1,2,3,4,5,8,10,15,20,30,40,50,80,100,150,200,300,400,500ÿ:a,0,0ÿ:g,5,1000,-1,false,0,falseÿ:es,0,0ÿ:mbnr,1.0ÿbs,0,1,0ÿ:k,nullÿe,{1},{2},{3},-1ÿb,1000,1000,0ÿs,1ÿr,0,5,51,78,36,153,20ÿx,2,,lv:5;49;50ÿrw,0", balance, !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? this._defaultLine : _dicUserBetInfos[strGlobalUserID].PlayLine, !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? this._defaultBetPerLine : (_dicUserBetInfos[strGlobalUserID].PlayBet / _dicUserBetInfos[strGlobalUserID].PlayLine), !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? Array.IndexOf(_supportLines, this._defaultLine) : Array.IndexOf(_supportLines, _dicUserBetInfos[strGlobalUserID].PlayLine));
        }

        protected override void onDoInit(string strGlobalUserID, GITMessage message, double balance, Currencies currency)
        {
            try
            {
                GITMessage resMessage = new GITMessage((ushort)SCMSG_CODE.SC_GREENTUBE_DOINIT);
                resMessage.Append("%t0ÿq0");
                resMessage.Append(VersionCheckString);
                foreach (string currencyName in SupportCurrencyList)
                {
                    resMessage.Append(currencyName);
                }
                resMessage.Append(buildInitString(strGlobalUserID, balance, currency));
                resMessage.Append("\vGAMEVARIATIONÿ665ÿTICKETSÿ1");
                resMessage.Append("$20ÿ5000ÿgrandÿ21.9261057ÿmajorÿ4.0185388");
                resMessage.Append(GameUniqueString);

                resMessage.Append("%t0ÿq0");
                resMessage.Append($"\aNATIVEJACKPOTCURRENCYFACTORÿ100.0ÿMAXBUYINTOTALÿ0ÿNEEDSSESSIONTIMEOUTÿ0ÿRELIABILITYÿ0ÿNICKNAMEÿ155258EURÿIDÿ155258ÿISDEEPWALLETÿ0ÿCURRENCYFACTORÿ100.0ÿMINBUYINÿ1ÿSESSIONTIMEOUTMINUTESÿ60ÿJACKPOT_PROGRESSIVE_CAPÿ0.0ÿNATIVEJACKPOTCURRENCYÿ{getCurrencyCode(currency)}ÿEXTUSERIDÿDummyDB_ExternalUserId_155258EURÿFREESPINSISCAPREACHEDÿ0ÿCURRENCYÿ{getCurrencySymbol(currency)}ÿTICKETSÿ0ÿJACKPOT_TOTAL_CAPÿ0.0ÿJACKPOTFEEPERCENTAGEÿ0.0ÿISSHOWJACKPOTCONTRIBUTIONÿ0");
                resMessage.Append(buildLineBetString(strGlobalUserID, balance));
                resMessage.Append("$20ÿ5000ÿgrandÿ21.9261057ÿmajorÿ4.0185388");

                ToUserMessage toUserMessage = new ToUserMessage((int)_gameID, resMessage);

                Sender.Tell(toUserMessage, Self);
            }
            catch (Exception ex)
            {
                _logger.Error("Exception has been occurred in BaseGreentubeSlotGame::onDoInit GameID: {0}, {1}", _gameID, ex);
            }
        }
        protected override void onBalanceConfirm(string strGlobalUserID, GITMessage message, double balance, Currencies currency)
        {
            try
            {
                GITMessage resMessage = new GITMessage((ushort)SCMSG_CODE.SC_GREENTUBE_BALANCECONFIRM);
                resMessage.Append("%t0ÿq0");
                resMessage.Append($"\aNATIVEJACKPOTCURRENCYFACTORÿ100.0ÿMAXBUYINTOTALÿ0ÿNEEDSSESSIONTIMEOUTÿ0ÿRELIABILITYÿ0ÿNICKNAMEÿ155258EURÿIDÿ155258ÿISDEEPWALLETÿ0ÿCURRENCYFACTORÿ100.0ÿMINBUYINÿ1ÿSESSIONTIMEOUTMINUTESÿ60ÿJACKPOT_PROGRESSIVE_CAPÿ0.0ÿNATIVEJACKPOTCURRENCYÿ{getCurrencyCode(currency)}ÿEXTUSERIDÿDummyDB_ExternalUserId_155258EURÿFREESPINSISCAPREACHEDÿ0ÿCURRENCYÿ{getCurrencySymbol(currency)}ÿTICKETSÿ0ÿJACKPOT_TOTAL_CAPÿ0.0ÿJACKPOTFEEPERCENTAGEÿ0.0ÿISSHOWJACKPOTCONTRIBUTIONÿ0");
                resMessage.Append(buildLineBetString(strGlobalUserID, balance));
                ToUserMessage toUserMessage = new ToUserMessage((int)_gameID, resMessage);

                Sender.Tell(toUserMessage, Self);
            }
            catch (Exception ex)
            {
                _logger.Error("Exception has been occurred in BaseGreenSlotGame::onDoInit GameID: {0}, {1}", _gameID, ex);
            }
        }
    }
}
