using GITProtocol;
using SlotGamesNode.GameLogics.BaseClasses;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SlotGamesNode.GameLogics
{
    internal class CashConnectionGoldenBookOfRaGameLogic : BaseGreenLockRespinSlotGame
    {
        #region
        protected override string ScatterSymbol {
            get
            {
                return "D";
            }
        }

        protected override int MinCountToFreespin
        {
            get
            {
                return 6;
            }
        }

        protected override string VersionCheckString
        {
            get
            {
                return "\b0ÿ2.5.16ÿCasino-Lobbymanager-Serverÿ11289ÿ1.10.54.0ÿGTATCashConnectionServerÿ13275ÿ1.1.0ÿCash Connection - Golden Book of Ra Linked 95%ÿ1.118.0_2025-03-28_090804ÿ1.51.0";
            }
        }

        protected override string GameUniqueString
        {
            get
            {
                return "\u0006S0ÿA1ÿRÿM,10,10000,20,-1,0ÿI00ÿH,0,0,0,0,0,0ÿ:n,Cash Connection - Golden Book of Ra Linked 95%ÿ:v,3ÿ:l,-----ÿ:l,^^^^^ÿ:l,_____ÿ:l,^-_-^ÿ:l,_-^-_ÿ:l,-___-ÿ:l,-^^^-ÿ:l,__-^^ÿ:l,^^-__ÿ:l,_---^ÿ:r,0,TQABJTKMJTQEATSQTKCJQTDDDAQSKJMAKSQJCKASTQABJTKMJTQEATSQTKCJQTDDDAQSKJMAKSQJCKASTQABJTKMJTQEATSQTKCJQTDDDAQSKJMAKSQJCKASÿ:r,0,TASKQBTJQDDJQCAJMQKCTJSAKEATCKADDJKQMAKCTASKQBTJQDDJTQCAJMQKCTJSAKEATCKADDJKQMAKCTASKQBTJQDDJQCAJMQKCTJSAKEATCKQADDJKQMAKCÿ:r,0,TJEQTDDDQAKSQJTSKQMJTSAQEKJTMQJAKDDAQTSJATEBKQAMJKQSTKCJQEKJSTQCATSKTJEKTACJKMAJCTACKJCAQSKTJCTJEQTSDDDQAKSQJTSKCQMJTSAQEKJTMQAKDDATSJATBKQAMJKSTKCJQEKJSTQCATSKJEKTACJKMAJCKTACKJCAQSTMJCTJEQTDDDTQAKSQJTSKQMJTSAQEKJTMQAKDDJATSJATBKQACMJKSTKCJQEKJSTQCATSKJEKTACJKMAJCTACKJCAQSTJCÿ:r,0,TACQKJSKQCJKSATCKQDDKAJQSTAETJQBKTASKTJEQMASJTKEJATCJKAMJQSAKTCQKDDDJQSJTCQJAMSQTEAQCKTAMKQSJTACKJSKMQCJKSQATCKQDDKAQSTJAETJQBKTASKTJEQASJTKEJATCJTKAMJTQSAKTCQKDDDJQSJTCQJAMQTEAQCTAMKQSJTACKJSKQCJKSAMTCKQDDKCAQSTAETJQBKTASKTJEQASJTKEJATCJKAMJQSAKTCQKDDDJQSJTCQJAMQTEAQCTAMKQSJÿ:r,0,JQMTJBKAEQKSJQETASQJMTQKCAJSTQDDAJSATQCKAECTJCKQCJKMQKSTQEAJSKQACJKMATESATQCKTSQATSJADDDQTSAJQMTJBKAEQKSJQETASQJMTKCAJSKTQDDAJSATQCKACTJCKQCJKMQKSTQEAJSKQCJKMATEATQCKTSQATSJADDDQTESAJQMTJBKAEQKSJQETASQJCMTKCAJSTQDDAJSATQCKACTJCKQCJKMQAKSTQEAJSKQCJKMATEATQCKTSQATSJADDDQTSAÿ:r,1,TQABJTKMJTQEATSQTKCJQTDDDAQSKJMAKSQJCKASTQABJTKMJTQEATSQTKCJQTDDDAQSKJMAKSQJCKASTQABJTKMJTQEATSQTKCJQTDDDAQSKJMAKSQJCKASÿ:r,1,TASKQBTJQDDJQCAJMQKCTJSAKEATCKADDJKQMAKCTASKQBTJQDDJTQCAJMQKCTJSAKEATCKADDJKQMAKCTASKQBTJQDDJQCAJMQKCTJSAKEATCKQADDJKQMAKCÿ:r,1,TJEQTDDDQAKSQJTSKQMJTSAQEKJTMQJAKDDAQTSJATEBKQAMJKQSTKCJQEKJSTQCATSKTJEKTACJKMAJCTACKJCAQSKTJCTJEQTSDDDQAKSQJTSKCQMJTSAQEKJTMQAKDDATSJATBKQAMJKSTKCJQEKJSTQCATSKJEKTACJKMAJCKTACKJCAQSTMJCTJEQTDDDTQAKSQJTSKQMJTSAQEKJTMQAKDDJATSJATBKQACMJKSTKCJQEKJSTQCATSKJEKTACJKMAJCTACKJCAQSTJCÿ:r,1,TACQKJSKQCJKSATCKQDDKAJQSTAETJQBKTASKTJEQMASJTKEJATCJKAMJQSAKTCQKDDDJQSJTCQJAMSQTEAQCKTAMKQSJTACKJSKMQCJKSQATCKQDDKAQSTJAETJQBKTASKTJEQASJTKEJATCJTKAMJTQSAKTCQKDDDJQSJTCQJAMQTEAQCTAMKQSJTACKJSKQCJKSAMTCKQDDKCAQSTAETJQBKTASKTJEQASJTKEJATCJKAMJQSAKTCQKDDDJQSJTCQJAMQTEAQCTAMKQSJÿ:r,1,JQMTJBKAEQKSJQETASQJMTQKCAJSTQDDAJSATQCKAECTJCKQCJKMQKSTQEAJSKQACJKMATESATQCKTSQATSJADDDQTSAJQMTJBKAEQKSJQETASQJMTKCAJSKTQDDAJSATQCKACTJCKQCJKMQKSTQEAJSKQCJKMATEATQCKTSQATSJADDDQTESAJQMTJBKAEQKSJQETASQJCMTKCAJSTQDDAJSATQCKACTJCKQCJKMQAKSTQEAJSKQCJKMATEATQCKTSQATSJADDDQTSAÿ:r,2,TQABJTKMJTQEATSQTKCJQTDDDAQSKJMAKSQJCKASTQABJTKMJTQEATSQTKCJQTDDDAQSKJMAKSQJCKASTQABJTKMJTQEATSQTKCJQTDDDAQSKJMAKSQJCKASÿ:r,2,TASKQBTJQDDJQCAJMQKCTJSAKEATCKADDJKQMAKCTASKQBTJQDDJTQCAJMQKCTJSAKEATCKADDJKQMAKCTASKQBTJQDDJQCAJMQKCTJSAKEATCKQADDJKQMAKCÿ:r,2,TJEQTDDDQAKSQJTSKQMJTSAQEKJTMQJAKDDAQTSJATEBKQAMJKQSTKCJQEKJSTQCATSKTJEKTACJKMAJCTACKJCAQSKTJCTJEQTSDDDQAKSQJTSKCQMJTSAQEKJTMQAKDDATSJATBKQAMJKSTKCJQEKJSTQCATSKJEKTACJKMAJCKTACKJCAQSTMJCTJEQTDDDTQAKSQJTSKQMJTSAQEKJTMQAKDDJATSJATBKQACMJKSTKCJQEKJSTQCATSKJEKTACJKMAJCTACKJCAQSTJCÿ:r,2,TACQKJSKQCJKSATCKQDDKAJQSTAETJQBKTASKTJEQMASJTKEJATCJKAMJQSAKTCQKDDDJQSJTCQJAMSQTEAQCKTAMKQSJTACKJSKMQCJKSQATCKQDDKAQSTJAETJQBKTASKTJEQASJTKEJATCJTKAMJTQSAKTCQKDDDJQSJTCQJAMQTEAQCTAMKQSJTACKJSKQCJKSAMTCKQDDKCAQSTAETJQBKTASKTJEQASJTKEJATCJKAMJQSAKTCQKDDDJQSJTCQJAMQTEAQCTAMKQSJÿ:r,2,JQMTJBKAEQKSJQETASQJMTQKCAJSTQDDAJSATQCKAECTJCKQCJKMQKSTQEAJSKQACJKMATESATQCKTSQATSJADDDQTSAJQMTJBKAEQKSJQETASQJMTKCAJSKTQDDAJSATQCKACTJCKQCJKMQKSTQEAJSKQCJKMATEATQCKTSQATSJADDDQTESAJQMTJBKAEQKSJQETASQJCMTKCAJSTQDDAJSATQCKACTJCKQCJKMQAKSTQEAJSKQCJKMATEATQCKTSQATSJADDDQTSAÿ:r,3,TQABJTKMJTQEATSQTKCJQTDDDAQSKJMAKSQJCKASTQABJTKMJTQEATSQTKCJQTDDDAQSKJMAKSQJCKASTQABJTKMJTQEATSQTKCJQTDDDAQSKJMAKSQJCKASÿ:r,3,TASKQBTJQDDJQCAJMQKCTJSAKEATCKADDJKQMAKCTASKQBTJQDDJTQCAJMQKCTJSAKEATCKADDJKQMAKCTASKQBTJQDDJQCAJMQKCTJSAKEATCKQADDJKQMAKCÿ:r,3,TJEQTDDDQAKSQJTSKQMJTSAQEKJTMQJAKDDAQTSJATEBKQAMJKQSTKCJQEKJSTQCATSKTJEKTACJKMAJCTACKJCAQSKTJCTJEQTSDDDQAKSQJTSKCQMJTSAQEKJTMQAKDDATSJATBKQAMJKSTKCJQEKJSTQCATSKJEKTACJKMAJCKTACKJCAQSTMJCTJEQTDDDTQAKSQJTSKQMJTSAQEKJTMQAKDDJATSJATBKQACMJKSTKCJQEKJSTQCATSKJEKTACJKMAJCTACKJCAQSTJCÿ:r,3,TACQKJSKQCJKSATCKQDDKAJQSTAETJQBKTASKTJEQMASJTKEJATCJKAMJQSAKTCQKDDDJQSJTCQJAMSQTEAQCKTAMKQSJTACKJSKMQCJKSQATCKQDDKAQSTJAETJQBKTASKTJEQASJTKEJATCJTKAMJTQSAKTCQKDDDJQSJTCQJAMQTEAQCTAMKQSJTACKJSKQCJKSAMTCKQDDKCAQSTAETJQBKTASKTJEQASJTKEJATCJKAMJQSAKTCQKDDDJQSJTCQJAMQTEAQCTAMKQSJÿ:r,3,JQMTJBKAEQKSJQETASQJMTQKCAJSTQDDAJSATQCKAECTJCKQCJKMQKSTQEAJSKQACJKMATESATQCKTSQATSJADDDQTSAJQMTJBKAEQKSJQETASQJMTKCAJSKTQDDAJSATQCKACTJCKQCJKMQKSTQEAJSKQCJKMATEATQCKTSQATSJADDDQTESAJQMTJBKAEQKSJQETASQJCMTKCAJSTQDDAJSATQCKACTJCKQCJKMQAKSTQEAJSKQCJKMATEATQCKTSQATSJADDDQTSAÿ:r,4,JMKJEKASTKJAMQTGAJMQATKJMQKACQJSKACQAJMKJEKASTKJAMQTGAJMQTKJMQKACQAJSKATCQAJMKJEKASTKJAMQTGAJMQTKJMQKACQJSKACQAÿ:r,4,QSJKTCJGKQATQEJACJQATKSAJQTMJAKQJCTQAKTQSKTCJGKQATQEJACJQATKSAJQTMJAQJCTAKTQSKTCJGKQATQEKJACJQATKSAJQTMJAQJCTAKTÿ:r,4,AEQTEKJEQSJKCQAETAKMQAJKTJAGTKJMTQSKJAEQTEKJQSJKCQAETAKMQAJKTJAGTKJMTQSKJAEQTEKJQSJKCQAETAKMQAJKETJAGTKJMTQSKJÿ:r,4,GTKQCKTMQJEAQSKQCTKSQTCAJETJGTKSQAKTCQJGTSKQCKMQJEAQGSKQCTKSQTCAJETJGTKSAKTCQJGTKQCKMQJEAQSKQCTKSQTCAJETJGTKSAKTCQJÿ:r,4,QCTKMQASTJGKJMASCJEAJGTSAEKCTMQSKCQMTEQCTKMQASTJGKJTMASJEAJGTSAJEKCTMQSKCQMTEQCTKMQASTJGKJMATSJEAJGTSAEKCTMQASKCQMTEÿ:r,5,JMKJZKASTCKJAMQTGAJMQTKJMQKACQMJSKAJCQAJMKJZKASTKJAMQTGAJMCQTKJMQKACQJSKACTQAJMKJZKASTKJAMQTGAJMQTKJMQKACQJSMKACQAÿ:r,5,QSJKTCJGKQATQZJACJQATKSAJQTMJAQJCTAKTQSKTACJGKQATQZJACJQATKSAJQKTMJAQJCTAKTQSKTCJGKQATQZJACJQATQKSAJQTMJAQJCTAKTÿ:r,5,AZQTZKJQSJKCQAZTAKMQAJKTJAZGTKJMTQSKJAZQTZKJQSJKCQAZTAKMQAZJKTQJAGZTKJMTQSKJAZQTZKJQSJKCQAZTAKMQAJKTJZAGTKJMTQSKJÿ:r,5,GTSKQCKMQJZAQSKQCTKSQTCAJZTJGTKSAKTCQJGTKQCKMQJZAQSKQCTKSQTCAJZTJGTKSAKTCQJGTKQCTKMQJZAQSKQCTKSQJTCAJZTJGTKSAKTCQJÿ:r,5,QJCTKMQASTJGKJMASJZAJGTSAZKCTMQSKJCQMTZQCTKMQASTJGKJMASJZAJGTSQAZKJCTMQSKCQJMTZQCTKMQASTJQGKJMASJZAJQGTSAJZKCTMQSKCQMTZÿ:r,6,JYAKJEKASTKJCAYQTGAKJYQTKJYQKACQJSKACQAJYKJECKASTKJAYQTCGAJYQTKJYQKACQJSKACQAJYKJEKASTKJAYJQTGCAJYQTKJYQKACQJSKACQAÿ:r,6,QJSKTCJGKQATQEJACJQATKSAJQTYJAQJCTAKTQSKATCJGKQATQEJACJQATKSAJQTYJAQJCTAKTQSKTCJGKQATQEJACJQATKSAJQTYJAQJCTAKTÿ:r,6,AEQTEKJQASJKCQAETAKYQAJKTJAGTKJYTQSKJAEQTEKJQSJKCQAETAKYQAJKTJAGTKJYTQSKJAEQTEKJQSJKCQAETAKYQAJKTJAGTKJYTQSKJÿ:r,6,GTKQCSKYQJEAQSKQCTKSQTCAJETJCGTKSAKTCQJGTKQCKYQJEAQSGKQCTKSQTCAJETJGTKSAKTCQJGTKQCKYQJEAQSKQCTKSQTCAJETJGTKQSAKTCQJÿ:r,6,QCATKYQASTQJGKJYASCJEAJGTSAEKCTYAQSKCQYTEQCTKYQASTJEGKJYASJCEAJGTSAEKCTYQGSKCQYTEQCTKYQASTJGKJYASJEAJGTSAEKCTYQSKCQYTEÿ:r,7,JMKJEKAXTKJAMQTGAJMQTKJMQKACQJXKACQAJMKJEKAXTKJAMQTGAJMQTKJMQKACQJXKACQAJMKJEKAXTKJAMQTGAJMQTKJMQKACQJXKACQAÿ:r,7,QXKTCJGKQATQKEJACJQATKXAJQTMJAQKJCTAKTQXKTCJGKQATQEJACJQATKXAJQTMJAQJCTAKTQXKTCJGKQATQEJACJQATKXAJQTMJAQJCTAKTÿ:r,7,AEQTEKAJQXJTKCQAETAKMQAJKTJAGTKJMTQXKJAEQTEKJQTXJKCQAETAKMQAJKTJAGTKJMTQXKJAEQTEKJQXEJKCQAETAKMEQAJKTJAGTKJMTEQXKJÿ:r,7,GTKQCKMQJEAQXKQCTKXQTCAJETJGTKXAKTCQJGTKQCKXMQJEAQXKQCTKXQTCAJQETJGTKXAKTCQJGTKQCKMQJEAQXKQCTKXQTCAJEQTJGTKXAKTCQJÿ:r,7,QCTKMQAXTJGKJMAXJEAJGTQXAEKCTMQXKCQMTEQCTKMQAEXTJGKJMAXJEAJGTXAEKCTMQXGKCQMTEQCTKMQAXTJGKJMAXJKEAJGTXAEKJCTMQXKCQMTEÿ:r,8,JMKJEKASTIKJAMQTGAJMQTKJMQKAIQMJSKAIQAJMKJEKAQSTKJIAMQTGAJMQATKJMQKAIQJSKAIQAJMKQJEKASITKJAMQTIGAJMQTKJMQKAIQJSKAIQAÿ:r,8,QSKTAIJGKQATQEJAIJQATKSTAJQTMJAQJITAKTQSKTIJGKQATQEJAIJQATKSAJQTMJAQJITAKTQSKTIJGKQATQEJTAIJQATKSAJQTMJAQJITAKTÿ:r,8,AEQTEKJQSJKIQAETAKMQAJKTJAGTKJMTQSKJAEQTEKJQSJKIQAETAKMQAJKTJAGTKJMTQSKJAEQTEKJQSJKIQAETAKMQAJKETJAGTEKJMTQSKJÿ:r,8,GTKQISKMQJEAQJSKQITKSQTIAJETJGTKSAKTIQJGTKQIKMQJEAQSKQITGKSQTIAJETQJGTKJSAKTIQJGTKQIKMQJEAQSKQITKSQTIAJETJGTKSAKTIQJÿ:r,8,QITKMQASTJGKJMASQJEAJGTSAEKITMQSKIQMTEQITKMQASTJGKJMASJEKAJGTSAEKITMQSKIQMTEQITKMQASTJGKJQMASJEAJGTSAEKITMQSKIQMTEÿ:r,9,JMKJEKHQSTKJHMQTGHJMQTKHJMQKHCQJSKJHCQHJMKJQEKHSTKJHMQTCGHJMQTKJMQKHCQJSKHCQHJMKJEKHSTKJHMQTGHJMQTKJMQKHCQJMSKHCQHÿ:r,9,QHSKTCJGKQHTQEJHCJQHTKSHJQTMJHQJCTHKTQSJKTCJGKQHTQEJHCJQHTKSHJKQTMJHQJCTHKTQSKTCJGKQHTKQEJHCJQHTKSHJQTMJHQJCTHKTÿ:r,9,HEQTEKJQHSJKECQHETHKMQHJKTJHGTKJMTQSKJHEQTEKJQSTJKCQHETHKMQHJKTJHGTKJMTQSKJHEQTEKJQSJHKCQHETHKMQHJKTJHGTKJMTQSKJÿ:r,9,GTKQCKMQJEHTQSKQCTKSQTCHKJETJGTKSHKTCQJGTKQCKMQJEHQSGKQCTKSQTCHJETKJGTKSHKTCQJGTKQCKMQJEHQSKQCTKSQTKCHJETJGTKSJHKTCQJÿ:r,9,QCTKMQHSTJGKJMHSJEHJGTSHEKCTMQSHKCQMTEQCTKMQHSTJGKJMHSJEQHJGTSHEKCTMQSKCQMTEQCTKMQHSTJGKJMHSJEHJGTJSHEKCTMQJSKCQMTEÿ:r,10,JMNJENASTNJAMQTGAJMQTNJAMQNACQJSNACQAJMNJENASTNJACMQTGAJMQTNJMQNTACQJSNACTQAJMNJENASTNJAMQTGAJMQTNJMQNACQJSNACQAÿ:r,10,QSNTCJGNQATQEJACJQATNSAJQTMJAQJCTANTQSNTCJGNQATQEJACTJQATNSAJQTMJAQJCTANTQSNTCJGNQATQEJACJQATNSAJQTMJAQJCTANTÿ:r,10,AEQTENJQSTJNCQAETANJMQAJNTQJAGTNJMTQSNJAEQTENJQSJNCQAETANMQAJNTJAGTNJMTQSNJAEQTENJQSJNCQAETANMQAJNTJAGTNJMTQSNJÿ:r,10,GTNQCNMQJEAQSJNQCTJNSQTCAJETJGTNSANTCQJGTNQCNMQJEAQSNQCTNSQTCAJENTJGTNSANTCQJGTNQCNMQJEAQSNQCTNSQTCNAJETJGTNSANTCQJÿ:r,10,QCTNMQASTJGNJMASJEAJGMTSAENCTMQSNCQMTEQCTNMQASTJGNJMASJEAJGTSAENCTMQSNJCQMTEQCTNMQASTJGNJMASJECAJGTSAENCTMQSNCQMTEÿ:r,11,JMKJEKASFTKJAMFTGAJMFTKJMFKACFJSKACFAJMKFJEKASTKJAMFTGAJMFTKJAMFKACFJSKACFAJMKJEKASTKJAMFTGAJMFTKJMFKACFJSKACFAÿ:r,11,FSKTCJGKFAJTFEJTACJFATKSTAJFTMJAFJCTAKTFSKTCJGKFATFEJACJFATKSAJFTMJAFJCTAKTFSKTCJGKFATFEJACJFATKSAJFTMJAFJCTAKTÿ:r,11,AEFTEKJFSEJKCFAETAKMFAJKTJAGTKJMETFSKJAEFTEKJFSJKCFAETAKMFAJKTJAGTKJMTFSKJAEFJTEKJFASJKCFAETAJKMFAJKTJAGTKJMTFSKJÿ:r,11,GTKFCKMFJEAFSKFCTKSFTCAJETJGTKSAKTCFJGTKFCKMFKJEAFSKFCTKSFTCAJETJGTKSAKTCFJGTKFCKTMFJEATFSKFCTKSFTCAJETJGTJKSAKTCFJÿ:r,11,FCTKMFASTJGKJMATSJEAJGTSAEKJCTMFSKCFGMTEFCTKMFASTJGKJMASFJEAJGTMSAEKCTMAFSKCFMTEFCTKMFASTJGKFJMASJEAJGTSAEKCTMFSAKCFMTEÿ:r,12,LMKLEKASTKLAMQTGALMQTKALMQKACQLSKACQALMKLEKASTKLAMQTCGALMQTKLMQKACQLSKLACQALMKLEKASTKLAMCQTGALMQTKLMQKACQLSKACQAÿ:r,12,QSKTCLGKQATQELACLQATKSALQTMLAQLCTAKTQSKTCLGKQATQELACLQATKSALQTMLAQLCTAKTQSKTCLGKQATQELACLQATKSALQTMLAQLCTAKTÿ:r,12,AEQTEKLQTSLKCQAETAKMQALKTLAGTKLMTAQSKLAEQTEKLQSLKCQAETAKMQALKTLAGTKALMTQSKLAEQTEKLQSLKCQAETAKMQALKTLAGTKLMTQSKLÿ:r,12,GTKQCKMQLEAQSKQCTKSQTCALETLGTKSAKTCQLGTKQCKMQLEAQSKQCTKSQTKCALETLGTKSAKLTCQLGTKQCKMQLEAQSKQCTKSLQTCALETLGTKSAKTCQLÿ:r,12,QCTKMQASTLGKLMASLEALGMTSAEKCTMQSKCQMTEQCTKMQASTLGKLMASLEALGTSAEKCTMQSKCGQMTEQCTKMQASTLGKLMASLEALGTSAEKCTMQSKCQMTEÿ:r,13,JMKJEKASOKJAMQOGAJMQOKJMQKACQJSKACQAJMKJEKASOKJAMQOGAJMQOKJMQKACQJSKACQAJMKJEKASOKJAMQOGAJMQOKJMQKACQJSKJACQAÿ:r,13,QSKOCJGKQAOQEJACOJQAOJKSAJQOMJAQJCOAKOQSKOCJGKQAOQEJACJQAOKSAJQOMJAQJCOAKOQSKOCJGKQAOQEJAKCJQAOKSAJQOMJAQJCOAKOÿ:r,13,AEQOEKJQSOJKCQAEOAKMQAJKOJAGOKJMOQSKJAEQOEKJAQSJKCQAEOAKMQAJKOJAGOKJMOQSKJAEQOEKJQSJKCQAEOAKMEQAJKOJAGOKJMOQSKJÿ:r,13,GSOKQCKMQJEAQSKQCOKSQKOCAJEOJGOKSAKOCQJGOKQCJKMQJEAJQSKQCOKSQOCAJEOJGOKSAKOCQJGOKQCKMQJEAQSKQCOKSQOCAJEOJGOKSAKOCQJÿ:r,13,QCOKMQASOJGKJMACSJEAJGOSAEKCOMQSKCQMOEQCOKMQASOJGKJMASJEAJGOSAEKCOMQSKCQMOEQCOKMQACSOJQGKJMASJEAJGOSAEKCOMQSKCQMOEÿ:j,B,1,0,EMSCAKQJTÿ:j,G,1,0,EMSCAKQJTÿ:u,APPPP.PP.PP.PPPPÿ:w,D,103,-12500,99.0:Major,12500.0ÿ:w,D,102,-75000,99.0:Grand,75000.0ÿ:w,D,14,-1,0ÿ:w,D,13,-1,0ÿ:w,D,12,-1,0ÿ:w,D,11,-1,0ÿ:w,D,10,-1,0ÿ:w,D,9,-1,0ÿ:w,D,8,-1,0ÿ:w,D,7,-1,0ÿ:w,D,6,-1,0ÿ:w,Z,2,-10,0ÿ:w,Z,3,-100,0ÿ:w,Z,4,-1000,0ÿ:w,Z,5,-5000,0ÿ:w,Y,2,-5,0ÿ:w,Y,3,-40,0ÿ:w,Y,4,-400,0ÿ:w,Y,5,-2000,0ÿ:w,X,2,-5,0ÿ:w,X,3,-30,0ÿ:w,X,4,-100,0ÿ:w,X,5,-750,0ÿ:w,I,2,-5,0ÿ:w,I,3,-30,0ÿ:w,I,4,-100,0ÿ:w,I,5,-750,0ÿ:w,H,3,-5,0ÿ:w,H,4,-40,0ÿ:w,H,5,-150,0ÿ:w,N,3,-5,0ÿ:w,N,4,-40,0ÿ:w,N,5,-150,0ÿ:w,F,3,-5,0ÿ:w,F,4,-25,0ÿ:w,F,5,-100,0ÿ:w,L,3,-5,0ÿ:w,L,4,-25,0ÿ:w,L,5,-100,0ÿ:w,O,3,-5,0ÿ:w,O,4,-25,0ÿ:w,O,5,-100,0ÿ:w,B,2,10,0ÿ:w,B,3,100,0ÿ:w,B,4,1000,0ÿ:w,B,5,5000,0ÿ:w,E,2,10,0ÿ:w,E,3,100,0ÿ:w,E,4,1000,0ÿ:w,E,5,5000,0ÿ:w,M,2,5,0ÿ:w,M,3,40,0ÿ:w,M,4,400,0ÿ:w,M,5,2000,0ÿ:w,S,2,5,0ÿ:w,S,3,30,0ÿ:w,S,4,100,0ÿ:w,S,5,750,0ÿ:w,C,2,5,0ÿ:w,C,3,30,0ÿ:w,C,4,100,0ÿ:w,C,5,750,0ÿ:w,A,3,5,0ÿ:w,A,4,40,0ÿ:w,A,5,150,0ÿ:w,K,3,5,0ÿ:w,K,4,40,0ÿ:w,K,5,150,0ÿ:w,Q,3,5,0ÿ:w,Q,4,25,0ÿ:w,Q,5,100,0ÿ:w,J,3,5,0ÿ:w,J,4,25,0ÿ:w,J,5,100,0ÿ:w,T,3,5,0ÿ:w,T,4,25,0ÿ:w,T,5,100,0ÿ:wa,D,103,-12500,99.0:Major,12500.0,0,0:1,-1,0ÿ:wa,D,102,-75000,99.0:Grand,75000.0,0,0:1,-1,0ÿ:wa,D,14,-1,0,0,0,0:1,-1,0ÿ:wa,D,13,-1,0,0,0,0:1,-1,0ÿ:wa,D,12,-1,0,0,0,0:1,-1,0ÿ:wa,D,11,-1,0,0,0,0:1,-1,0ÿ:wa,D,10,-1,0,0,0,0:1,-1,0ÿ:wa,D,9,-1,0,0,0,0:1,-1,0ÿ:wa,D,8,-1,0,0,0,0:1,-1,0ÿ:wa,D,7,-1,0,0,0,0:1,-1,0ÿ:wa,D,6,-1,0,0,0,0:1,-1,0ÿ:wa,G,3,-2,0,0,0,0:1,5,0ÿ:wa,G,4,-20,0,0,0,0:1,5,0ÿ:wa,G,5,-200,0,0,0,0:1,5,0ÿ:wa,G,3,-2,0,0,0,0:1,6,0ÿ:wa,G,4,-20,0,0,0,0:1,6,0ÿ:wa,G,5,-200,0,0,0,0:1,6,0ÿ:wa,G,3,-2,0,0,0,0:1,7,0ÿ:wa,G,4,-20,0,0,0,0:1,7,0ÿ:wa,G,5,-200,0,0,0,0:1,7,0ÿ:wa,G,3,-2,0,0,0,0:1,8,0ÿ:wa,G,4,-20,0,0,0,0:1,8,0ÿ:wa,G,5,-200,0,0,0,0:1,8,0ÿ:wa,G,3,-2,0,0,0,0:1,9,0ÿ:wa,G,4,-20,0,0,0,0:1,9,0ÿ:wa,G,5,-200,0,0,0,0:1,9,0ÿ:wa,G,3,-2,0,0,0,0:1,10,0ÿ:wa,G,4,-20,0,0,0,0:1,10,0ÿ:wa,G,5,-200,0,0,0,0:1,10,0ÿ:wa,G,3,-2,0,0,0,0:1,11,0ÿ:wa,G,4,-20,0,0,0,0:1,11,0ÿ:wa,G,5,-200,0,0,0,0:1,11,0ÿ:wa,G,3,-2,0,0,0,0:1,12,0ÿ:wa,G,4,-20,0,0,0,0:1,12,0ÿ:wa,G,5,-200,0,0,0,0:1,12,0ÿ:wa,G,3,-2,0,0,0,0:1,13,0ÿ:wa,G,4,-20,0,0,0,0:1,13,0ÿ:wa,G,5,-200,0,0,0,0:1,13,0ÿ:wa,Z,2,-10,0,0,0,0:1,-1,0ÿ:wa,Z,3,-100,0,0,0,0:1,-1,0ÿ:wa,Z,4,-1000,0,0,0,0:1,-1,0ÿ:wa,Z,5,-5000,0,0,0,0:1,-1,0ÿ:wa,Y,2,-5,0,0,0,0:1,-1,0ÿ:wa,Y,3,-40,0,0,0,0:1,-1,0ÿ:wa,Y,4,-400,0,0,0,0:1,-1,0ÿ:wa,Y,5,-2000,0,0,0,0:1,-1,0ÿ:wa,X,2,-5,0,0,0,0:1,-1,0ÿ:wa,X,3,-30,0,0,0,0:1,-1,0ÿ:wa,X,4,-100,0,0,0,0:1,-1,0ÿ:wa,X,5,-750,0,0,0,0:1,-1,0ÿ:wa,I,2,-5,0,0,0,0:1,-1,0ÿ:wa,I,3,-30,0,0,0,0:1,-1,0ÿ:wa,I,4,-100,0,0,0,0:1,-1,0ÿ:wa,I,5,-750,0,0,0,0:1,-1,0ÿ:wa,H,3,-5,0,0,0,0:1,-1,0ÿ:wa,H,4,-40,0,0,0,0:1,-1,0ÿ:wa,H,5,-150,0,0,0,0:1,-1,0ÿ:wa,N,3,-5,0,0,0,0:1,-1,0ÿ:wa,N,4,-40,0,0,0,0:1,-1,0ÿ:wa,N,5,-150,0,0,0,0:1,-1,0ÿ:wa,F,3,-5,0,0,0,0:1,-1,0ÿ:wa,F,4,-25,0,0,0,0:1,-1,0ÿ:wa,F,5,-100,0,0,0,0:1,-1,0ÿ:wa,L,3,-5,0,0,0,0:1,-1,0ÿ:wa,L,4,-25,0,0,0,0:1,-1,0ÿ:wa,L,5,-100,0,0,0,0:1,-1,0ÿ:wa,O,3,-5,0,0,0,0:1,-1,0ÿ:wa,O,4,-25,0,0,0,0:1,-1,0ÿ:wa,O,5,-100,0,0,0,0:1,-1,0ÿ:wa,B,2,10,0,0,0,0:1,-1,0ÿ:wa,B,3,100,0,0,0,0:1,-1,0ÿ:wa,B,4,1000,0,0,0,0:1,-1,0ÿ:wa,B,5,5000,0,0,0,0:1,-1,0ÿ:wa,E,2,10,0,0,0,0:1,-1,0ÿ:wa,E,3,100,0,0,0,0:1,-1,0ÿ:wa,E,4,1000,0,0,0,0:1,-1,0ÿ:wa,E,5,5000,0,0,0,0:1,-1,0ÿ:wa,M,2,5,0,0,0,0:1,-1,0ÿ:wa,M,3,40,0,0,0,0:1,-1,0ÿ:wa,M,4,400,0,0,0,0:1,-1,0ÿ:wa,M,5,2000,0,0,0,0:1,-1,0ÿ:wa,S,2,5,0,0,0,0:1,-1,0ÿ:wa,S,3,30,0,0,0,0:1,-1,0ÿ:wa,S,4,100,0,0,0,0:1,-1,0ÿ:wa,S,5,750,0,0,0,0:1,-1,0ÿ:wa,C,2,5,0,0,0,0:1,-1,0ÿ:wa,C,3,30,0,0,0,0:1,-1,0ÿ:wa,C,4,100,0,0,0,0:1,-1,0ÿ:wa,C,5,750,0,0,0,0:1,-1,0ÿ:wa,A,3,5,0,0,0,0:1,-1,0ÿ:wa,A,4,40,0,0,0,0:1,-1,0ÿ:wa,A,5,150,0,0,0,0:1,-1,0ÿ:wa,K,3,5,0,0,0,0:1,-1,0ÿ:wa,K,4,40,0,0,0,0:1,-1,0ÿ:wa,K,5,150,0,0,0,0:1,-1,0ÿ:wa,Q,3,5,0,0,0,0:1,-1,0ÿ:wa,Q,4,25,0,0,0,0:1,-1,0ÿ:wa,Q,5,100,0,0,0,0:1,-1,0ÿ:wa,J,3,5,0,0,0,0:1,-1,0ÿ:wa,J,4,25,0,0,0,0:1,-1,0ÿ:wa,J,5,100,0,0,0,0:1,-1,0ÿ:wa,T,3,5,0,0,0,0:1,-1,0ÿ:wa,T,4,25,0,0,0,0:1,-1,0ÿ:wa,T,5,100,0,0,0,0:1,-1,0ÿ:s,0ÿ:i,10ÿ:m,10ÿ:a,0,0ÿ:g,5,1000,-1,false,0,falseÿ:es,0,0ÿ:mbnr,0.0ÿ:fs,0,0,0,0,0,0ÿbs,0,1,0ÿ:k,nullÿe,10,0,0,-1ÿb,0,0,0ÿs,1ÿr,0,5,22,14,85,82,12ÿx,2,dv:10001;10001;10001;-1;-1;-1;-1;-1;-1;-1;-1;-1;-1;-1;-1,lv:1;2;10ÿrw,0";
            }
        }
        #endregion

        public CashConnectionGoldenBookOfRaGameLogic()
        {
            _gameID = GAMEID.CashConnectionGoldenBookOfRa;
            GameName = "CashConnectionGoldenBookOfRa";
        }

        protected override string buildLineBetString(string strGlobalUserID, double balance)
        {
            return string.Format("\u0006S{0}ÿA0ÿC,100.0,,1,ÿT,0,0,0ÿRÿM,20,2000,20,-1,0ÿI00ÿH,0,0,0,0,0,0ÿY,7200,10ÿ:i,10ÿ:m,10ÿ:b,15,2,3,4,5,8,10,15,20,30,40,50,80,100,150,200ÿ:a,0,0ÿ:g,5,1000,-1,false,0,falseÿ:es,0,0ÿ:mbnr,20.0ÿbs,0,1,0ÿ:k,nullÿe,{1},{2},{3},-1ÿb,1000,1000,0ÿs,1ÿr,0,5,22,14,85,82,12ÿx,2,dv:10001;10001;10001;-1;-1;-1;-1;-1;-1;-1;-1;-1;-1;-1;-1,lv:1;0;0ÿrw,0", balance, !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? this._defaultLine : _dicUserBetInfos[strGlobalUserID].PlayLine, !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? this._defaultBetPerLine : (_dicUserBetInfos[strGlobalUserID].PlayBet / _dicUserBetInfos[strGlobalUserID].PlayLine), !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? Array.IndexOf(_supportLines, this._defaultLine) : Array.IndexOf(_supportLines, _dicUserBetInfos[strGlobalUserID].PlayLine));
        }

        protected override void onDoInit(string strGlobalUserID, GITMessage message, double balance, Currencies currency)
        {
            try
            {
                GITMessage resMessage = new GITMessage((ushort)SCMSG_CODE.SC_GREENTUBE_DOINIT);
                resMessage.Append("%t0ÿq0");
                resMessage.Append(VersionCheckString);
                foreach (string currencyName in SupportCurrencyList)
                {
                    resMessage.Append(currencyName);
                }
                resMessage.Append(buildInitString(strGlobalUserID, balance, currency));
                resMessage.Append("\vGAMEVARIATIONÿ665ÿTICKETSÿ1");
                resMessage.Append("$20ÿ5000ÿgrandÿ21.9261057ÿmajorÿ4.0185388");
                resMessage.Append(GameUniqueString);

                resMessage.Append("%t0ÿq0");
                resMessage.Append($"\aNATIVEJACKPOTCURRENCYFACTORÿ100.0ÿMAXBUYINTOTALÿ0ÿNEEDSSESSIONTIMEOUTÿ0ÿRELIABILITYÿ0ÿNICKNAMEÿ155258EURÿIDÿ155258ÿISDEEPWALLETÿ0ÿCURRENCYFACTORÿ100.0ÿMINBUYINÿ1ÿSESSIONTIMEOUTMINUTESÿ60ÿJACKPOT_PROGRESSIVE_CAPÿ0.0ÿNATIVEJACKPOTCURRENCYÿ{getCurrencyCode(currency)}ÿEXTUSERIDÿDummyDB_ExternalUserId_155258EURÿFREESPINSISCAPREACHEDÿ0ÿCURRENCYÿ{getCurrencySymbol(currency)}ÿTICKETSÿ0ÿJACKPOT_TOTAL_CAPÿ0.0ÿJACKPOTFEEPERCENTAGEÿ0.0ÿISSHOWJACKPOTCONTRIBUTIONÿ0");
                resMessage.Append(buildLineBetString(strGlobalUserID, balance));
                resMessage.Append("$20ÿ5000ÿgrandÿ21.9261057ÿmajorÿ4.0185388");

                ToUserMessage toUserMessage = new ToUserMessage((int)_gameID, resMessage);

                Sender.Tell(toUserMessage, Self);
            }
            catch (Exception ex)
            {
                _logger.Error("Exception has been occurred in BaseGreentubeSlotGame::onDoInit GameID: {0}, {1}", _gameID, ex);
            }
        }
        protected override void onBalanceConfirm(string strGlobalUserID, GITMessage message, double balance, Currencies currency)
        {
            try
            {
                GITMessage resMessage = new GITMessage((ushort)SCMSG_CODE.SC_GREENTUBE_BALANCECONFIRM);
                resMessage.Append("%t0ÿq0");
                resMessage.Append($"\aNATIVEJACKPOTCURRENCYFACTORÿ100.0ÿMAXBUYINTOTALÿ0ÿNEEDSSESSIONTIMEOUTÿ0ÿRELIABILITYÿ0ÿNICKNAMEÿ155258EURÿIDÿ155258ÿISDEEPWALLETÿ0ÿCURRENCYFACTORÿ100.0ÿMINBUYINÿ1ÿSESSIONTIMEOUTMINUTESÿ60ÿJACKPOT_PROGRESSIVE_CAPÿ0.0ÿNATIVEJACKPOTCURRENCYÿ{getCurrencyCode(currency)}ÿEXTUSERIDÿDummyDB_ExternalUserId_155258EURÿFREESPINSISCAPREACHEDÿ0ÿCURRENCYÿ{getCurrencySymbol(currency)}ÿTICKETSÿ0ÿJACKPOT_TOTAL_CAPÿ0.0ÿJACKPOTFEEPERCENTAGEÿ0.0ÿISSHOWJACKPOTCONTRIBUTIONÿ0");
                resMessage.Append(buildLineBetString(strGlobalUserID, balance));
                ToUserMessage toUserMessage = new ToUserMessage((int)_gameID, resMessage);

                Sender.Tell(toUserMessage, Self);
            }
            catch (Exception ex)
            {
                _logger.Error("Exception has been occurred in BaseGreenSlotGame::onDoInit GameID: {0}, {1}", _gameID, ex);
            }
        }
    }
}
