using GITProtocol;
using SlotGamesNode.GameLogics.BaseClasses;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SlotGamesNode.GameLogics
{
    internal class FeelinFruityWinWaysGameLogic : BaseGreenSlotGame
    {
        #region
        protected override string ScatterSymbol
        {
            get
            {
                return "X";
            }
        }

        protected override int MinCountToFreespin
        {
            get
            {
                return 4;
            }
        }

        protected override string VersionCheckString
        {
            get
            {
                return "\b0ÿ2.5.16ÿCasino-Lobbymanager-Serverÿ545ÿ1.10.54.0ÿMazooma_Serverÿ13494ÿ1.0.0ÿFeelin' Fruity Win Ways 96% Buy Bonusÿ1.119.0_2025-04-14_123855ÿ1.183.0";
            }
        }

        protected override string GameUniqueString
        {
            get
            {
                return "\u0006S0ÿA1ÿRÿM,10,10000,20,-1,0ÿI00ÿH,0,0,0,0,0,0ÿ:n,Feelin' Fruity Win Ways 96% Buy Bonusÿ:v,7ÿ:l,-----ÿ:r,0,QQQQQQQBBBBBBBKKKKKKKNNNNNNNQQQQQQQNNNNNNNBJJKKJJRAFADBNBRNKKGNBQGQBRKTKKNBDKRQKGTQGKAATBKQTRNRQBNKDKKQAFBJBJNKABBNGFBNBRTBAKAQQKKABFQQKJQANKGNBNNAAJGDNTKNNFNQKQBKKJBTGBKTNKKBKNÿ:r,0,JJJJJJJRRRRRRBAAAAAAAJJJJJJJTTTTTTTJTTGNJTGQRBGKJRATTQAGAKDJAKANBAATAJTJQQDJBJADJTNATNJARTBBQKJGDAGTJANATKAFNAKKGATGTFKTQAAQKQTFQBAATRTKNARKRANTATRRFTGTTJJBJQRAAFKTNAGKTDAAAFJAAÿ:r,0,QTRRTGKKNQFRQKNQQGGGGTNRGGKBGTKGNAAGARKNFGKKDQATNNQJAQRJKQRKKTAGARNQTKQRARGQGTKTKGRKGBKQQBNTBJQATGKNKTGJJKNQNFKTRJQQJJAAGJBRQKKGGAKRGGAGDDRGKTRQKNQGNGRNBQRTNTBBTGKKJAKGRRAFGBTRQÿ:r,0,GDNAGQNNGDGNKTGQGGBDQJGQRJJJDTGFBNGRAQDNATFNADNKGJGADGFGQRTDJFRNQGNQNGNNGKTNDGANNQNRTDNKKNNNKGFQDTKNNQGGNJDRQRQKKTDQQJNNTRNDGNNGNJRNQATNJQNAJGNAQQQJAQGJNNADQQRQJQGJNKAJDBKANRNNQÿ:r,0,DKKNTJGDBJRJGAKGDBFGTJANABBQJRTQNQKBTJGAJBGJKJKGTQNBGQRTJFNBRGTKRJTJTJGGKGBBRKQGAGNBQTRJGNBQGBQGTKJNQTNJDTQGBAFTGBGGBBQDAKGKBNDRJNBNGBFBGNJNGTAJNGNNTKJTBJTFNKTNGNGTBRAJGBKGNBTQGÿ:r,0,GNNJTBFGAQNGJJJGTRKTAJRGFABBKNJATQBTRJNNKAKNQNGKDJQBBRTKJJBQQBKTJBQTTBQAKQNRGKBNJQDRGJTNATJADNQJNTKRJTKNBTTTKKNNJKRNBNBNKTJDBAQJAKGQBKTAKBKNKJTFQATTJJNQQAKTNGJJJTTTBQBJRTJBGTRJQÿ:r,1,GNFBJKNBAGGGGQKRQNRGNGAGBJQGQDKJTKJNFAGBTKKGQQKTGNTTGGGGKQNGKAAKAKGNGJGKQGKGKTTKGNFQGKGKJAKTGGAQAADJGKQKAAQAQQKKGQFKJATAADKQKJBJRAKBQJGJQANTNKNBQFJKKADJTFJAQQAJTATBQDKTTGQKGJKDRÿ:r,1,GABJNBRGNNGABNRQBABQNAKBRGGJJNGJQGFJKAGTRJRGJQTQJAQJQTNDBQRJGJTQJBNTJKGAQRDRRATNRJJRAJNDGAQARJJGRJBJGQRDQRNAGRKBNAJFBKAGAJJJGNTJJFRGQGRTJNGAGBDQBJAANKJDJABQQJQRJKJGQDQGRJAAJJFQRÿ:r,1,DBBGGGGGGGTTTTTTTAAAAAAANFRQTBBBRRRRGNFQQQQNDBRGDQKQKTJJJAAAAJRDBTJNQKKKKJJJJJKRNNQQAFNTGRBNQJFTGRRTTQQQJJJRRRRKKKKNKTBKFQQNTKBDRNQGTTNRFGBAATTTTJJJKNQGBDAKJJJJFTTBRGQQAAAGGJJJJÿ:r,1,AAAAAAQQQQQQQKKKKKKKGGGGGDBDNNTQJKJJJQQQQKKKBRTKGAAAQQBKNNBBTFKRBABQKJTNNNNNNNQBQAAARAKKKFBDBKRRTTTKKKKKAAAABBBBKKKFRBGJJJTTTTTTTDDRGANKJNGARJBTNKKKAAGQJNNATTGGGGAAAKKKQQRBFJGGTÿ:r,1,TGJDRTNTTKTFDGKRNRATDGRBGRTTNTDRAARKQTRADJQBTBRABRQBQQDTTTQTARANABNRANTTBKGAABTNTBRKTQGTAAGQBTQQAGJTQAKTBTRDRKTRBQDGTJFJTDRJBAQTDBKJKTGKNJATBNAGNJQBJNNAQRATFKRGRKKFTGANQJQKQTANTÿ:r,1,KJNAGAKGTKBTQARKTBNAGNJTKABKTBNGJKAFQNRBNTQTBQATGFNJJRANGGGFATJBKRJAJBGTQKJQQRJDDRQDDTNNNKJGKQRANNQKJJBAJTRKJJJTKTGQANKNNDDDDFNQDQNQGARBABAQAQRANKJBRRRATTAJJAQGQTKRKJNBNKBABRQJQÿ:r,2,QTRRTGKKNQFRQKNQQGGGGTNRGGKBGTKGNAAGARKNFGKKDQATNNQJAQRJKQRKKTAGARNQTKQRARGQGTKTKGRKGBKQQBNTBJQATGKNKTGJJKNQNFKTRJQQJJAAGJBRQKKGGAKRGGAGDDRGKTRQKNQGNGRNBQRTNTBBTGKKJAKGRRAFGBTRQÿ:r,2,GNNJTBFGAQNGJJJGTRKTAJNGRABBKNJABQBTRJNNKAKNQNGKDAGJBRTKJJBQQBKTBJQTTTQDKQNRGKBNJQBRGJTNATJAQNQJNTKRDTKNBTTTKKNNJKRNBNBNKTJJBAQJAKDQBKTAKBKNKJTFQATTJJNQQAKTNGJJJTTTBQBRJTBJGTRJQÿ:r,2,JQNNGQJTNKKNBGJNJDKKQNTNRGTQBTBTAJBTNAQKAFQQRJNQFNQGNGQQNKRBAQNQTQJQRNDJNKNRQQTQTTNBANTKGRBRNRRQJTFNNQGKQJKTQQGFTQKGQBQQQKRQTNQNJBBJNNBDKGKNGNRQQDKANQQNQQTNJQQQAQGQTQTRAJRABDQJQÿ:r,2,BAJKAAANDAAJNJDDKAJJRDATADJGJATFBTAAJDTDNQFJTANATDDJJGFQJGTTJGTTRTAATJJAATDDBTQTADDAJAQATARTFAAGAQTGTTAJDJRQDTFDJAAKADKKANQDDTAJFTTGTKFGJRKDTAAAJGTRNAANAGQJTTATDTDKGRJATJJJJKTKGÿ:r,2,AAAAAAABBBBBBBKKKKKKKQQQQQQQNNNNNNNAKFTJRQGBKQRABQQQQQQQFKKKKKKKNNNNNNNRRRAAABNJGGGTTTJJJNJTBNNKRGDDDQJFNNNNNNNAKBQJNATQRKQBANTAJKNTANQTNBKQJAGNBBBBKKKKKRJAGKKKNNNNDGKDTDAJNGKNBÿ:r,2,GGGGGGGKKKKKKKTJNBKGQTRNJKBGQRTJNGGGGGGGKKKKKKKNNNNTTTTTFGGGGAAAJJJQQQRRRBKAQTBJKBQRGGGGGAAAJJTTTNNNNRRRQQQQAAAFBGGGJKKRRRRGAJDFNTBARJQGRTBNARFTTRGJBBGRAQQQJJJTTTRRRNNNBGRADRJQTÿ:r,3,NRNJDQBRGNBRAJTTANNBKNGAJNBNBBNNKNKAGBJKJKQGDJTRQAAJTAJGTNJJBBGBBKNABGQJTKADGKNBNBGNQBTJAQRNJQANKTAJQBRNTNBJANDAGBTBTKJQDGKNJNRAATKTNNTTDKBNKBNANRKTTRDQKRKGBANKTGQNBABNGGJTGJQTJÿ:r,3,KTQJJQAJAKATKGKJRGQRRRRJKBBNTJAJJATGBQBKTNTNGKKGKKNJQRJJRQKAQRQJJQGRJGAQBRRNQQAJJTKTNRRBQTRGGTKGNJBJGRQQGNTNBNJKRRNRGKKJARJKRTQGKJRRJJJBKBNGAQNGGNRANKKNNBKGNJRGNRRTJKTRNQJGRRDGBÿ:r,3,BBBBBBBRRRRRRRDQQQQQQQKKKKKKKDJJJJJJJRRRRRRRDTTTTTTTAAAAAAAGGGGGGGDNNNNNNNDBBBBBBBDKKKKKKKDQQQQQQNNNNNNNDGGGGGGGDKKKKKKKTTTTTTDAAAAAAAJJJJJJDQQQQQQQDTTTTTTTDJJJJJJJDAAAAAANNNNNNÿ:r,3,GGGGGGGBBBBBBBKKKKKKKQQQQQQQDDBBBBBDDTTTTTTTNNNNNNNRRRRRRRGGGGGGGAAAAAAANNNNNNNDDQQQQQQQRRRRRRRJJJJJJJAAAAAAANNNNNNNQQQQQQQGGGGGGGDDTTTTTDDJJJJJJJKKKKKKRRRRRRBBDDTTTTTTTTJJJJJJJÿ:r,3,ADTDTNDTBDNQBGBRARTBABKQQBRTRABKQRGQRJBQTRBTTRTBADDQQBDJQTTBARQTBRDDDTTKNAARBQKQGBBBBQKJTTTQATNQQRTQGNDQTAABRTRQGKAQRAGNNQQBQNQJBQRTARAQKRTDDQNDQTDQTNGDDNAQTQNTJABTQBRQTNRQTKDAAÿ:r,3,RNTQGBNARDBTAKDTKRADTTADKDBQNQJRKTNJTTAJDDRADKTBDKNRGQNJAGKQJRQQTDQQJADDGNRDNDTJJBAKGJQGTGDDGTQBKJAQNAJDJBKJQQQGQNJNNGNRJRJBJNGQDNQDQAGBAQGGTKJNQTDJGRKKNNBJGJJBJAGQRJQRJRGGDNRTDÿ:r,4,AKNBQAJAQNKANBANAANJBQTQQGDKBABNQTBRGAQNRAQJNNQABNJKNQAQQQNBBQBJQAANNQTGNBBNNNATQKQAANBGBAAAAGJNNRATBNBJTNTBANBBRBQQGAQNNJQKABBATBNBJNTNBQAABAQNRTAQNAKJAQRAQKAGAGABQJDNRJGBNAÿ:r,4,NANTANAQGQQNAGRABQQANDABJNKBAQQBKQTDNRTBJNQQAKRNAQQGAKAAKQNGNJBQAAJARGJTKRAJBQAABQATQNAANGANRNATQABTTAAQQNQATADNJJKANDKNNAJNQQNBGANBNAGNADAQQBQANNAQNNBAJDBJQDJDNNGANBQQBGJÿ:r,4,QTRRTKJJNQRQJNQQKKKKTNRKKJBKTJKNAAKARJNKJJDQATNNQGAQRGJQRJJTAKARNQTJQRARKQKTJTJKRJKBJQQBNTBGQATKJNJTKGGJNQNJTRGQQGGAAKGBRQJJKKAJRKKAKDDRKJTRQJNQKNKRNBQRTNTBBTKJJGAJKRRAKBTRQÿ:r,4,KDNAKQNNKDKNJTKQKKBDQGKQRGGGDTKBNKRAQDNATNADNJKGKADKKQRTDGRNQKNQNKNNKJTNDKANNQNRTDNJJNNNJKQDTJNNQKKNGDRQRQJJTDQQGNNTRNDKNNKNGRNQATNGQNAGKNAQQQGAQKGNNADQQRQGQKGNJAGDBJANRNNQÿ:r,4,DAANTGKDBGRGKJAKDBGKTGJNJBBQGRTQNQABTGKJGBKGAGAKTQNBKQRTGNBRKTARGTGTGKKAKBBRAQKJKNBQTRGKNBQKBQKTAGNQTNGDTQKBJTKBKKBBQDJAKABNDRGNBNKBBKNGNKTJGNKNNTAGTBGTGNATNKNKTBRJGKBAKNBTQKÿ:r,4,KNNGTBKAQNKGGGKTRJTAGRKABBJNGATQBTRGNNJAJNQNKJDGQBBRTJGGBQQBJTGBQTTBQAJQNRKJBNGQDRKGTNATGADNQGNTJRGTJNBTTTJJNNGJRNBNBNJTGDBAQGAJKQBJTAJBJNJGTQATTGGNQQAJTNKGGGTTTBQBGRTGBKTRGQÿ:r,5,JGJBQKARJBKKTQJTKDNJAKTJKAKKJNAGKGQKJAKJNQAQANDQJGJGGGAKKJKKNQNQBJGTGJKQRTQQJKBJGABGGKDNTTNDJATGRJANNKTQJQKKNQTTJTJJTQAKJTAQKJJAAKTNKBGBJAJQKJAKNAQQKKJNAJJGKQQJKKQJANRKJKKQAAKGÿ:r,5,QAJNKADQQJKJGANABATAJNKKQDGKQJBKTGARTNQKKKQDTANJAQGDRJJKQKKJATTBNBNAJNDDGKTJGAKTRJNGKKQQQTQNAGAJTQKKKKQKJBKGQJDGAKJBKTABKNARNJGAJGGAKBKQKKJADKJJGAJKNNQKQQJGDJJDTKKJJTGNTKKQJÿ:r,5,DBBKKKKKKKTTTTTTTAAAAAAANRQTBBBRRRRKNQQQQNDBRKDQJQJTGGGAAAAGRDBTGNQJJJJGGGGGJRNNQQANTKRBNQGTKRRTTQQQGGGRRRRJJJJNJTBJQQNTJBDRNQKTTNRKBAATTTTGGGJNQKBDAJGGGGTTBRKQQAAAKKGGGGÿ:r,5,AAAAAAQQQQQQQJJJJJJJKKKKKDBDNNTQGJGGGQQQQJJJBRTJKAAAQQBJNNBBTJJRBABQJGTNNNNNNNQBQAAARAJJJBDBJRRTTTJJJJJAAAABBBBJJJJRBKGGGTTTTTTTDDRKANJGNKARGBTNJJJAAKQGNNATTKKKKAAAJJJQQRBJGKKTÿ:r,5,GKTDRGNGGJGDKJRNRAGDKRBKRGGNGDRAARJQGRADTQBGBRABRQBQQDGGGQGARANABNRANGGBJKAABGNGBRJGQKGAAKQBGQQAKTGQAJGBGRDRJGRBQDKGTTGDRTBAQGDBJTJGKJNTAGBNAKNTQBTNNAQRAGJRKRJJGKANQTQJQGANGÿ:r,5,JGNAKAJKTJBTQARJTBNAKNGTJABJTBNKGJAQNRBNTQTBQATKNGGRANKKKATGBJRGAGBKTQJGQQRGDDRQDDTNNNJGKJQRANNQJGGBAGTRJGGGTJTKQANJNNDDDDNQDQNQKARBABAQAQRANJGBRRRATTAGGAQKQTJRJGNBNJBABRQGQÿ:r,6,QTRRTGKKNQRQKNQQGGGGTNRGGKBGTKGNAAGARKNGKKDQATNNQJAQRJKQRKKTAGARNQTKQRARGQGTKTKGRKGBKQQBNTBJQATGKNKTGJJKNQNKTRJQQJJAAGJBRQKKGGAKRGGAGDDRGKTRQKNQGNGRNBQRTNTBBTGKKJAKGRRAGBTRQÿ:r,6,GNNJTBGAQNGJJJGTRKTAJNGRABBKNJABQBTRJNNKAKNQNGKDAGJBRTKJJBQQBKTBJQTTTQDKQNRGKBNJQBRGJTNATJAQNQJNTKRDTKNBTTTKKNNJKRNBNBNKTJJBAQJAKDQBKTAKBKNKJTQATTJJNQQAKTNGJJJTTTBQBRJTBJGTRJQÿ:r,6,JQNNGQJTNKKNBGJNJDKKQNTNRGTQBTBTAJBTNAQKAQQRJNQNQGNGQQNKRBAQNQTQJQRNDJNKNRQQTQTTNBANTKGRBRNRRQJTNNQGKQJKTQQGTQKGQBQQQKRQTNQNJBBJNNBDKGKNGNRQQDKANQQNQQTNJQQQAQGQTQTRAJRABDQJQÿ:r,6,BAJKAAANDAAJNJDDKAJJRDATADJGJATBTAAJDTDNQJTANATDDJJGQJGTTJGTTRTAATJJAATDDBTQTADDAJAQATARTAAGAQTGTTAJDJRQDTDJAAKADKKANQDDTAJTTGTKGJRKDTAAAJGTRNAANAGQJTTATDTDKGRJATJJJJKTKGÿ:r,6,AAAAAAABBBBBBBKKKKKKKQQQQQQQNNNNNNNAKTJRQGBKQRABQQQQQQQKKKKKKKNNNNNNNRRRAAABNJGGGTTTJJJNJTBNNKRGDDDQJNNNNNNNAKBQJNATQRKQBANTAJKNTANQTNBKQJAGNBBBBKKKKKRJAGKKKNNNNDGKDTDAJNGKNBÿ:r,6,GGGGGGGKKKKKKKTJNBKGQTRNJKBGQRTJNGGGGGGGKKKKKKKNNNNTTTTTGGGGAAAJJJQQQRRRBKAQTBJKBQRGGGGGAAAJJTTTNNNNRRRQQQQAAABGGGJKKRRRRGAJDNTBARJQGRTBNARTTRGJBBGRAQQQJJJTTTRRRNNNBGRADRJQTÿ:r,7,QTRRTGKKQRQKQQGGGGTRGGKGTKGGRKGKKQTQQRKQRKKTGRQTKQRRGQGTKTKGRKGKQQTQTGKKTGKQKTRQQGRQKKGGKRGGGRGKTRQKQGGRQRTTTGKKKGRRGTRQÿ:r,7,NNJBANJJJAJNABBNJABBJNNANNDAJBJJBBBJDNBNJBJNAJANJNDNBNNJNBNBNJJBAJADBABNJAJJNANJJJBBJBJJÿ:r,7,JQNNGQJTNKKNBGJNJDKKQNTNRGTQBTBTAJBTNAQKAQQRJNQNQGNGQQNKRBAQNQTQJQRNDJNKNRQQTQTTNBANTKGRBRNRRQJTNNQGKQJKTQQGTQKGQBQQQKRQTNQNJBBJNNBDKGKNGNRQQDKANQQNQQTNJQQQAQGQTQTRAJRABDQJQÿ:r,7,BAJKAAANDAAJNJDDKAJJRDATADJGJATBTAAJDTDNQJTANATDDJJGQJGTTJGTTRTAATJJAATDDBTQTADDAJAQATARTAAGAQTGTTAJDJRQDTDJAAKADKKANQDDTAJTTGTKGJRKDTAAAJGTRNAANAGQJTTATDTDKGRJATJJJJKTKGÿ:r,7,AAAAAAABBBBBBBKKKKKKKQQQQQQQNNNNNNNAKTJRQGBKQRABQQQQQQQKKKKKKKNNNNNNNRRRAAABNJGGGTTTJJJNJTBNNKRGDDDQJNNNNNNNAKBQJNATQRKQBANTAJKNTANQTNBKQJAGNBBBBKKKKKRJAGKKKNNNNDGKDTDAJNGKNBÿ:r,7,GGGGGGGKKKKKKKTJNBKGQTRNJKBGQRTJNGGGGGGGKKKKKKKNNNNTTTTTGGGGAAAJJJQQQRRRBKAQTBJKBQRGGGGGAAAJJTTTNNNNRRRQQQQAAABGGGJKKRRRRGAJDNTBARJQGRTBNARTTRGJBBGRAQQQJJJTTTRRRNNNBGRADRJQTÿ:r,8,JNTNJTKWNTKGJTKJWTJQNQTAQTQKJTKJDKTDKJNKAJQANQTAWNRATJTRANQAJNAJAGQNAQGJGTBNTBKTBDKNDRJWNQNRDJBTDNJWÿ:r,8,JNTNJTKWNTKGJTKJWTJQNQTAQTQKJTKJDKTDKJNKAJQANQTAWNRATJTRANQAJNAJAGQNAQGJGTBNTBKTBDKNDRJWNQNRDJBTDNJWÿ:r,8,JNTNJTKWNTKGJTKJWTJQNQTAQTQKJTKJDKTDKJNKAJQANQTAWNRATJTRANQAJNAJAGQNAQGJGTBNTBKTBDKNDRJWNQNRDJBTDNJWÿ:r,8,JNTNJTKWNTKGJTKJWTJQNQTAQTQKJTKJDKTDKJNKAJQANQTAWNRATJTRANQAJNAJAGQNAQGJGTBNTBKTBDKNDRJWNQNRDJBTDNJWÿ:r,8,JNTNJTKWNTKGJTKJWTJQNQTAQTQKJTKJDKTDKJNKAJQANQTAWNRATJTRANQAJNAJAGQNAQGJGTBNTBKTBDKNDRJWNQNRDJBTDNJWÿ:r,8,JNTNJTKWNTKGJTKJWTJQNQTAQTQKJTKJDKTDKJNKAJQANQTAWNRATJTRANQAJNAJAGQNAQGJGTBNTBKTBDKNDRJWNQNRDJBTDNJWÿ:r,9,NBTJAWRQKQAKFQWABJGWJGJGBFTWBTBTBWRNFWBTBTBWGBTRTRNFWKRQRWNRFBTDWKRNTFRNRBRNRDNDWFGRQARDFNWJFNADKWRFÿ:r,9,NBTJAWRQKQAKFQWABJGWJGJGBFTWBTBTBWRNFWBTBTBWGBTRTRNFWKRQRWNRFBTDWKRNTFRNRBRNRDNDWFGRQARDFNWJFNADKWRFÿ:r,9,NBTJAWRQKQAKFQWABJGWJGJGBFTWBTBTBWRNFWBTBTBWGBTRTRNFWKRQRWNRFBTDWKRNTFRNRBRNRDNDWFGRQARDFNWJFNADKWRFÿ:r,9,NBTJAWRQKQAKFQWABJGWJGJGBFTWBTBTBWRNFWBTBTBWGBTRTRNFWKRQRWNRFBTDWKRNTFRNRBRNRDNDWFGRQARDFNWJFNADKWRFÿ:r,9,NBTJAWRQKQAKFQWABJGWJGJGBFTWBTBTBWRNFWBTBTBWGBTRTRNFWKRQRWNRFBTDWKRNTFRNRBRNRDNDWFGRQARDFNWJFNADKWRFÿ:r,9,NBTJAWRQKQAKFQWABJGWJGJGBFTWBTBTBWRNFWBTBTBWGBTRTRNFWKRQRWNRFBTDWKRNTFRNRBRNRDNDWFGRQARDFNWJFNADKWRFÿ:r,10,FQTRRTGKFKQRQKQQFGGGGTRGFGKGTKGGFRKGKKQTFQQRKQRKFKTGRQTKFQRRGQGTFKTKGRKGFKQQTQTGFKTGKQKTFRQQGRQKFKGGKRGGFGRGKTRQÿ:r,10,FNNNJBAFNJJJAJFNABBNJFABBJNNFANNDAJFBJJBBBFJDNBNJFBJNAJAFNJNDNBFNNJNBNFBNJJBAFADBABNFJAJJNAFNJJJBBFJBJJBJFBJJAJJÿ:r,10,FJQNNGQFJTNKKNFBGJNJDFKKQNTNFRGTQBTFBTAJBTFNAQKAQFQRJNQNFQGNGQQFNKRBAQFNQTQJQFNDJNKNFRQQTQTFTNBANTFKGRBRNFRRQJTNÿ:r,10,FBAJKAAFANDAAJFNJDDKAFJJRDATFADJGJAFTBTAAJFDTDNQJFTANATDFDJJGQJFGTTJGTFTRTAATFJAATDDFBTQTADFDAJAQAFTARTAAFGAQTGTÿ:r,10,FRRRAAAFBNJGGGFTTTJJJFNJTBNNFKRGDDDFQJAKBQFJNATQRFKQBANTFAJKNTAFNQTNBKFQJAGNBFBBKKKKFKRJAGKFKKNNNNFDGKDTDFAJNGKNÿ:r,10,FTJNBKGQFTRNJKBGFQRTJNBKFAQTBJKBFQRAAAJJFAAABGGGFJKKRRRRFGAJDNTBFARJQGRTFBNARTTRFJBBGRAQFQQJJJTTFTRRRNNNFBGRADRJÿ:j,W,1,0,NTJQKAGBRDÿ:j,5,1,0,Fÿ:u,APPPP.PP.PP.PPPPÿ:w,W,6,1000,0ÿ:w,W,5,500,0ÿ:w,W,4,200,0ÿ:w,W,3,100,0ÿ:w,W,2,40,0ÿ:w,D,6,1000,0ÿ:w,D,5,500,0ÿ:w,D,4,200,0ÿ:w,D,3,100,0ÿ:w,D,2,40,0ÿ:w,R,6,150,0ÿ:w,R,5,50,0ÿ:w,R,4,40,0ÿ:w,R,3,20,0ÿ:w,B,6,40,0ÿ:w,B,5,30,0ÿ:w,B,4,20,0ÿ:w,B,3,5,0ÿ:w,G,6,40,0ÿ:w,G,5,15,0ÿ:w,G,4,10,0ÿ:w,G,3,5,0ÿ:w,A,6,35,0ÿ:w,A,5,12,0ÿ:w,A,4,8,0ÿ:w,A,3,4,0ÿ:w,K,6,35,0ÿ:w,K,5,12,0ÿ:w,K,4,8,0ÿ:w,K,3,4,0ÿ:w,Q,6,20,0ÿ:w,Q,5,12,0ÿ:w,Q,4,5,0ÿ:w,Q,3,4,0ÿ:w,J,6,20,0ÿ:w,J,5,10,0ÿ:w,J,4,5,0ÿ:w,J,3,3,0ÿ:w,T,6,18,0ÿ:w,T,5,10,0ÿ:w,T,4,5,0ÿ:w,T,3,3,0ÿ:w,N,6,16,0ÿ:w,N,5,8,0ÿ:w,N,4,4,0ÿ:w,N,3,2,0ÿ:w,#,1,-1,0ÿ:wa,W,6,1000,0,0,0,0:1,-1,0ÿ:wa,W,5,500,0,0,0,0:1,-1,0ÿ:wa,W,4,200,0,0,0,0:1,-1,0ÿ:wa,W,3,100,0,0,0,0:1,-1,0ÿ:wa,W,2,40,0,0,0,0:1,-1,0ÿ:wa,D,6,1000,0,0,0,0:1,-1,0ÿ:wa,D,5,500,0,0,0,0:1,-1,0ÿ:wa,D,4,200,0,0,0,0:1,-1,0ÿ:wa,D,3,100,0,0,0,0:1,-1,0ÿ:wa,D,2,40,0,0,0,0:1,-1,0ÿ:wa,R,6,150,0,0,0,0:1,-1,0ÿ:wa,R,5,50,0,0,0,0:1,-1,0ÿ:wa,R,4,40,0,0,0,0:1,-1,0ÿ:wa,R,3,20,0,0,0,0:1,-1,0ÿ:wa,B,6,40,0,0,0,0:1,-1,0ÿ:wa,B,5,30,0,0,0,0:1,-1,0ÿ:wa,B,4,20,0,0,0,0:1,-1,0ÿ:wa,B,3,5,0,0,0,0:1,-1,0ÿ:wa,G,6,40,0,0,0,0:1,-1,0ÿ:wa,G,5,15,0,0,0,0:1,-1,0ÿ:wa,G,4,10,0,0,0,0:1,-1,0ÿ:wa,G,3,5,0,0,0,0:1,-1,0ÿ:wa,A,6,35,0,0,0,0:1,-1,0ÿ:wa,A,5,12,0,0,0,0:1,-1,0ÿ:wa,A,4,8,0,0,0,0:1,-1,0ÿ:wa,A,3,4,0,0,0,0:1,-1,0ÿ:wa,K,6,35,0,0,0,0:1,-1,0ÿ:wa,K,5,12,0,0,0,0:1,-1,0ÿ:wa,K,4,8,0,0,0,0:1,-1,0ÿ:wa,K,3,4,0,0,0,0:1,-1,0ÿ:wa,Q,6,20,0,0,0,0:1,-1,0ÿ:wa,Q,5,12,0,0,0,0:1,-1,0ÿ:wa,Q,4,5,0,0,0,0:1,-1,0ÿ:wa,Q,3,4,0,0,0,0:1,-1,0ÿ:wa,J,6,20,0,0,0,0:1,-1,0ÿ:wa,J,5,10,0,0,0,0:1,-1,0ÿ:wa,J,4,5,0,0,0,0:1,-1,0ÿ:wa,J,3,3,0,0,0,0:1,-1,0ÿ:wa,T,6,18,0,0,0,0:1,-1,0ÿ:wa,T,5,10,0,0,0,0:1,-1,0ÿ:wa,T,4,5,0,0,0,0:1,-1,0ÿ:wa,T,3,3,0,0,0,0:1,-1,0ÿ:wa,N,6,16,0,0,0,0:1,-1,0ÿ:wa,N,5,8,0,0,0,0:1,-1,0ÿ:wa,N,4,4,0,0,0,0:1,-1,0ÿ:wa,N,3,2,0,0,0,0:1,-1,0ÿ:wa,#,1,-1,0,0,0,0:1,-1,0ÿ:s,0ÿ:i,1ÿ:i,1ÿ:m,2000,20ÿ:a,0,0ÿ:g,999,1000,-1,false,0,falseÿ:es,0,0ÿ:mbnr,0.0ÿ:fs,0,0,0,0,0,0ÿbs,0,1,0ÿ:k,nullÿe,20,0,1,-1ÿb,0,0,0ÿs,1ÿr,0,6,76,10,127,116,95,42ÿx,5,WINDOWS:KRQ----|RR----|GG----|QJNN--|GTK---|KNQ----|JKQJ,REELCOUNT:3|2|2|4|3|3,WAYS:3|9|27|135|540|1620,TOPREELSET:8,rnd_0_76_10_127_116_95_42_174_161_187_673_576_320_44_59_52_34ÿrw,0";
            }
        }
        #endregion

        public FeelinFruityWinWaysGameLogic()
        {
            _gameID = GAMEID.FeelinFruityWinWays;
            GameName = "FeelinFruityWinWays";
        }
        
        protected override string buildLineBetString(string strGlobalUserID, double balance)
        {
            return string.Format("\u0006S{0}ÿA0ÿC,100.0,,1,ÿT,0,0,0ÿRÿM,20,200000,20,-1,0ÿI00ÿH,0,0,0,0,0,0ÿY,7200,10ÿ:i,1ÿ:i,1ÿ:m,2000,20ÿ:b,14,1,2,3,4,5,8,10,15,20,30,40,50,80,100ÿ:a,0,0ÿ:g,999,1000,-1,false,0,falseÿ:es,0,0ÿ:mbnr,20.0ÿbs,0,1,0ÿ:k,nullÿe,{1},{2},{3},1,-1ÿb,1000,1000,0ÿs,1ÿr,0,6,76,10,127,116,95,42ÿx,5,WINDOWS:KRQ----|RR----|GG----|QJNN--|GTK---|KNQ----|JKQJ,REELCOUNT:3|2|2|4|3|3,WAYS:3|9|27|135|540|1620,TOPREELSET:8,rnd_0_76_10_127_116_95_42_174_161_187_673_576_320_44_59_52_34ÿrw,0", balance, !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? this._defaultLine : _dicUserBetInfos[strGlobalUserID].PlayLine, !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? this._defaultBetPerLine : (_dicUserBetInfos[strGlobalUserID].PlayBet / _dicUserBetInfos[strGlobalUserID].PlayLine), !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? Array.IndexOf(_supportLines, this._defaultLine) : Array.IndexOf(_supportLines, _dicUserBetInfos[strGlobalUserID].PlayLine));
        }

        protected override void onDoInit(string strGlobalUserID, GITMessage message, double balance, Currencies currency)
        {
            try
            {
                GITMessage resMessage = new GITMessage((ushort)SCMSG_CODE.SC_GREENTUBE_DOINIT);
                resMessage.Append("%t0ÿq0");
                resMessage.Append(VersionCheckString);
                foreach (string currencyName in SupportCurrencyList)
                {
                    resMessage.Append(currencyName);
                }
                resMessage.Append(buildInitString(strGlobalUserID, balance, currency));
                resMessage.Append("\vGAMEVARIATIONÿ665ÿTICKETSÿ1");

                resMessage.Append(GameUniqueString);
                
                resMessage.Append("%t0ÿq0");
                resMessage.Append($"\aNATIVEJACKPOTCURRENCYFACTORÿ100.0ÿMAXBUYINTOTALÿ0ÿNEEDSSESSIONTIMEOUTÿ0ÿRELIABILITYÿ0ÿNICKNAMEÿ155258EURÿIDÿ155258ÿISDEEPWALLETÿ0ÿCURRENCYFACTORÿ100.0ÿMINBUYINÿ1ÿSESSIONTIMEOUTMINUTESÿ60ÿJACKPOT_PROGRESSIVE_CAPÿ0.0ÿNATIVEJACKPOTCURRENCYÿ{getCurrencyCode(currency)}ÿEXTUSERIDÿDummyDB_ExternalUserId_155258EURÿFREESPINSISCAPREACHEDÿ0ÿCURRENCYÿ{getCurrencySymbol(currency)}ÿTICKETSÿ0ÿJACKPOT_TOTAL_CAPÿ0.0ÿJACKPOTFEEPERCENTAGEÿ0.0ÿISSHOWJACKPOTCONTRIBUTIONÿ0");
                resMessage.Append(buildLineBetString(strGlobalUserID, balance));

                ToUserMessage toUserMessage = new ToUserMessage((int)_gameID, resMessage);

                Sender.Tell(toUserMessage, Self);
            }
            catch (Exception ex)
            {
                _logger.Error("Exception has been occurred in BaseGreentubeSlotGame::onDoInit GameID: {0}, {1}", _gameID, ex);
            }
        }
        protected override void onBalanceConfirm(string strGlobalUserID, GITMessage message, double balance, Currencies currency)
        {
            try
            {
                GITMessage resMessage = new GITMessage((ushort)SCMSG_CODE.SC_GREENTUBE_BALANCECONFIRM);
                resMessage.Append("%t0ÿq0");
                resMessage.Append($"\aNATIVEJACKPOTCURRENCYFACTORÿ100.0ÿMAXBUYINTOTALÿ0ÿNEEDSSESSIONTIMEOUTÿ0ÿRELIABILITYÿ0ÿNICKNAMEÿ155258EURÿIDÿ155258ÿISDEEPWALLETÿ0ÿCURRENCYFACTORÿ100.0ÿMINBUYINÿ1ÿSESSIONTIMEOUTMINUTESÿ60ÿJACKPOT_PROGRESSIVE_CAPÿ0.0ÿNATIVEJACKPOTCURRENCYÿ{getCurrencyCode(currency)}ÿEXTUSERIDÿDummyDB_ExternalUserId_155258EURÿFREESPINSISCAPREACHEDÿ0ÿCURRENCYÿ{getCurrencySymbol(currency)}ÿTICKETSÿ0ÿJACKPOT_TOTAL_CAPÿ0.0ÿJACKPOTFEEPERCENTAGEÿ0.0ÿISSHOWJACKPOTCONTRIBUTIONÿ0");
                resMessage.Append(buildLineBetString(strGlobalUserID, balance));
                ToUserMessage toUserMessage = new ToUserMessage((int)_gameID, resMessage);

                Sender.Tell(toUserMessage, Self);
            }
            catch (Exception ex)
            {
                _logger.Error("Exception has been occurred in BaseGreentubeSlotGame::onDoInit GameID: {0}, {1}", _gameID, ex);
            }
        }
    }
}
