using GITProtocol;
using SlotGamesNode.GameLogics.BaseClasses;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SlotGamesNode.GameLogics
{
    internal class PrizeOfTheNileGameLogic : BaseGreenSlotGame
    {
        #region
        protected override string ScatterSymbol {
            get
            {
                return "F";
            }
        }

        protected override int MinCountToFreespin
        {
            get
            {
                return 3;
            }
        }

        protected override string VersionCheckString
        {
            get
            {
                return "\b0ÿ2.5.16ÿCasino-Lobbymanager-Serverÿ898ÿ1.10.54.0ÿGTSKSlotServerÿ11061ÿ1.2.1ÿPrize of the Nile 95%ÿ1.120.0_2025-05-09_075230ÿ1.313.0";
            }
        }

        protected override string GameUniqueString
        {
            get
            {
                return "\u0006S0ÿA1ÿRÿM,10,10000,30,-1,0ÿI00ÿH,0,0,0,0,0,0ÿ:n,Prize of the Nile 95%ÿ:v,3ÿ:l,-----ÿ:l,^^^^^ÿ:l,_____ÿ:l,^-_-^ÿ:l,_-^-_ÿ:l,-___-ÿ:l,-^^^-ÿ:l,__-^^ÿ:l,^^-__ÿ:l,_---^ÿ:l,^---_ÿ:l,-_-^-ÿ:l,-^-_-ÿ:l,^-^-^ÿ:l,_-_-_ÿ:l,--^--ÿ:l,--_--ÿ:l,^_^_^ÿ:l,_^_^_ÿ:l,_^-^_ÿ:l,^_-_^ÿ:l,^^_^^ÿ:l,__^__ÿ:l,-^_^-ÿ:l,-_^_-ÿ:l,_^^^_ÿ:l,^___^ÿ:l,^^^^-ÿ:l,----_ÿ:l,____-ÿ:r,0,BRCBDRBCBTCDBCBRWCBCDVCBRBTBCRCVPPBCDBCRBDUBCRPPBRTBVDCBCUCDRCDBCBDCPBVWBCBUCBRTCDBVCDBCWRBCUBRBPCBRCRTBDBCPPDBDBRCBURCVBCBCBPDRBCVBTCDBCBURWCBCDVCBRBTBCRCVPPBCDBCBDUBCRBPPBRBVDCBCUCDRCDBCBDCRPBVWBCBUCBRTCDBVCDCWRBCUBRBPCBRCRVTBDBCPPDCBDRCBURCVBCBCBDRBCBTCDBCBRWCBCDVCBRBTBCRCVPPBCDBCBDUBCRPPBDRBVDCBCUCDRCDBCBDCPBVWBCBUCBRTCDBVCDCWRBCUBRBPCBRCRTBCDBCPPDBDRCBDURCVBCÿ:r,0,BVUCBVDBFRUVBCTRBFCBUDBVFCVDBVBFPPBUBVUDFBUDBUCTBFDUBTUCPDVBWCTVBFRBTUDBVUPPBTRBTBVRFBTBUCRVBUBVFDCBVBCUDPBUCBWVDCFUBVDTBVRBVBUCBVDBFUVBCTRBFCBUDBVFVDBRVBPPBUBVDRFBUDBUCTBFDUBTUCPVRBWCVBFURBTUDBVUPPBTRBTBVCRFBTBUCRBUBVFDTCBVBCUDTPBUCBWVUDCFUBVDTBVRBVBUCBVDBFUVBCTRBFCBUDBVFVDBVBPPBUBVDFBUDBUCTBFDUBTUCPVBDWCVBFRBTUDBVUPPBTRBTBVRFBTBUCRBUBVFDCBVBCUDPBUCBWVDCFUBVDTBVRBVÿ:r,0,CDCRCFDRCWTPPCVDRCRFCRCDBRCDVCDFCRUCBCDCDFCUCDRDCRCFRCDVUDCPPDRBCDVFDTCDUPCDCVCRCDCDUCDCFDRCDCVCPPCDCTCRUCDCDCPVCRCFDBRCDCVRCFDRCWTPPCDRCRFCRCDBRCDVCDFCRUCBCDCDFCUCDRDCRCFRCDVDCPPDRBCDVFDTCDUDPCDCVCRCDCDUCDCFDRCDCVCBPPCDCFTCRUCDCDCPVCRCFDBRCDCRUCFDRCWTPPCDRCRFCRCDBRCDVCDFCRUCBCDCDFCVUCDRDCRCFRCDVDCPPDRBCDVFDTCDUPCDCVCRCDCDUCDCFDRCDUCVCPPCDCTCRUCDCDCPVCRCFDBRÿ:r,0,CBDVFCBDPPBTBVFBCDVBDVCTUWDBVFCBDUBCDBVCBDVDFTDBVCDVWURBUDFTRDCVBVPPUTBCVRCBVBRUCRFBVBDCPBCUBCBVFRVBCVCUBDPUCRWBVCFBCDBVBCDCDCBDUVFCVBDPPBTBVFBCUDVBDVDCTWCDBVFCPBDUBCBVCUBDVDFTBVCDVWURBUDFTRVDCVBVPPTBCVRCUBVBRURFBVBDCPBCUBRCBVTFRBCVCUBDPCRWBUVCFBDBVBCDCDCBDVDFCBDPPDBTBVFBCDVBDVCUTWDBVFCBDUBCBVCBDVUDFTBVCDVWURBUDFTRDCUVBVPPTBCVRCBVBVRURFBVBDCPBCUBCBVFTRBCVCUBDBPCRWBVCFBDBVBCDCDÿ:r,0,BCBDVCBUDWBRBCDBTCVDBCBCRCBCTWRCBDVCUBPPTRBCBDBCVBUCRBDVBPPBVCDBTCBUCVDTBCRBCVBTBUDCBCTBCWBCBCVCBPPDURCBCBDTRVBPBDBVCDCBCVBRBCBDVCBUDWBTRBCDBCVDBCBCRCBCTWRCBVCUBPPTRBCBDBCVBUCRBTDVBPPBVCTDBCBUCVDBCRDBCVBTBPUDCBCRTBCWBCBCVCPPTDURCDBCBTRVBPBDBVCDCBVBRBCBDVPPCBUDWBRBCDTBCVDBCBPCRCBCTWRCBVCUBPPTDRBCBDBCVBUCRBDVBCPPBVCDBCBUCVDBCRBCVPBTBUDCBCTBCWBCBCVCPPDVURCBCBTRVBPBDTBVCDCBVBRÿ:r,1,BCBDRBCBTCDBCBRWCBCDVCBDRBTBCRCVPPBCDBCBDUBCRPPBWRBVDCBCUCDRCDBCBDCPBVWBCBUCBRTCDBVCDCWRBCUBCRBPCBRCRTBDBCPPDBDRCBURWVBCBCBDRBCPBTCDBRCBRWCBCDUVCBRBTBCRCVPPBCDBCBCDUBCRPPBRDBVDCBCDUCDRCDBCBDCPBVWBCRBUCBRTCDBDVCDCWRBCUBRBPCBRCRTRBDBCPPDBDRCBUDRWVBCBCBDRBCBTUCDBCBRWCBCDVCUBRBTBCRCVPPBCDBCBDUBCRPPBRBVDCBCUCBDRCDBCBDCPBVWBCBUCBRTCDBVCDRCWRBCUBRBPCBRCRTBCDBCPPDBDRCBURWVBCÿ:r,1,BUCBVDBFUVBCWRBUFCBUDRBVFVDBWBPPBUBVDFBUDBUCTBFDUBTUCPVTBWCVBFRBTUDBVUDPPBTRUBTBVRFBVTBUCRBUBVFDCBVBCUDPBUCBWVDCFUBVDTBVRBVBUCBVDBFUVDBCWRBFTCBUDBVBFVDBWBPPBUCBVDFBUDBUCTBFDUBTBUCPVBRWCVBDFRBTUDBVUPPCBTRBWTBVRFBTBUCRBUBVFDCBVBCUDPBUCBWVDCFUBVDTBVRBVBUCBVDBFUVBCWRBFCBUDBVFRVDBWBPPBUBVDFRBUDBUCTBFCDUBTUCPVBWCVBFRCBTUDBVBUPPBVTRBTBVRFCBTBUCRBUBVFDCBVBCUDPBUCBWTVDCTFUBVDTBVRBVÿ:r,1,CDCWRCFDRCWBTPPCDWDCRFCRCDBRCDVRCDFCRWUCBCDCDFCUCDRDCRCFRCDVDCPPDRBCDVFDTCDUPCDCVCBRCDCWUCDCFDRCDCVCPPCDCTWRFUCDCDCPVCRCFDBRCDCRCFDRCWTBPPCDWCRFCRCDBRCDVCDFWCRUCBCDCDFCUCDRDCRCFRCDVDCPPDRBCDVFDTCDUPCRDCVCRCDCWUCDCFDRCDCVWCPPCDCTWRUCDCDCPVCRCFDBRCDCRCFDRCWTPPCDVWCRFCRCDBRCDVCDFCRUCBCDCDFCUCDRDCRCFRCDVDCPPWDRBCDVFDTCDUPCDCVCRCDCWUCDCFDRCDCVCBPPCDCTWRUCDCDCPVCRCFDBRÿ:r,1,CBDVFCBDPPBDTBVFBCDVBDVCTWCDBVFVCBDUBCBVCBDVDFTBVCDVWCURBUDFTRDCVBVPPTBCVRCBVBRURFBVBDCRPBWUVBCBVTFRBCVCUCBDPCBRWBVCFBDBVBCTDCDCBDVFCBDPPBTBVFBCDVBDVCTWDBVFCPBDUBCBVUCBDVDFTBVCDVWURBUDFTRDCVBVPPTBCVRCBVBRURFBVBDCPBWUBCBVFRBRCVCUBVDPCRCWBVCFBDBVBCDTCDCBDVFCBDPPBTBVFBRCDVBDVCTWDBVFCBDUBCBVCBRDVDFTUBVCDVWURBUDFTRDCVBVPPTBCVRCBVBRURFBVBDCPBCWUBCBUVFRBCTVCUBDUPCRWBTVCFBDBVBTCDCDÿ:r,1,BCBDVCBUDWTBRBCDBCVDBCBCRCBCVTWRCBVCUBPPTRBCBDBCVBUCRBDVBPPBVCTDBCBUCVDBCRBCWBPPTBUDCBCTBCWBCBCVCPPCDURCBCBTRCVBPBDBVCDCBVBRBCBDVCBUDWBRBCDBCVDBCBCRCBCTWRCBVCUBPPVTRBCBDBCVBUCRBDVBPPBVCDBCBUCVDBCRBCWBTPPBUDCBCTBCWBCBCVCPPDURCBCBTRVBPBDBVCDCBVBRBCBDVPPCBUCDWBRBCDBCVDBCBCRCBDCTWRCBVCUBPPTRBCBDBCVBUCRBDVBPPBVCDBCBUCVDBCRBCWBTBUDCBCTBCWBCBCVCPPDURCBCBTWRVBPBDBVCDCBVBRÿ:r,2,BCBCRWCDUBPPBCRBDBCRBPCBCBCDVBRCDBDPPBCVDBUDCBTBDCRBCUVCDBCBCRWCUBPPBCRBDBCRBPCBCBCDVBRPCDBDBCVDBUDCBTBCRBCUVCDBCBCRWCUBPPBCRBDBCRBDPCBCBCDVBRCDBDBCVDBUDCBTBCRBCUVCDÿ:r,2,BCBDFBRBUPBVDCUBCBFVRBDTBFBDBPPBCBRBWVFCDBUBTBFBRUTDVBCUBDFBRBUPBTVDCUBCBFVRBDTBFBDBPPBCBURBWVFCDBUBTBFBRUTDVBCBDFBRBUPBVDCUBCBFVRBDTBFBDBPPBCBRBWVFCDBUBTBFBRUCTDVÿ:r,2,CFDWCBVCDRCDFCDCRWCRCTFDCDCDUCPRCDVRCFTRCVBDWCFRCDCRPPDRCDWCDBVCDRCDFCDCRWCRCTFDCDCDUCPRCDVCFWTRCVBDCFRCDCRPPDRCDWCBVCDRCDFCDCRWCRCTFDCDCDUCPRCDVCFTRCVWBDCFRCDCRPPDRÿ:r,2,CBVDBCTDRFCPPBWDVCFRVBCBVDUBDFVRDBFURDBDCDPTWBUCFRBTBUVCDCBDBCTDRCPPBWDVCFRVBCBVDUBDFVRDBFURDBDCPTWBUCFBRTBUVCDCBDBCTDRCPPBWDVCFRVBCBTVDUBDFVRDBFURDBDCPTWBUCFBTBUVCDÿ:r,2,BCUBDTWVRBDCBVCBRVDBPBCDBCTWUBRTCDBCBVDBCUVCBRBCRBDCPPBVCBCBDTWVRBDCBVUCBRVDBPBCDBCTWUBRTDBCBVDBCUVCBRCRBDCPPVCBCBDTBWVRBDCBVCBRVDCBPBCDBCTWUBRTDBCBVDBCUVCBRCRBDCPPVCÿ:r,3,BCBCRWCUBPPBCRBDBCRPPCBCBCDVBPPDBDBCVDBPPCBTBCRBCPPCDBCBCRWCUBPPBCRBDBCRPPCBCBCDVBCPPDBDBCVDBPPCBTBCRBCPPCDBCBCRWCUBPPBCVRBDBCRPPCBCBCDVBPPDBDBCVDBPPCBTBCRBCPPCDÿ:r,3,BCBDFBRBUPPVDCUBCBFPPBDTBFBDBPPBCBRBCWVFDPPBUBTBFCBRPPDVBCBDFBRBUPPVDCUBCBFPPBDTBFBDBPPBCBRBWVFPPBUBTBFBRPPDVBCBDFBRBUPPVDCUBCBFPPBDTBFBDBUPPBCBRBWVFPPBUBTBFBRPPDVÿ:r,3,CDWCBVCDRPPFCDCRWCRPPFDCDCDUCPPCDVCFTRCPPDCFRCDCRPPDRCDWCBVCDRDPPFCDCRWCRPPFDCDCDUCPPCDVCFTRCPPDCFRCDCRPPDRCDWDCBVCDRPPFCDCRWCRPPFDCDCDUCPPCDVCFTRCPPDCFRCDCRPPDRÿ:r,3,CBDBCTDBRCPPBWDVCFRVPPBVDUBDFVPPBFURTDBDCPPWBUCFBTBPPCDCBVDBCTDRCPPFBWDVCFRVPPBVDUBDFVPPBVFURDBDCPPWBUCFBTBPPCDCBDBDCTDRCPPBWDVCFRVPPFBVDUBDFVPPBFURDBDCPPWBUCFBTBPPCDÿ:r,3,BCBDTWCVRBPPBVCBRVDBPPCDBCTWUBPPDBCBVDBCPPCBRCRBDCPPVCBCBDTWVRBPPBVCBRVDBPPCDBCTVWUBPPDBCBVDBCPPCBRCRVBDCPPVCBCBDTWVRBPPBVCBRVDBPPCRDBCTWUBPPDBCRBVDBCPPCBRCRBDCPPVCÿ:j,W,1,0,TUVRDBCMXÿ:j,T,1,0,Mÿ:j,U,1,0,Mÿ:j,V,1,0,Mÿ:j,R,1,0,Xÿ:j,D,1,0,Xÿ:u,APPPP.PP.PP.PPPPÿ:w,F,3,-1,0ÿ:w,P,10,-4000,0ÿ:w,P,9,-1500,0ÿ:w,P,8,-500,0ÿ:w,P,7,-100,0ÿ:w,P,6,-40,0ÿ:w,P,5,-10,0ÿ:w,P,4,-3,0ÿ:w,P,3,-1,0ÿ:w,W,3,200,0ÿ:w,W,4,500,0ÿ:w,W,5,2000,0ÿ:w,T,3,80,0ÿ:w,T,4,240,0ÿ:w,T,5,500,0ÿ:w,U,3,40,0ÿ:w,U,4,120,0ÿ:w,U,5,240,0ÿ:w,V,3,20,0ÿ:w,V,4,60,0ÿ:w,V,5,120,0ÿ:w,M,3,10,0ÿ:w,M,4,30,0ÿ:w,M,5,60,0ÿ:w,R,3,10,0ÿ:w,R,4,30,0ÿ:w,R,5,60,0ÿ:w,D,3,5,0ÿ:w,D,4,15,0ÿ:w,D,5,30,0ÿ:w,X,3,2,0ÿ:w,X,4,6,0ÿ:w,X,5,15,0ÿ:w,B,3,3,0ÿ:w,B,4,8,0ÿ:w,B,5,15,0ÿ:w,C,3,3,0ÿ:w,C,4,8,0ÿ:w,C,5,15,0ÿ:wa,F,3,-1,0,0,0,0:1,-1,0ÿ:wa,P,10,-4000,0,0,0,0:1,-1,0ÿ:wa,P,9,-1500,0,0,0,0:1,-1,0ÿ:wa,P,8,-500,0,0,0,0:1,-1,0ÿ:wa,P,7,-100,0,0,0,0:1,-1,0ÿ:wa,P,6,-40,0,0,0,0:1,-1,0ÿ:wa,P,5,-10,0,0,0,0:1,-1,0ÿ:wa,P,4,-3,0,0,0,0:1,-1,0ÿ:wa,P,3,-1,0,0,0,0:1,-1,0ÿ:wa,W,3,200,0,0,0,0:1,-1,0ÿ:wa,W,4,500,0,0,0,0:1,-1,0ÿ:wa,W,5,2000,0,0,0,0:1,-1,0ÿ:wa,T,3,80,0,0,0,0:1,-1,0ÿ:wa,T,4,240,0,0,0,0:1,-1,0ÿ:wa,T,5,500,0,0,0,0:1,-1,0ÿ:wa,U,3,40,0,0,0,0:1,-1,0ÿ:wa,U,4,120,0,0,0,0:1,-1,0ÿ:wa,U,5,240,0,0,0,0:1,-1,0ÿ:wa,V,3,20,0,0,0,0:1,-1,0ÿ:wa,V,4,60,0,0,0,0:1,-1,0ÿ:wa,V,5,120,0,0,0,0:1,-1,0ÿ:wa,M,3,10,0,0,0,0:1,-1,0ÿ:wa,M,4,30,0,0,0,0:1,-1,0ÿ:wa,M,5,60,0,0,0,0:1,-1,0ÿ:wa,R,3,10,0,0,0,0:1,-1,0ÿ:wa,R,4,30,0,0,0,0:1,-1,0ÿ:wa,R,5,60,0,0,0,0:1,-1,0ÿ:wa,D,3,5,0,0,0,0:1,-1,0ÿ:wa,D,4,15,0,0,0,0:1,-1,0ÿ:wa,D,5,30,0,0,0,0:1,-1,0ÿ:wa,X,3,2,0,0,0,0:1,-1,0ÿ:wa,X,4,6,0,0,0,0:1,-1,0ÿ:wa,X,5,15,0,0,0,0:1,-1,0ÿ:wa,B,3,3,0,0,0,0:1,-1,0ÿ:wa,B,4,8,0,0,0,0:1,-1,0ÿ:wa,B,5,15,0,0,0,0:1,-1,0ÿ:wa,C,3,3,0,0,0,0:1,-1,0ÿ:wa,C,4,8,0,0,0,0:1,-1,0ÿ:wa,C,5,15,0,0,0,0:1,-1,0ÿ:s,0ÿ:i,30ÿ:m,30ÿ:a,0,0ÿ:g,5,1000,-1,false,0,falseÿ:es,0,0ÿ:mbnr,0.0ÿ:fs,0,0,0,0,0,0ÿbs,0,1,0ÿ:k,nullÿe,30,0,0,-1ÿb,0,0,0ÿs,1ÿr,1,5,66,18,112,74,19ÿrw,0";
            }
        }
        #endregion

        public PrizeOfTheNileGameLogic()
        {
            _gameID = GAMEID.PrizeOfTheNile;
            GameName = "PrizeOfTheNile";
        }

        protected override string buildLineBetString(string strGlobalUserID, double balance)
        {
            return string.Format("\u0006S{0}ÿA0ÿC,100.0,,1,ÿT,0,0,0ÿRÿM,30,1200,30,-1,0ÿI00ÿH,0,0,0,0,0,0ÿY,7200,10ÿ:i,30ÿ:m,30ÿ:b,11,1,2,3,4,5,8,10,15,20,30,40ÿ:a,0,0ÿ:g,5,1000,-1,false,0,falseÿ:es,0,0ÿ:mbnr,30.0ÿbs,0,1,0ÿ:k,nullÿe,{1},{2},{3},-1ÿb,1000,1000,0ÿs,1ÿr,1,5,66,18,112,74,19ÿrw,0", balance, !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? this._defaultLine : _dicUserBetInfos[strGlobalUserID].PlayLine, !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? this._defaultBetPerLine : (_dicUserBetInfos[strGlobalUserID].PlayBet / _dicUserBetInfos[strGlobalUserID].PlayLine), !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? Array.IndexOf(_supportLines, this._defaultLine) : Array.IndexOf(_supportLines, _dicUserBetInfos[strGlobalUserID].PlayLine));
        }

        protected override void onDoInit(string strGlobalUserID, GITMessage message, double balance, Currencies currency)
        {
            try
            {
                GITMessage resMessage = new GITMessage((ushort)SCMSG_CODE.SC_GREENTUBE_DOINIT);
                resMessage.Append("%t0ÿq0");
                resMessage.Append(VersionCheckString);
                foreach (string currencyName in SupportCurrencyList)
                {
                    resMessage.Append(currencyName);
                }
                resMessage.Append(buildInitString(strGlobalUserID, balance, currency));
                resMessage.Append("\vGAMEVARIATIONÿ665ÿTICKETSÿ1");
                resMessage.Append(GameUniqueString);

                resMessage.Append("%t0ÿq0");
                resMessage.Append($"\aNATIVEJACKPOTCURRENCYFACTORÿ100.0ÿMAXBUYINTOTALÿ0ÿNEEDSSESSIONTIMEOUTÿ0ÿRELIABILITYÿ0ÿNICKNAMEÿ155258EURÿIDÿ155258ÿISDEEPWALLETÿ0ÿCURRENCYFACTORÿ100.0ÿMINBUYINÿ1ÿSESSIONTIMEOUTMINUTESÿ60ÿJACKPOT_PROGRESSIVE_CAPÿ0.0ÿNATIVEJACKPOTCURRENCYÿ{getCurrencyCode(currency)}ÿEXTUSERIDÿDummyDB_ExternalUserId_155258EURÿFREESPINSISCAPREACHEDÿ0ÿCURRENCYÿ{getCurrencySymbol(currency)}ÿTICKETSÿ0ÿJACKPOT_TOTAL_CAPÿ0.0ÿJACKPOTFEEPERCENTAGEÿ0.0ÿISSHOWJACKPOTCONTRIBUTIONÿ0");
                resMessage.Append(buildLineBetString(strGlobalUserID, balance));

                ToUserMessage toUserMessage = new ToUserMessage((int)_gameID, resMessage);

                Sender.Tell(toUserMessage, Self);
            }
            catch (Exception ex)
            {
                _logger.Error("Exception has been occurred in BaseGreentubeSlotGame::onDoInit GameID: {0}, {1}", _gameID, ex);
            }
        }
        protected override void onBalanceConfirm(string strGlobalUserID, GITMessage message, double balance, Currencies currency)
        {
            try
            {
                GITMessage resMessage = new GITMessage((ushort)SCMSG_CODE.SC_GREENTUBE_BALANCECONFIRM);
                resMessage.Append("%t0ÿq0");
                resMessage.Append($"\aNATIVEJACKPOTCURRENCYFACTORÿ100.0ÿMAXBUYINTOTALÿ0ÿNEEDSSESSIONTIMEOUTÿ0ÿRELIABILITYÿ0ÿNICKNAMEÿ155258EURÿIDÿ155258ÿISDEEPWALLETÿ0ÿCURRENCYFACTORÿ100.0ÿMINBUYINÿ1ÿSESSIONTIMEOUTMINUTESÿ60ÿJACKPOT_PROGRESSIVE_CAPÿ0.0ÿNATIVEJACKPOTCURRENCYÿ{getCurrencyCode(currency)}ÿEXTUSERIDÿDummyDB_ExternalUserId_155258EURÿFREESPINSISCAPREACHEDÿ0ÿCURRENCYÿ{getCurrencySymbol(currency)}ÿTICKETSÿ0ÿJACKPOT_TOTAL_CAPÿ0.0ÿJACKPOTFEEPERCENTAGEÿ0.0ÿISSHOWJACKPOTCONTRIBUTIONÿ0");
                resMessage.Append(buildLineBetString(strGlobalUserID, balance));
                ToUserMessage toUserMessage = new ToUserMessage((int)_gameID, resMessage);

                Sender.Tell(toUserMessage, Self);
            }
            catch (Exception ex)
            {
                _logger.Error("Exception has been occurred in BaseGreentubeSlotGame::onDoInit GameID: {0}, {1}", _gameID, ex);
            }
        }
    }
}
