using GITProtocol;
using SlotGamesNode.GameLogics.BaseClasses;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SlotGamesNode.GameLogics
{
    internal class ShootingStarsGameLogic : BaseGreenSlotGame
    {
        #region
        protected override string ScatterSymbol {
            get
            {
                return "";
            }
        }

        protected override int MinCountToFreespin
        {
            get
            {
                return 0;
            }
        }
        protected override string VersionCheckString
        {
            get
            {
                return "\b0ÿ2.5.16ÿCasino-Lobbymanager-Serverÿ545ÿ1.10.54.0ÿMazooma_Serverÿ1098ÿ1.0.0ÿShooting Stars 96%ÿ1.119.0_2025-04-14_123855ÿ1.183.0";
            }
        }

        protected override string GameUniqueString
        {
            get
            {
                return "\u0006S0ÿA1ÿRÿM,10,10000,2,-1,0ÿI00ÿH,0,0,0,0,0,0ÿ:n,Shooting Stars 96%ÿ:v,3ÿ:l,-----ÿ:l,^^^^^ÿ:l,_____ÿ:l,^-_-^ÿ:l,_-^-_ÿ:l,^^-^^ÿ:l,__-__ÿ:l,-___-ÿ:l,-^^^-ÿ:l,-^-^-ÿ:r,0,KKKAAAQQQTTTAAAJJJAAAKKKAAATTTSSSJJJKKKJJJAAAJJJAAATTTQQQJJJBBBTTTQQQTTTQQQJJJQQQJJJQQQBBBQQQKKKQQQJJJSSSJJJTTTQQQAAATTTSSSÿ:r,0,TTTQQQJJJQQQKKKTTTJJJTTTKKKJJJKKKJJJQQQJJJTTTJJJBBBTTTKKKQQQSSSTTTBBBAAQQJJJAAAKKKTTTKKKTTTQQTTTKKKJTTTJJKKKTTTKKKJJJKKKJJJQQQAAAQQQKKKQQQJJJQQQKKKTTTQQTTTQQKKKTTTBBBTTTAAATTTKKKQQKKKQQKKKTTTWSSSKKKSSAAABBBTTTJJJKKKBBBAAAKKKBBBTTTKKKTTTKKKJJJKKKTTTBBBKKKAAQQQJJJAAAJJTTTWQQQBBBAAKKKWTTTWBBBAAATTTKKKAAAJJJSSAAAJJJBBBJJJQQQKKKTTTQQQJJQQQKKKTTTSSTTTBBBTTTKKKJJJBBBKKKTTTAAATTTKKKBBBJJJQQQKKKQQJJJQQQTTTBBBQQBBBTTTQQQSSJJJAATTTQQBBBWQQJJJBBBTTTKKKTTTKKKTTTKKKAATTTBBBKKKTTTKKKAAKKKÿ:r,0,AAAQQQTTTSSSTTTJJJTTTAAAQQQBBBJJJBBBAAAKKKSSSJJJQQQAAAJJJKKKTTTJJJQQQBBBQQQWTTTKKKSSSKKKJJJQQQAAABBBQQQJJJAAAJJJTTTJJJQQQKKKBBBTTTWJJJAAAQQQKKKQQQJJJQQQTTTJJJTTTKKKBBKKKAAAKKKTTTAAAJJJQQQKKKWTTTSSSKKKTTTKKKTTTJJJBBBTTTSSSBBBJJJQQQKKKAAAQQQBBBQQQAAATTTKKKBBBKKKSSSQQQJJJTTTQQQBBBJJJBBBTTTKKKJJJÿ:r,0,QQQJJJQQQKKKJJJQQQJJJQQQKKKQQQJJJBBBJJJTTTAAATTTJJJAAATTTQQQAAAQQQKKKQQQBBBQQQJJJQQQAAAJJJQQQKKKJJJTTTQQQJJJQQAAABBQQQJJJAAAQQQJJJAAAWSSSJJJBBBWSSSJJJTTTAAAQQQKKKJJJQQQJJJTTTJJJBBQQQTTTKKKJJJKKKJJJQQQAAAJJJQQQTTTQQQTTTSSSQQQKKKTTAAAQQQTTTQQQJJJSSSBBBJJJQQQSSSJJJAAAQQQAAAQQQJJJSSSJJJKKKQQQSSSJJJQQQBBBQQQAAAJJJQQQAAATTJJJTTTBBBJJJKKKAAAQQQBBBQQWJJJKKKJJJTTTQQQBBBAAAJJJKKKÿ:r,0,SSSQQQTTTJJJBBBQQQTTTKKKBBBSSSTTTKKKTTTBBBSSQQQKKKAAAJJJTTTQQQTBBBQQQBBBTTTQQQJJJQQQTTKKKAAAJJJAAAJJJTTTJJJBBKKKJJJKKKJJJKKKBBBKKKQQQKKKÿ:r,1,KKKAAAQQQTTTAAAJJJAAAKKKAAATTTSSSJJJKKKJJJAAAJJJAAATTTQQQJJJBBBTTTQQQTTTQQQJJJQQQJJJQQQBBBQQQKKKQQQJJJSSSJJJTTTQQQAAATTTSSSÿ:r,1,TTTQQQJJJQQQKKKTTTJJJTTTKKKJJJKKKJJJQQQJJJTTTJJJBBBTTTKKKQQQSSSTTTBBBAAQQJJJAAAKKKTTTKKKTTTQQTTTKKKJTTTJJKKKTTTKKKJJJKKKJJJQQQAAAQQQKKKQQQJJJQQQKKKTTTQQTTTQQKKKTTTBBBTTTAAATTTKKKQQKKKQQKKKTTTWSSSKKKSSAAABBBTTTJJJKKKBBBAAAKKKBBBTTTKKKTTTKKKJJJKKKTTTBBBKKKAAQQQJJJAAAJJTTTWQQQBBBAAKKKWTTTWBBBAAATTTKKKAAAJJJSSAAAJJJBBBJJJQQQKKKTTTQQQJJQQQKKKTTTSSTTTBBBTTTKKKJJJBBBKKKTTTAAATTTKKKBBBJJJQQQKKKQQJJJQQQTTTBBBQQBBBTTTQQQSSJJJAATTTQQBBBWQQJJJBBBTTTKKKTTTKKKTTTKKKAATTTBBBKKKTTTKKKAAKKKÿ:r,1,AAAQQQTTTSSSTTTJJJTTTAAAQQQBBBJJJBBBAAAKKKSSSJJJQQQAAAJJJKKKTTTJJJQQQBBBQQQTTTTKKKSSSKKKJJJQQQAAABBBQQQJJJAAAJJJTTTJJJQQQKKKBBBTTTWJJJAAAQQQKKKQQQJJJQQQTTTJJJTTTKKKBBKKKAAAKKKTTTAAAJJJQQQKKKWTTTSSSKKKTTTKKKTTTJJJBBBTTTSSSBBBJJJQQQKKKAAAQQQBBBQQQAAATTTKKKBBBKKKSSSQQQJJJTTTQQQBBBJJJBBBTTTKKKJJJÿ:r,1,QQQJJJQQQKKKJJJQQQJJJQQQKKKQQQJJJBBBJJJTTTAAATTTJJJAAATTTQQQAAAQQQKKKQQQBBBQQQJJJQQQAAAJJJQQQKKKJJJTTTQQQJJJQQAAABBQQQJJJAAAQQQJJJAAAWSSSJJJBBBWSSSJJJTTTAAAQQQKKKJJJQQQJJJTTTJJJBBQQQTTTKKKJJJKKKJJJQQQAAAJJJQQQTTTQQQTTTSSSQQQKKKTTAAAQQQTTTQQQJJJSSSBBBJJJQQQSSSJJJAAAQQQAAAQQQJJJSSSJJJKKKQQQSSSJJJQQQBBBQQQAAAJJJQQQAAATTJJJTTTBBBJJJKKKAAAQQQBBBQQWJJJKKKJJJTTTQQQBBBAAAJJJKKKÿ:r,1,SSSQQQTTTJJJBBBQQQTTTKKKBBBSSSTTTKKKTTTBBBSSQQQKKKAAAJJJTTTQQQTBBBQQQBBBTTTQQQJJJQQQTTKKKAAAJJJAAAJJJTTTJJJBBKKKJJJKKKJJJKKKBBBKKKQQQKKKÿ:r,2,QQQJJJTTTJJJKKKJJJAAAQQQJJJAAQQQKKKJJJAAAQQQBBJJJQQQSSAAAQQQAAAQQAAATTJJJQQQJJJJSSQQQSSSAAAKKKJJJÿ:r,2,WWWWWWWWWWWWWWWWWWWWWWWWÿ:r,2,QQQJJJSSSJJJKKKBBBSSSJJJAAAQQQKKKSSSTTTKKKQQQAAATTTSSJJJQQQAAASSSTTTKKKTTTQQQKKKSSSJJJQQQBBBJJJKKKBBBTTTBBBKKKJJJJTTTSSSTTTKKKJJJSSSKKKSSSAAASSSTTTJJJTTTKKKTTTBBBQQQBBBKKKJJJJQQQTTTQQQJJJTTTBBBAAAQQQSSSJJJSSSTTTKKKTTTQQQKKKSSSKKKSSAAASSSAAAJJJBBBTTTAAAJJJTTTBBAAASSSJJJBBBJJJAAABBBWAAATTTBBBJJJQQQJJJSSSAAASSKKKTTTÿ:r,2,TTQQQAAAQQQKKKAAAJJJAAAJJJQQQJJJSSJJJAAAQQQKKKJJJQQQJJJKKKJJJQQJJJTTTBBBQQQJJJTTTAAAJJJQQQWKKKSSSQQQJJJQQQJJJBBBQQQBBJJJAAAJJJTTTAAAJJJQQQJJJSSAAAQQQKKKTTQQQTTKKKTTJJJQQQAAAQQQJJJQQQBBBQQQTTQQQAAAJJJAAAJJJQQQSSSAAAQQQÿ:r,2,KKKQQQAAAKKKTTTKKKBBBKKKBBKKKTTTBBBTTTQQQSSJJJTTTBBBTTTSSBBBKKKSSSBBBQQQBBBKKKTTTKKKJJJTTTKKKQQQTTTÿ:r,3,SSAAAJJJSSQQQJJJAAAJJJJKKKQQQAAAQQQJJJTTQQQKKKTTTJJJAAABBJJJQQQAAQQQAAAQQQJJJSSSQQQJJJAAAJJJQQKKKÿ:r,3,JJJKKKTTTBBBQQBBBKKKJJJKKKTTTJJTTTQQQBBBKKKTTTBBBKKKTTTQQJJJBBBKKKSSSBBBQQKKKJJAAAQQTTTBBBTTTQQBBBTTTKKKAAAKKKTTTQQQTTTKKKTTTKKKBBBKKKQQQTTTBBBKKKQQQJJJTTTJJJTTTJJJKKKAATTTBBBKKKSSSTTTKKKBBBTTTKKKWTTTJJKKKTTTKKKTTTBBBTTTKKKAATTTKKKBBBTTTKKKBBBKKKTTTBBBQQQTTTKKKAAAKKKTTTKKKBBBKKKBBBQQTTTQQQAAÿ:r,3,WWWWWWWWWWWWWWWWWWWWWWWWÿ:r,3,AAAQQQJJJJSSQQQJJJQQQJJJAAABBBJJJQQQAAAQQQWBBJJJQQQJJJAAAQQQKKKAAAJJJTTTQQQJJJKKKJJJQQQTTBBBJJJQQQJJJQQQKKKJJJAAAQQQBBBQQTTKKKJJJQQQJJJQQQKKKAAATTQQQTTSSSAAAJJJAAAQQQJJJTTTAAATTTQQQJJJKKKQQQJJJTTQQQJJJSSSAAAJJJAAAQQQÿ:r,3,BBBTTTBBQQQTTTJJJTTTKKKQQQTTTKKKSSSKKKBBBKKKQQQKKKSSKKKJJJAAAKKKTTTBBBSSQQQTTTBBBKKKTTTBBBKKKBBBTTTÿ:r,4,QQQJJJAAASSQQQAAAQQJJJJTTTQQQJJJQQQKKKJJJAAQQQAAAKKKAAAKKKQQQJJJSSJJJTTAAAJJJQQQBBJJJQQQSSSJJJAAAÿ:r,4,TTTQQQKKKTTTJJJKKKBBBKKKBBBQQQJJJAAAKKKTTTBBBKKKQQQAAKKKTTTKKKTTTKKKBBBQQJJTTTJJJKKKSSBBBTTTQQKKKAAAQQBBBAAJJJKKKTTTKKKAAKKKTTTBBBQQSSTTTKKKQQQJJTTTBBBTTTKKKAAAJJKKKTTTBBBKKKTTTKKKTTTKKKTTTBBBTTTBBBTTTSSQQQJJJQQQKKKBBBKKKQQTTTQQWTTTBBBKKKTTTKKKTTTBBBJJJKKKBBBTTTKKKTTTBBBTTTKKKTTTKKKBBBTTTBBBÿ:r,4,KKKJJJBBBQQQJJJJKKKBBBKKKSSSQQQAAATTTSSSBBBTTTQQQTTTSSSAAAJJJTTTJJJQQQAAASSSAAAQQQTTTKKKTTTJJJTTTJJJJBBQQQAAAATTTBBBTTTSSSJJJKKKSSSKKKJJJTTTBBBKKKJJJSSSTTTSSSKKKTTTSSSAAASSJJJSSSWQQQBBBJJJBBBJJJSSSAAASSSJJJKKKAAAKKKTTTKKKQQQAAABBBSSSTTTJJJQQQBBBQQQKKKTTTAAAJJJTTTBBBJJJSSSSKKKSSQQQSSSKKKTTTAAAKKKAAAJJJSSBBBQQQJJJJTTTÿ:r,4,WWWWWWWWWWWWWWWWWWWWWWWWÿ:r,4,TTTKKKBBBSSJJJTTTQQQJJJAAAJJJTTTQQQJJJSSSTTTQQQTTTAAAKKKAATTTJJJTTTJJJQQQAAAJJJAAAJJJAAAJJJSSTTTAAAÿ:r,5,QQQAAAKKKQQQJJJTTTQQQJJJKKKSSSJJJJAAABBQQQJJJAAAKKKTTTJJJQQJJJQQQSSQQQKKQQQKKKJJJKKKSSTTTQQQJJJTTTJJJKKKÿ:r,5,WWWWWWWWWWWWWWWWWWWWWWWWÿ:r,5,WWWWWWWWWWWWWWWWWWWWWWWWÿ:r,5,AAAKKKJJJQQQJJJKKKTTTAAASSJJJQQQJJJAAAJJJKKKJJJQQQJJJQQQAAAJJJQQQAAAKKKJJJAAAQQQTTTQQQAAABBBQQQJJJQQQBBQQQJJJWQQQBBBJJJTTAAAKKKJJJSSJJJAAAQQQTTQQJJJAAAQQQJJJJSSQQQSSJJJQQQAAATTJJJTTQQQJJJKKKQQQJJJQQQAAATTTQQQBBBQQQTTÿ:r,5,JJJTTTBBBTTTKKKBBBKKKBBBAAATTTBBBKKKTTTQQQKKKTTTQQQTTTSSJJJTTTSSQQQBBKKKBBBKKKQQQKKKBBBKKKSSSTTTKKKÿ:r,6,AAATTQQQJJJKKKQQQJJJQQJJJAAATTTJJJSSQQQKKKJJJBBJJJQQQAAJJJQQQKKKJJJSSSAAAJJJQQQAAAJJJQQQSSAAAJJJQQQÿ:r,6,WWWWWWWWWWWWWWWWWWWWWWWWÿ:r,6,JJJKKKBBBJJJAAAJJJBBBTTTKKKAAASSKKKWKKKAAATTTKKKSSSBBBQQQJJJKKKTTTAAABBJJJJQQQSSSKKKQQQSSSQQQJJJBBBAAASSSKKKTTTKKKQQQKKKJJJJQQQJJJQQQTTTSSSQQQJJJTTTJJJSSSJJJSSSAAAKKKBBBSSSTTTAAATTTSSQQQKKKJJJAAASSSBBBTTTSSSJJJTTTAAAAJJJAAATTTBBBSSSJJJJSSJJJSSSJJJQQQSSSAAAKKKTTTBBBQQQBBBTTTSSSSKKKBBBJJJTTTAAATTTKKKTTTBBBTTTSSSQQQTTTÿ:r,6,WWWWWWWWWWWWWWWWWWWWWWWWÿ:r,6,AAATTTKKKTTTKKKQQQKKKTTTQQQAAABBBTTTAAAQQQKKKAAATTTKKKQQQTTTKKKTTTSSSTTTJJJKKKAASSTTTSSAAAKKKJJJTTTAAAKKKÿ:r,7,JJJAAJJJJAAAJJJQQQAAAKKKJJJQQQTTQQQJJJAAASSSTTTQQBBQQQJJJQQQKKKAAAQQQAAAJJJQQQAAAJJJKKKSSJJJSSQQQÿ:r,7,BBBKKKQQQKKKTTTKKKBBBJJKKKQQQTTTKKKJJJBBBKKKAAATTTJJJKKKAATTTJJJKKKJJTTTSSBBBKKKTTTBBBKKKAAATTTQQQBBBTTTKKKQQTTTKKKJJQQKKKQQQBBBKKKTTTBBBTTTBBBTTTQQTTTQQQTTTAAQQBBBKKKTTTBBBTTTKKKTTTKKKTTTSSBBBJJJKKKSSKKKJJJKKKTTTJJJKKKTTTKKKQQQWQQTTTQQBBBTTTBBBKKKTTTKKKAATTTKKKBBBTTTBBBTTTBBBKKKAAABBBTTTKKKÿ:r,7,WWWWWWWWWWWWWWWWWWWWWWWWÿ:r,7,WWWWWWWWWWWWWWWWWWWWWWWWÿ:r,7,AAAKKKJJJQQQTTTQQQBBBJJJQQQSSTTTQQQAAATTTAAAJJJTTTJJJAAAJJJSSSKKKTTTSSAAJJJTTTJJJAAATTTJJJAAATTTJJJÿ:r,8,QQQJJJSSQQQSSSJJJTTTJJJKKKAAATTTAAAJJJJQQQKKKAAJJJQQQJJJQQQAAAJJJQQTTTQQQAAAJJJQQQAAAKKKBBAAAJJJQQQTTTÿ:r,8,WWWWWWWWWWWWWWWWWWWWWWWWÿ:r,8,WWWWWWWWWWWWWWWWWWWWWWWWÿ:r,8,WWWWWWWWWWWWWWWWWWWWWWWWÿ:r,8,TTTKKKSSKKKBBBTTTQQQKKKQQQTTTBBBQQQKKKQQQTTTKKKSSJJJBBBTTTBBBTTTKKKTTTKKKJJJTTTKKKBBBSSSBBKKKAAABBBÿ:j,W,1,0,TJQKASBÿ:u,APPPP.PP.PP.PPPPÿ:w,T,5,50,0ÿ:w,T,4,10,0ÿ:w,T,3,5,0ÿ:w,J,5,50,0ÿ:w,J,4,10,0ÿ:w,J,3,5,0ÿ:w,Q,5,80,0ÿ:w,Q,4,15,0ÿ:w,Q,3,7,0ÿ:w,K,5,100,0ÿ:w,K,4,20,0ÿ:w,K,3,8,0ÿ:w,A,5,120,0ÿ:w,A,4,25,0ÿ:w,A,3,10,0ÿ:w,B,5,240,0ÿ:w,B,4,60,0ÿ:w,B,3,25,0ÿ:w,S,5,500,0ÿ:w,S,4,200,0ÿ:w,S,3,50,0ÿ:wa,T,5,50,0,0,0,0:1,-1,0ÿ:wa,T,4,10,0,0,0,0:1,-1,0ÿ:wa,T,3,5,0,0,0,0:1,-1,0ÿ:wa,T,4,10,0,0,1,0:1,-1,0ÿ:wa,T,3,5,0,0,2,0:1,-1,0ÿ:wa,J,5,50,0,0,0,0:1,-1,0ÿ:wa,J,4,10,0,0,0,0:1,-1,0ÿ:wa,J,3,5,0,0,0,0:1,-1,0ÿ:wa,J,4,10,0,0,1,0:1,-1,0ÿ:wa,J,3,5,0,0,2,0:1,-1,0ÿ:wa,Q,5,80,0,0,0,0:1,-1,0ÿ:wa,Q,4,15,0,0,0,0:1,-1,0ÿ:wa,Q,3,7,0,0,0,0:1,-1,0ÿ:wa,Q,4,15,0,0,1,0:1,-1,0ÿ:wa,Q,3,7,0,0,2,0:1,-1,0ÿ:wa,K,5,100,0,0,0,0:1,-1,0ÿ:wa,K,4,20,0,0,0,0:1,-1,0ÿ:wa,K,3,8,0,0,0,0:1,-1,0ÿ:wa,K,4,20,0,0,1,0:1,-1,0ÿ:wa,K,3,8,0,0,2,0:1,-1,0ÿ:wa,A,5,120,0,0,0,0:1,-1,0ÿ:wa,A,4,25,0,0,0,0:1,-1,0ÿ:wa,A,3,10,0,0,0,0:1,-1,0ÿ:wa,A,4,25,0,0,1,0:1,-1,0ÿ:wa,A,3,10,0,0,2,0:1,-1,0ÿ:wa,B,5,240,0,0,0,0:1,-1,0ÿ:wa,B,4,60,0,0,0,0:1,-1,0ÿ:wa,B,3,25,0,0,0,0:1,-1,0ÿ:wa,B,4,60,0,0,1,0:1,-1,0ÿ:wa,B,3,25,0,0,2,0:1,-1,0ÿ:wa,S,5,500,0,0,0,0:1,-1,0ÿ:wa,S,4,200,0,0,0,0:1,-1,0ÿ:wa,S,3,50,0,0,0,0:1,-1,0ÿ:wa,S,4,200,0,0,1,0:1,-1,0ÿ:wa,S,3,50,0,0,2,0:1,-1,0ÿ:s,0ÿ:i,1ÿ:i,2ÿ:i,3ÿ:i,4ÿ:i,5ÿ:i,6ÿ:i,7ÿ:i,8ÿ:i,9ÿ:i,10ÿ:m,1,2,3,4,5,6,7,8,9,10ÿ:a,0,0ÿ:g,999,1000,-1,false,0,falseÿ:es,0,0ÿ:mbnr,0.0ÿ:fs,0,0,0,0,0,0ÿbs,0,1,0ÿ:k,nullÿe,10,0,9,-1ÿb,0,0,0ÿs,1ÿr,0,5,81,464,233,362,67ÿrw,0";
            }
        }
        #endregion

        public ShootingStarsGameLogic()
        {
            _gameID = GAMEID.ShootingStars;
            GameName = "ShootingStars";
        }

        protected override string buildLineBetString(string strGlobalUserID, double balance)
        {
            return string.Format("\u0006S{0}ÿA0ÿC,100.0,,1,ÿT,0,0,0ÿRÿM,2,3000,2,-1,0ÿI00ÿH,0,0,0,0,0,0ÿY,7200,10ÿ:i,1ÿ:i,2ÿ:i,3ÿ:i,4ÿ:i,5ÿ:i,6ÿ:i,7ÿ:i,8ÿ:i,9ÿ:i,10ÿ:m,1,2,3,4,5,6,7,8,9,10ÿ:b,16,2,3,4,5,8,10,15,20,30,40,50,80,100,150,200,300ÿ:a,0,0ÿ:g,999,1000,-1,false,0,falseÿ:es,0,0ÿ:mbnr,2.0ÿbs,0,1,0ÿ:k,nullÿe,{1},{2},{3},-1ÿb,1000,1000,0ÿs,1ÿr,0,5,81,464,233,362,67ÿrw,0", balance, !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? this._defaultLine : _dicUserBetInfos[strGlobalUserID].PlayLine, !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? this._defaultBetPerLine : (_dicUserBetInfos[strGlobalUserID].PlayBet / _dicUserBetInfos[strGlobalUserID].PlayLine), !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? Array.IndexOf(_supportLines, this._defaultLine) : Array.IndexOf(_supportLines, _dicUserBetInfos[strGlobalUserID].PlayLine));
        }

        protected override void onDoInit(string strGlobalUserID, GITMessage message, double balance, Currencies currency)
        {
            try
            {
                GITMessage resMessage = new GITMessage((ushort)SCMSG_CODE.SC_GREENTUBE_DOINIT);
                resMessage.Append("%t0ÿq0");
                resMessage.Append(VersionCheckString);
                foreach (string currencyName in SupportCurrencyList)
                {
                    resMessage.Append(currencyName);
                }
                resMessage.Append(buildInitString(strGlobalUserID, balance, currency));
                resMessage.Append("\vGAMEVARIATIONÿ665ÿTICKETSÿ1");
                resMessage.Append(GameUniqueString);

                resMessage.Append("%t0ÿq0");
                resMessage.Append($"\aNATIVEJACKPOTCURRENCYFACTORÿ100.0ÿMAXBUYINTOTALÿ0ÿNEEDSSESSIONTIMEOUTÿ0ÿRELIABILITYÿ0ÿNICKNAMEÿ155258EURÿIDÿ155258ÿISDEEPWALLETÿ0ÿCURRENCYFACTORÿ100.0ÿMINBUYINÿ1ÿSESSIONTIMEOUTMINUTESÿ60ÿJACKPOT_PROGRESSIVE_CAPÿ0.0ÿNATIVEJACKPOTCURRENCYÿ{getCurrencyCode(currency)}ÿEXTUSERIDÿDummyDB_ExternalUserId_155258EURÿFREESPINSISCAPREACHEDÿ0ÿCURRENCYÿ{getCurrencySymbol(currency)}ÿTICKETSÿ0ÿJACKPOT_TOTAL_CAPÿ0.0ÿJACKPOTFEEPERCENTAGEÿ0.0ÿISSHOWJACKPOTCONTRIBUTIONÿ0");
                resMessage.Append(buildLineBetString(strGlobalUserID, balance));

                ToUserMessage toUserMessage = new ToUserMessage((int)_gameID, resMessage);

                Sender.Tell(toUserMessage, Self);
            }
            catch (Exception ex)
            {
                _logger.Error("Exception has been occurred in BaseGreentubeSlotGame::onDoInit GameID: {0}, {1}", _gameID, ex);
            }
        }
        protected override void onBalanceConfirm(string strGlobalUserID, GITMessage message, double balance, Currencies currency)
        {
            try
            {
                GITMessage resMessage = new GITMessage((ushort)SCMSG_CODE.SC_GREENTUBE_BALANCECONFIRM);
                resMessage.Append("%t0ÿq0");
                resMessage.Append($"\aNATIVEJACKPOTCURRENCYFACTORÿ100.0ÿMAXBUYINTOTALÿ0ÿNEEDSSESSIONTIMEOUTÿ0ÿRELIABILITYÿ0ÿNICKNAMEÿ155258EURÿIDÿ155258ÿISDEEPWALLETÿ0ÿCURRENCYFACTORÿ100.0ÿMINBUYINÿ1ÿSESSIONTIMEOUTMINUTESÿ60ÿJACKPOT_PROGRESSIVE_CAPÿ0.0ÿNATIVEJACKPOTCURRENCYÿ{getCurrencyCode(currency)}ÿEXTUSERIDÿDummyDB_ExternalUserId_155258EURÿFREESPINSISCAPREACHEDÿ0ÿCURRENCYÿ{getCurrencySymbol(currency)}ÿTICKETSÿ0ÿJACKPOT_TOTAL_CAPÿ0.0ÿJACKPOTFEEPERCENTAGEÿ0.0ÿISSHOWJACKPOTCONTRIBUTIONÿ0");
                resMessage.Append(buildLineBetString(strGlobalUserID, balance));
                ToUserMessage toUserMessage = new ToUserMessage((int)_gameID, resMessage);

                Sender.Tell(toUserMessage, Self);
            }
            catch (Exception ex)
            {
                _logger.Error("Exception has been occurred in BaseGreentubeSlotGame::onDoInit GameID: {0}, {1}", _gameID, ex);
            }
        }
    }
}
