using GITProtocol;
using SlotGamesNode.GameLogics.BaseClasses;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SlotGamesNode.GameLogics
{
    internal class StarsInfernoGameLogic : BaseGreenSlotGame
    {
        #region
        protected override string ScatterSymbol
        {
            get
            {
                return "";
            }
        }

        protected override int MinCountToFreespin
        {
            get
            {
                return 0;
            }
        }

        protected override string VersionCheckString
        {
            get
            {
                return "\b0ÿ2.5.16ÿCasino-Lobbymanager-Serverÿ11619ÿ1.10.54.0ÿEurocoinInteractiveSharedJackpotServerÿ12628ÿ1.0.1ÿStars Inferno 95%ÿ1.118.0_2025-03-28_090804ÿ1.68.0";
            }
        }

        protected override string GameUniqueString
        {
            get
            {
                return "\u0006S0ÿA1ÿRÿM,10,10000,2,-1,0ÿI00ÿH,0,0,0,0,0,0ÿ:n,Stars Inferno 95%ÿ:v,3ÿ:l,-----ÿ:l,^^^^^ÿ:l,_____ÿ:l,^-_-^ÿ:l,_-^-_ÿ:l,-___-ÿ:l,-^^^-ÿ:l,__-^^ÿ:l,^^-__ÿ:l,_---^ÿ:r,0,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,0,777PPPMMMLLLOOOPPPLLLCCCMMMPPPBBBPYBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPMMMCCCPPPMMMLLLPPPMMMLLLOOOLLLÿ:r,0,777CCCBBBPPPOOO777MMMGGGLLLBBBCCC777MMMPPPGGGOOOBBBCCCLLL777MMMCCCLLLPPPOOOGGGMMMPPPOYPOOOBBBGGGCCCLLLBBBLLLÿ:r,0,777OOOCCCGGGCCCBBBPPPOOOGGGOOOCCCLLLOOOCCCOOOMMMPPPLLLOOOMMMCCCGGGOOOCYOCCCPPPOOOCCCLLLCCCOOOGGGOOOGGGCCCGGGCCCÿ:r,0,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,1,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,1,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,1,777CCCBBBPPPOOO777MMMGGGLLLBBBCCC777MMMPPPGGGOOOBBBCCCLLL777MMMCCCLLLPPPOOOGGGMMMPPPOYPOOOBBBGGGCCCLLLBBBLLLÿ:r,1,777OOOCCCGGGCCCBBBPPPOOOGGGOOOCCCLLLOOOCCCOOOMMMPPPLLLOOOMMMCCCGGGOOOCYOCCCPPPOOOCCCLLLCCCOOOGGGOOOGGGCCCGGGCCCÿ:r,1,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,2,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,2,777PPPMMMLLLOOOPPPLLLCCCMMMPPPBBBPYBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPMMMCCCPPPMMMLLLPPPMMMLLLOOOLLLÿ:r,2,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,2,777OOOCCCGGGCCCBBBPPPOOOGGGOOOCCCLLLOOOCCCOOOMMMPPPLLLOOOMMMCCCGGGOOOCYOCCCPPPOOOCCCLLLCCCOOOGGGOOOGGGCCCGGGCCCÿ:r,2,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,3,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,3,777PPPMMMLLLOOOPPPLLLCCCMMMPPPBBBPYBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPMMMCCCPPPMMMLLLPPPMMMLLLOOOLLLÿ:r,3,777CCCBBBPPPOOO777MMMGGGLLLBBBCCC777MMMPPPGGGOOOBBBCCCLLL777MMMCCCLLLPPPOOOGGGMMMPPPOYPOOOBBBGGGCCCLLLBBBLLLÿ:r,3,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,3,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,4,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,4,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,4,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,4,777OOOCCCGGGCCCBBBPPPOOOGGGOOOCCCLLLOOOCCCOOOMMMPPPLLLOOOMMMCCCGGGOOOCYOCCCPPPOOOCCCLLLCCCOOOGGGOOOGGGCCCGGGCCCÿ:r,4,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,5,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,5,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,5,777CCCBBBPPPOOO777MMMGGGLLLBBBCCC777MMMPPPGGGOOOBBBCCCLLL777MMMCCCLLLPPPOOOGGGMMMPPPOYPOOOBBBGGGCCCLLLBBBLLLÿ:r,5,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,5,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,6,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,6,777PPPMMMLLLOOOPPPLLLCCCMMMPPPBBBPYBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPMMMCCCPPPMMMLLLPPPMMMLLLOOOLLLÿ:r,6,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,6,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,6,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,7,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,7,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,7,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,7,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,7,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,8,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,8,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,8,777CCCBBBPPPOOO777MMMGGGLLLBBBCCC777MMMPPPGGGOOOBBBCCCLLL777MMMCCCLLLPPPOOOGGGMMMPPPOYPOOOBBBGGGCCCLLLBBBLLLÿ:r,8,777OOOCCCGGGCCCBBBPPPOOOGGGOOOCCCLLLOOOCCCOOOMMMPPPLLLOOOMMMCCCGGGOOOCYOCCCPPPOOOCCCLLLCCCOOOGGGOOOGGGCCCGGGCCCÿ:r,8,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,9,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,9,777PPPMMMLLLOOOPPPLLLCCCMMMPPPBBBPYBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPMMMCCCPPPMMMLLLPPPMMMLLLOOOLLLÿ:r,9,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,9,777OOOCCCGGGCCCBBBPPPOOOGGGOOOCCCLLLOOOCCCOOOMMMPPPLLLOOOMMMCCCGGGOOOCYOCCCPPPOOOCCCLLLCCCOOOGGGOOOGGGCCCGGGCCCÿ:r,9,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,10,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,10,777PPPMMMLLLOOOPPPLLLCCCMMMPPPBBBPYBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPMMMCCCPPPMMMLLLPPPMMMLLLOOOLLLÿ:r,10,777CCCBBBPPPOOO777MMMGGGLLLBBBCCC777MMMPPPGGGOOOBBBCCCLLL777MMMCCCLLLPPPOOOGGGMMMPPPOYPOOOBBBGGGCCCLLLBBBLLLÿ:r,10,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,10,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,11,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,11,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,11,XXXOOOMMMLLLPPPLLLGGGLLLPPPOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLÿ:r,11,777OOOCCCGGGCCCBBBPPPOOOGGGOOOCCCLLLOOOCCCOOOMMMPPPLLLOOOMMMCCCGGGOOOCYOCCCPPPOOOCCCLLLCCCOOOGGGOOOGGGCCCGGGCCCÿ:r,11,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,12,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,12,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,12,777CCCBBBPPPOOO777MMMGGGLLLBBBCCC777MMMPPPGGGOOOBBBCCCLLL777MMMCCCLLLPPPOOOGGGMMMPPPOYPOOOBBBGGGCCCLLLBBBLLLÿ:r,12,XXXGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPÿ:r,12,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,13,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,13,777PPPMMMLLLOOOPPPLLLCCCMMMPPPBBBPYBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPMMMCCCPPPMMMLLLPPPMMMLLLOOOLLLÿ:r,13,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,13,XXXGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPÿ:r,13,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,14,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,14,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,14,XXXLLLOOOMMMLLLPPPLLLGGGLLLPPPOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPÿ:r,14,XXXBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPOOOPPPLLLCCCMMMPPPÿ:r,14,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,15,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,15,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,15,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,15,777OOOCCCGGGCCCBBBPPPOOOGGGOOOCCCLLLOOOCCCOOOMMMPPPLLLOOOMMMCCCGGGOOOCYOCCCPPPOOOCCCLLLCCCOOOGGGOOOGGGCCCGGGCCCÿ:r,15,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,16,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,16,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,16,777CCCBBBPPPOOO777MMMGGGLLLBBBCCC777MMMPPPGGGOOOBBBCCCLLL777MMMCCCLLLPPPOOOGGGMMMPPPOYPOOOBBBGGGCCCLLLBBBLLLÿ:r,16,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,16,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,17,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,17,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,17,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,17,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,17,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,18,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,18,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,18,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,18,777OOOCCCGGGCCCBBBPPPOOOGGGOOOCCCLLLOOOCCCOOOMMMPPPLLLOOOMMMCCCGGGOOOCYOCCCPPPOOOCCCLLLCCCOOOGGGOOOGGGCCCGGGCCCÿ:r,18,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,19,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,19,777PPPMMMLLLOOOPPPLLLCCCMMMPPPBBBPYBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPMMMCCCPPPMMMLLLPPPMMMLLLOOOLLLÿ:r,19,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,19,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,19,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,20,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,20,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,20,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,20,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,20,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,21,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,21,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,21,777CCCBBBPPPOOO777MMMGGGLLLBBBCCC777MMMPPPGGGOOOBBBCCCLLL777MMMCCCLLLPPPOOOGGGMMMPPPOYPOOOBBBGGGCCCLLLBBBLLLÿ:r,21,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,21,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,22,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,22,777PPPMMMLLLOOOPPPLLLCCCMMMPPPBBBPYBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPMMMCCCPPPMMMLLLPPPMMMLLLOOOLLLÿ:r,22,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,22,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,22,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,23,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,23,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,23,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,23,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,23,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,24,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,24,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,24,XXXCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPOOOPPPLLLCCCMMMPPPBBBPPPLLLÿ:r,24,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,24,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,25,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,25,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,25,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,25,XXXPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGÿ:r,25,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:r,26,777GGGCCCLLLPPPOOOBBBCCCOOOCCCGGGMMMPPPCCCGGGCCCPPPGGGPPPOOOCCCOOOBBBOOOCCCOOOCCCGGGOOOCCCGGGOOOLLLGGGCCCOOOÿ:r,26,MPS7LLLPPPOOOCCC7LSGCCCGGGOOOBBBGCSBOCCCOOOLLLPPPBOSMPMMMPPPCCCOOOÿ:r,26,XXXOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPLLLOOOMMMLLLPPPLLLGGGLLLPPPÿ:r,26,XXXLLLOOOMMMLLLPPPLLLGGGLLLPPPOOOPPPLLLCCCMMMPPPBBBPPPLLLCCCPPPGGGPPPÿ:r,26,777LLLMMMBBBMMMLLLOOOGGGPPPLLLMMMPPPOOOLLLPPPLLLPPPBBBOOOCCCMMMPPPLLLPPPLLLPPPOOOLLLMMMLLLPPPMMMPPPCCCLLLMMMÿ:j,S,1,0,ÿ:j,X,1,0,ÿ:u,APPPP.PP.PP.PPPPÿ:w,#,103,-5000,1:Grandÿ:w,#,102,-1250,1:Majorÿ:w,#,101,-200,1:Minorÿ:w,#,100,-50,1:Miniÿ:w,7,5,1000,0ÿ:w,7,4,500,0ÿ:w,7,3,100,0ÿ:w,B,5,500,0ÿ:w,B,4,200,0ÿ:w,B,3,50,0ÿ:w,M,5,200,0ÿ:w,M,4,50,0ÿ:w,M,3,20,0ÿ:w,G,5,200,0ÿ:w,G,4,50,0ÿ:w,G,3,20,0ÿ:w,P,5,150,0ÿ:w,P,4,30,0ÿ:w,P,3,10,0ÿ:w,O,5,150,0ÿ:w,O,4,30,0ÿ:w,O,3,10,0ÿ:w,L,5,100,0ÿ:w,L,4,20,0ÿ:w,L,3,10,0ÿ:w,C,5,100,0ÿ:w,C,4,20,0ÿ:w,C,3,10,0ÿ:wa,#,103,-5000,1:Grand,0,0,0:1,-1,0ÿ:wa,#,102,-1250,1:Major,0,0,0:1,-1,0ÿ:wa,#,101,-200,1:Minor,0,0,0:1,-1,0ÿ:wa,#,100,-50,1:Mini,0,0,0:1,-1,0ÿ:wa,7,5,1000,0,0,0,0:1,-1,0ÿ:wa,7,4,500,0,0,0,0:1,-1,0ÿ:wa,7,3,100,0,0,0,0:1,-1,0ÿ:wa,7,4,500,0,0,1,0:1,-1,0ÿ:wa,7,3,100,0,0,2,0:1,-1,0ÿ:wa,B,5,500,0,0,0,0:1,-1,0ÿ:wa,B,4,200,0,0,0,0:1,-1,0ÿ:wa,B,3,50,0,0,0,0:1,-1,0ÿ:wa,B,4,200,0,0,1,0:1,-1,0ÿ:wa,B,3,50,0,0,2,0:1,-1,0ÿ:wa,M,5,200,0,0,0,0:1,-1,0ÿ:wa,M,4,50,0,0,0,0:1,-1,0ÿ:wa,M,3,20,0,0,0,0:1,-1,0ÿ:wa,M,4,50,0,0,1,0:1,-1,0ÿ:wa,M,3,20,0,0,2,0:1,-1,0ÿ:wa,G,5,200,0,0,0,0:1,-1,0ÿ:wa,G,4,50,0,0,0,0:1,-1,0ÿ:wa,G,3,20,0,0,0,0:1,-1,0ÿ:wa,G,4,50,0,0,1,0:1,-1,0ÿ:wa,G,3,20,0,0,2,0:1,-1,0ÿ:wa,P,5,150,0,0,0,0:1,-1,0ÿ:wa,P,4,30,0,0,0,0:1,-1,0ÿ:wa,P,3,10,0,0,0,0:1,-1,0ÿ:wa,P,4,30,0,0,1,0:1,-1,0ÿ:wa,P,3,10,0,0,2,0:1,-1,0ÿ:wa,O,5,150,0,0,0,0:1,-1,0ÿ:wa,O,4,30,0,0,0,0:1,-1,0ÿ:wa,O,3,10,0,0,0,0:1,-1,0ÿ:wa,O,4,30,0,0,1,0:1,-1,0ÿ:wa,O,3,10,0,0,2,0:1,-1,0ÿ:wa,L,5,100,0,0,0,0:1,-1,0ÿ:wa,L,4,20,0,0,0,0:1,-1,0ÿ:wa,L,3,10,0,0,0,0:1,-1,0ÿ:wa,L,4,20,0,0,1,0:1,-1,0ÿ:wa,L,3,10,0,0,2,0:1,-1,0ÿ:wa,C,5,100,0,0,0,0:1,-1,0ÿ:wa,C,4,20,0,0,0,0:1,-1,0ÿ:wa,C,3,10,0,0,0,0:1,-1,0ÿ:wa,C,4,20,0,0,1,0:1,-1,0ÿ:wa,C,3,10,0,0,2,0:1,-1,0ÿ:s,0ÿ:i,1ÿ:i,2ÿ:i,3ÿ:i,4ÿ:i,5ÿ:i,6ÿ:i,7ÿ:i,8ÿ:i,9ÿ:i,10ÿ:m,1,2,3,4,5,6,7,8,9,10ÿ:a,0,0ÿ:g,999,1000,-1,false,0,falseÿ:es,0,0ÿ:mbnr,0.0ÿ:fs,0,0,0,0,0,0ÿbs,0,1,0ÿ:k,nullÿe,10,0,9,-1ÿb,0,0,0ÿs,1ÿr,0,5,106,73,28,13,46ÿx,1,j=-1ÿrw,0";
            }
        }
        #endregion

        public StarsInfernoGameLogic()
        {
            _gameID = GAMEID.StarsInferno;
            GameName = "StarsInferno";
        }
        
        protected override string buildLineBetString(string strGlobalUserID, double balance)
        {
            return string.Format("\u0006S{0}ÿA0ÿC,100.0,,1,ÿT,0,0,0ÿRÿM,2,5000,2,-1,0ÿI00ÿH,0,0,0,0,0,0ÿY,7200,10ÿ:i,1ÿ:i,2ÿ:i,3ÿ:i,4ÿ:i,5ÿ:i,6ÿ:i,7ÿ:i,8ÿ:i,9ÿ:i,10ÿ:m,1,2,3,4,5,6,7,8,9,10ÿ:b,18,2,3,4,5,8,10,15,20,30,40,50,80,100,150,200,300,400,500ÿ:a,0,0ÿ:g,999,1000,-1,false,0,falseÿ:es,0,0ÿ:mbnr,2.0ÿbs,0,1,0ÿ:k,nullÿe,{1},{2},{3},-1ÿb,1000,1000,0ÿs,1ÿr,0,5,106,73,28,13,46ÿx,6,jc=4324:592:23:1,jsc=526.0:2.1968215E8:15812.0:1.8286575688E10,j=-1,jhi=1.177700215E10:2.8969105026E10:3.4099232802E10:1.8286575688E10,js=805363209:805359032:805358728:804939776,jhs=805015074:804283481:805125722:804939776ÿrw,0", balance, !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? this._defaultLine : _dicUserBetInfos[strGlobalUserID].PlayLine, !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? this._defaultBetPerLine : (_dicUserBetInfos[strGlobalUserID].PlayBet / _dicUserBetInfos[strGlobalUserID].PlayLine), !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? Array.IndexOf(_supportLines, this._defaultLine) : Array.IndexOf(_supportLines, _dicUserBetInfos[strGlobalUserID].PlayLine));
        }

        protected override void onDoInit(string strGlobalUserID, GITMessage message, double balance, Currencies currency)
        {
            try
            {
                GITMessage resMessage = new GITMessage((ushort)SCMSG_CODE.SC_GREENTUBE_DOINIT);
                resMessage.Append("%t0ÿq0");
                resMessage.Append(VersionCheckString);
                foreach (string currencyName in SupportCurrencyList)
                {
                    resMessage.Append(currencyName);
                }
                resMessage.Append(buildInitString(strGlobalUserID, balance, currency));
                resMessage.Append("\vGAMEVARIATIONÿ665ÿTICKETSÿ1");

                resMessage.Append(GameUniqueString);
                
                resMessage.Append("%t0ÿq0");
                resMessage.Append($"\aNATIVEJACKPOTCURRENCYFACTORÿ100.0ÿMAXBUYINTOTALÿ0ÿNEEDSSESSIONTIMEOUTÿ0ÿRELIABILITYÿ0ÿNICKNAMEÿ155258EURÿIDÿ155258ÿISDEEPWALLETÿ0ÿCURRENCYFACTORÿ100.0ÿMINBUYINÿ1ÿSESSIONTIMEOUTMINUTESÿ60ÿJACKPOT_PROGRESSIVE_CAPÿ0.0ÿNATIVEJACKPOTCURRENCYÿ{getCurrencyCode(currency)}ÿEXTUSERIDÿDummyDB_ExternalUserId_155258EURÿFREESPINSISCAPREACHEDÿ0ÿCURRENCYÿ{getCurrencySymbol(currency)}ÿTICKETSÿ0ÿJACKPOT_TOTAL_CAPÿ0.0ÿJACKPOTFEEPERCENTAGEÿ0.0ÿISSHOWJACKPOTCONTRIBUTIONÿ0");
                resMessage.Append(buildLineBetString(strGlobalUserID, balance));

                ToUserMessage toUserMessage = new ToUserMessage((int)_gameID, resMessage);

                Sender.Tell(toUserMessage, Self);
            }
            catch (Exception ex)
            {
                _logger.Error("Exception has been occurred in BaseGreentubeSlotGame::onDoInit GameID: {0}, {1}", _gameID, ex);
            }
        }
        protected override void onBalanceConfirm(string strGlobalUserID, GITMessage message, double balance, Currencies currency)
        {
            try
            {
                GITMessage resMessage = new GITMessage((ushort)SCMSG_CODE.SC_GREENTUBE_BALANCECONFIRM);
                resMessage.Append("%t0ÿq0");
                resMessage.Append($"\aNATIVEJACKPOTCURRENCYFACTORÿ100.0ÿMAXBUYINTOTALÿ0ÿNEEDSSESSIONTIMEOUTÿ0ÿRELIABILITYÿ0ÿNICKNAMEÿ155258EURÿIDÿ155258ÿISDEEPWALLETÿ0ÿCURRENCYFACTORÿ100.0ÿMINBUYINÿ1ÿSESSIONTIMEOUTMINUTESÿ60ÿJACKPOT_PROGRESSIVE_CAPÿ0.0ÿNATIVEJACKPOTCURRENCYÿ{getCurrencyCode(currency)}ÿEXTUSERIDÿDummyDB_ExternalUserId_155258EURÿFREESPINSISCAPREACHEDÿ0ÿCURRENCYÿ{getCurrencySymbol(currency)}ÿTICKETSÿ0ÿJACKPOT_TOTAL_CAPÿ0.0ÿJACKPOTFEEPERCENTAGEÿ0.0ÿISSHOWJACKPOTCONTRIBUTIONÿ0");
                resMessage.Append(buildLineBetString(strGlobalUserID, balance));
                ToUserMessage toUserMessage = new ToUserMessage((int)_gameID, resMessage);

                Sender.Tell(toUserMessage, Self);
            }
            catch (Exception ex)
            {
                _logger.Error("Exception has been occurred in BaseGreentubeSlotGame::onDoInit GameID: {0}, {1}", _gameID, ex);
            }
        }
    }
}
