using GITProtocol;
using SlotGamesNode.GameLogics.BaseClasses;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SlotGamesNode.GameLogics
{
    internal class WinterQueenGameLogic : BaseGreenSlotGame
    {
        #region
        protected override string ScatterSymbol {
            get
            {
                return "S";
            }
        }

        protected override int MinCountToFreespin
        {
            get
            {
                return 0;
            }
        }
        protected override string VersionCheckString
        {
            get
            {
                return "\b0ÿ2.5.16ÿCasino-Lobbymanager-Serverÿ919ÿ1.10.54.0ÿNGI_GS2_Slot_Serverÿ3204ÿ1.0.0ÿWinter Queen 95%ÿ1.102.0_2024-02-26_095937ÿ1.88.1";
            }
        }

        protected override string GameUniqueString
        {
            get
            {
                return "\u0006S0ÿA1ÿRÿM,10,10000,40,-1,0ÿI00ÿH,0,0,0,0,0,0ÿ:n,Winter Queen 95%ÿ:v,4ÿ:l,^^^^^ÿ:l,-----ÿ:l,_____ÿ:l,VVVVVÿ:l,^-_-^ÿ:l,-_V_-ÿ:l,_-^-_ÿ:l,V_-_Vÿ:l,^^^^-ÿ:l,----^ÿ:l,____Vÿ:l,VVVV_ÿ:l,^----ÿ:l,----_ÿ:l,____-ÿ:l,V____ÿ:l,-^^^^ÿ:l,-____ÿ:l,_----ÿ:l,_VVVVÿ:l,^^^-_ÿ:l,---_Vÿ:l,___-^ÿ:l,VVV_-ÿ:l,^-___ÿ:l,-_VVVÿ:l,_-^^^ÿ:l,V_---ÿ:l,^^-^^ÿ:l,--^--ÿ:l,__V__ÿ:l,VV_VVÿ:l,^---^ÿ:l,--_--ÿ:l,__-__ÿ:l,V___Vÿ:l,-^^^-ÿ:l,-___-ÿ:l,_---_ÿ:l,_VVV_ÿ:r,0,QJBBBBQWAJQHHHHJAQSJKAWJQKPPPPAQKJWQKJAQSJKQXXXXAQKJAQKWAPPPPAJQKAJHHHHKAJBBBBQJKAQBBBBQWAJQHHHHJAQSJKAWJQKPPPPQKJWQKJAQSJKQXXXXAQBBBBKJAQKWAPPPPAJQKAJHHHHKAJBBBBQJKAQBBBBQWAJQHHHHJAQSJKAWJQKPPPPQKJWQKJAQBBBBSJKQXXXXAQKJAQKWAPPPPAJQKAJHHHHKAJBBBBQJKAQBBBBQWAJQHHHHJAQSJKAWJQKPPPPQKJWQBBBBKJAQSWJKQXXXXAQKJAQKWAPPPPAJQKAJHHHHKAJBBBBQJKAÿ:r,0,JQBBBBQKAJQHHHHJAQSKAQJXXXXQKJWQKJWQKJAQSJKQXXXXQKJAQKWAJPPPPAJQKAJHHHHKAJBBBBQKAJQBBBBQKAJQHHHHJAQSKAQJKXXXXQKJWQKJWQKJAQSJKQXXXXQKJAQKWAJPPPPAJQKAJHHHHKAJBBBBQKAJQBBBBQKWAJQHHHHJAQSKAQJXXXXQKJWQKJWQKJAQSJWKQXXXXQKJAQKWAJPPPPAJQKAJHHHHKAJBBBBQKAJQBBBBQKAJWQHHHHJAQWSKAQJXXXXQKJWQKJWQKJAQSJKQXXXXQKJAQKWAJPPPPAJQKAJHHHHKAJBBBBQKAÿ:r,0,JWQAJKBBBBQKAJQHHHHAJQKAJQKPPPPKJWQKJAQSJKQXXXXJAQKJAQKWAJKPPPPAJQKAJHHHHKAJBBBBQAJWQAJKBBBBQKAJQHHHHAJQKAJQKPPPPKJWQKJAQSJKQXXXXJAQKJAQKWAJKPPPPAJQKAJHHHHKAJBBBBQAJWQAJKBBBBQKAJQHHHHAJQKAJQKPPPPKJWQKJAQSJKQXXXXJAQKJAQKWAQJKPPPPAJQKAJHHHHKAJBBBBQAJWQAJKBBBBQKAJQHHHHAJQKAJQKPPPPKJWQKJAQSJKQXXXXJAQKJAQKWAJKPPPPAJQKAJHHHHKAJBBBBQAÿ:r,0,KSJQABBBBQAKJQHHHHJAQSKAJQPPPPJWQKJWQKJSQKJXXXXAQKJAQKWAJKQPPPPAJQKAJHHHHKAJBBBBQAKJQABBBBQAKJQHHHHJAQSKAJQPPPPJWQKJWQKJSQKJXXXXAQBBBBKJAQKWAJKPPPPASJQKAJHHHHKAJBBBBQAKJQABBBBQAKJQHHHHJAQSKAJQPPPPJWQKJWQKJSQKJXXXXAQKJAQKWAJKPPPPAJQKAJHHHHKASJBBBBQAKJQABBBBQAKJQHHHHJAQSKAJQPPPPJWQKJWQKJSQKBBBBJXXXXAQKJAQKWAJKPPPPAJQKAJHHHHKAJQBBBBQAÿ:r,0,JKABBBBKAJQHHHHJAQSKAJXXXXQKJWQKJWQKJAQSJKQAXXXXAQKJAQKWBBBBAJKPPPPAJQKAJHHHHKAJBBBBAQJKABBBBKAJQHHHHJAQSKAJXXXXQKJWQBBBBKJWQKJBBBBAQSJKQXXXXAQKJAQKWAJKPPPPAJQKAJWHHHHKAJBBBBAQJKABBBBKAJQHHHHJAQSKAJXXXXQKJWQKJWQKJAQSJKQXXXXAQKJAQKWAJKPPPPAJQKAJHHHHKAJBBBBAQJKABBBBKAJQHHHHJAQSKAJXXXXQKJWQKJWQKJAQSJKQXXXXAQKJAQKWAJKPPPPAJQBBBBKAJHHHHKAJBBBBAQÿ:r,1,BBBBQKWAJQHHHHJAQSJKAWJQBBBBKPPPPQKJWQKJAQSJKQXXXXAQKJAQKWAPPPPAJQKAJHHHHKAJBBBBQJKABBBBQKWAJQHHHHJAQSJKAWJQKPPPPQKJWQKJAQSJKQXXXXAQKJAQKWAPPPPAJQKAJHHHHKAJBBBBQJKABBBBQKWAJQHHHHJAQSJKAWJQKPPPPAQKJWQKBBBBJAQSJKBBBBQXXXXAQKJAQKWAPPPPAJQKAJHHHHKAJQBBBBQJKABBBBQKWAJQHHHHJAQSJKAWJQKPPPPQKJWQKJAQSJKQXXXXAQKJAQKWAPPPPSAJQKAJHHHHKAJBBBBQJKAÿ:r,1,JKBBBBQKAJQKHHHHJAQSKAJXXXXQKJWQKJWQKJAQSJKQXXXXAQKJAQKWAJKPPPPAJQKAJHHHHKAJBBBBQAJKBBBBQKWAJQHHHHJAQSKAJXXXXQKJWQKJWQKJAQSJKQXXXXAQKJAQKWAJKPPPPAJQKAJHHHHKAJBBBBQAJKBBBBQKAJQHHHHJBBBBAQSKAJXXXXQKAJWQKJWQKJAQSJKQXXXXAQKJBBBBAQKWAJKPPPPASJQKAJHHHHQKAJBBBBQAJKBBBBQKAJQHHHHJAQSKAJXXXXQKJWQKJWQKJAQSJKQXXXXAQKJAQKWAJKPPPPAJSQKAJHHHHKAJBBBBQAÿ:r,1,JWQAJKBBBBQKAJQHHHHAJQKAJQKPPPPKJWQKJAQSJKQXXXXJAQKJAQKWAJKPPPPAJQKAJHHHHKAJBBBBQAJWQAJKBBBBQKAJQHHHHAJQKAJQKPPPPKJWQKJAQSJKQXXXXJAQKJAQKWAJKPPPPAJQKAJHHHHKAJBBBBQAJWQAJKBBBBQKAJQHHHHAJQKAJQKPPPPKJWQKJAQSJKQXXXXJAQKJAQKWAQJKPPPPAJQKAJHHHHKAJBBBBQAJWQAJKBBBBQKAJQHHHHAJQKAJQKPPPPKJWQKJAQSJKQXXXXJAQKJAQKWAJKPPPPAJQKAJHHHHKAJBBBBQAÿ:r,1,WJQABBBBQAKJQHHHHJAQSKAJQPPPPJWQKJWAQKJSQKJXXXXAQKJAQKWAJKPPPPAJQKAJHHHHKAJBBBBQAWJQABBBBQAKJQHHHHJABBBBQSKAJQPPPPJWQBBBBKJWQKJSQKJXXXXAQKJAQKWAJKPPPPAJQKSAJHHHHKAJBBBBQAWJQABBBBQAKJQHHHHJAQSKAWJQPPPPJWQKJWQKJWSQKJXXXXAQKJAQKWAJKPPPPAJQKASJHHHHKAJBBBBQAWJQABBBBQAKJQHHHHJAQSKAJQWPPPPJWQKJWQKJSQKJXXXXAQKJAQKWAJKPPPPAJQKAJHHHHKAJBBBBQAÿ:r,1,JKABBBBKAJQHHHHJAQSKAJXXXXQKJWQKJWQKJAQSJKQAXXXXAQKJAQKWBBBBAJKPPPPAJQKAJHHHHKAJBBBBAQJKABBBBKAJQHHHHJAQSKAJXXXXQKJWQBBBBKJWQKJBBBBAQSJKQXXXXAQKJAQKWAJKPPPPAJQKAJWHHHHKAJBBBBAQJKABBBBKAJQHHHHJAQSKAJXXXXQKJWQKJWQKJAQSJKQXXXXAQKJAQKWAJKPPPPAJQKAJHHHHKAJBBBBAQJKABBBBKAJQHHHHJAQSKAJXXXXQKJWQKJWQKJAQSJKQXXXXAQKJAQKWAJKPPPPAJQBBBBKAJHHHHKAJBBBBAQÿ:r,2,JKQSAKJQWKAJQHHHHJAWQKJAXXXXQKJAWQKBBBBKAQJPPPPJKAQHHHHKWJASQJKBBBBAQJPPPPQAKJQAJKQSAKJQWKAJQHHHHJAWQKJAXXXXQKJAWQKBBBBKAQJPPPPJKAQHHHHKWJASQJKBBBBAQJPPPPQAKJQAJKQSAKJQWKAJQHHHHJAWQKJAXXXXQKJAWQKBBBBKAQJPPPPJKAQHHHHKWJASQJKBBBBAQJPPPPQAKJQAJKQSAKJQWKAJQHHHHJAWQKJAXXXXQKJAWQKBBBBKAQJPPPPJKAQHHHHKWJASQJKBBBBAQJPPPPQAKJQAÿ:r,2,JQSKAJXXXXJQWKAHHHHJAWQKJXXXXQKJAQKJBBBBJKAWQJKAQHHHHQKAJSQXXXXAJKBBBBAQKJPPPPAQKJWAQJQSKAJXXXXJQWKAHHHHJAWQKJXXXXQKJAQKJBBBBJKAWQJKAQHHHHQKAJSQAJKBBBBAQKJPPPPAQKJWAQJQSKAJXXXXJQWKAHHHHJAWQKJXXXXQKJAQKJBBBBJKAWQJKAQHHHHQKAJSQAJKQBBBBAQKJPPPPAQKJWAQJQSKAJXXXXJQWKAHHHHJAWQKJXXXXQKJAQKQJBBBBJKAWQJKAQHHHHQKAJSQAJKBBBBWAQKJPPPPAQKJWAQÿ:r,2,JKWQJAWQJAKQJAKHHHHJQAKJQXXXXQKJAQKJBBBBJQKAWQJKPPPPJKAQWHHHHJASQJKBBBBAKQJPPPPAKQWJAKJKWQJAWQJAKQJAHHHHJQAKJXXXXQKJAQKJBBBBJQKAWQJKPPPPJKAQHHHHJASQJKBBBBAKQPPPPAKQWJAKJKWQJAWQJAKQJAHHHHJQAKJXXXXQKJAQKJBBBBJQKAWQJKPPPPJKAQHHHHJASQJKBBBBAKQPPPPAKQWJAKJKWQJAWQJAKQJAHHHHJQAKJXXXXQKJAQKJBBBBJQKAWQJKPPPPJKAJQHHHHJASQJKBBBBAKWQPPPPAKQWJAKÿ:r,2,JQKASQJAKQJAKHHHHQJAWQKJXXXXQKJAQKJBBBBKAWQJPPPPJKAQHHHHKJASQJKBBBBAQJPPPPAJKQWAJQKASQJAKQJAKHHHHQJAWQKJXXXXQKJAQKJBBBBKAWQJPPPPJKAQHHHHKJASQJKBBBBAQKJPPPPAJKQWAJQKASQJAKQJAKHHHHQJAWQKJXXXXQKJAQKJBBBBKAWQJPPPPJKAQHHHHKJASQJKBBBBAQJPPPPAJKQWAJQKASQJAKQJAKHHHHQJAWQKJXXXXQKJAQKJBBBBKAWQJPPPPJKAQHHHHKJASQJKBBBBAQJPPPPAJKQWAÿ:r,2,WKAJQKAJXXXXAQJKAHHHHJKAWQKJXXXXJQKWJAQKBBBBKJWAQJSKAQHHHHJKSQJKBBBBAQJPPPPAQKJAQWKAJQKAJXXXXAQJKAHHHHJKAWQKJSXXXXJQKWJAQKBBBBKJWAQJSKAQHHHHJKSQJKBBBBAQJPPPPAQKJAQWKAJQKAJXXXXAQJKAHHHHJKAWQKJXXXXJQKWJAQKBBBBKJWAQJSKAQHHHHJKSQJKBBBBAQKJPPPPAQKJAQWKAJQKAJXXXXAQJKBBBBAHHHHJKAWQKJXXXXJQKWJAQKBBBBKJWAQJSKAQHHHHJKSQJKBBBBAQJPPPPAQKJAQÿ:r,3,AQWKBBBBQAWJKAWJBBBBQKAJPPPPQAKJHHHHKWBBBBQJPPPPQKSJAQXXXXAQKWJHHHHKJAQWKBBBBQAWJKAWJBBBBQKAJPPPPQAKJHHHHKWQJPPPPQKSJAQXXXXAQKWJHHHHKJAQWKBBBBQAWJKAWJBBBBWQKAJPPPPQAKJHHHHKWQJPPPPWQKSJAQXXXXAQKWJHHHHKJAQWKBBBBQAWJKAWJBBBBQKAJPPPPQAKJHHHHKWQJPPPPQKSJAQXXXXAQKWJAHHHHKJÿ:r,3,AAQWBBBBQAWJXXXXKAWJBBBBQAKJQAKJHHHHKWQJPPPPQKSJAQXXXXAQKWJHHHHKJAAQWBBBBQAWJXXXXKAWJBBBBQAKJQAKJHHHHKAWQJPPPPQKSJAQXXXXAQKWJHHHHKJAAQWBBBBQAWJXXXXKAWJBBBBQAKJQAKJHHHHKWQJPPPPQKSJAQXXXXAQKWJHHHHKJAAQWBBBBQAWJXXXXKAWJBBBBQAKJQAKJHHHHKWQJPPPPWQKSJAQXXXXAQKWJHHHHKJÿ:r,3,AQWKBBBBQAWJKAWJBBBBQKAJPPPPQAKJHHHHKWBBBBQJPPPPQKSJAQXXXXAQKWJHHHHKJAQWKBBBBQAWJKAWJBBBBQKAJPPPPQAKJHHHHKWQJPPPPQKSJAQXXXXAQKWJHHHHKJAQWKBBBBQAWJKAWJBBBBWQKAJPPPPQAKJHHHHKWQJPPPPWQKSJAQXXXXAQKWJHHHHKJAQWKBBBBQAWJKAWJBBBBQKAJPPPPQAKJHHHHKWQJPPPPQKSJAQXXXXAQKWJAHHHHKJÿ:r,3,AAQWBBBBQAWJXXXXKAWJBBBBQKAJPPPPQAKJHHHHKWQJPPPPQKSJAQXXXXAQKWJHHHHKJAAQWBBBBQAWJXXXXKAWJBBBBQKAJPPPPQAKJHHHHKWQJPPPPQKSJAQXXXXAQKWJHHHHKJAAQWBBBBQAWJXXXXKAWJBBBBQKAJPPPPQAKJHHHHKWQJPPPPQKSJAQXXXXAQBBBBKWJHHHHKJAAQWBBBBQAWJXXXXKAWJBBBBQKAJPPPPQAKJHHHHKWQJPPPPQKSJAQXXXXAQKWJHHHHKJÿ:r,3,AQWBBBBQAWJXXXXKAWJBBBBQKAJPPPPQAKJHHHHKWQJPPPPQKSWJAQXXXXAQKWJHHHHKJAQWBBBBPPPPQAWJXXXXKAWJBBBBQKAJPPPPQAKJHHHHKWQJPPPPQKSJAQXXXXAQKWJHHHHKJAQWBBBBQAWPPPPJXXXXKAWJBBBBQKAJPPPPQAKJHHHHKWQBBBBJPPPPQKSJAQXXXXAQKWJHHHHKJAQWBBBBQAWJXXXXKAWJBBBBQKAJPPPPQAKJHHHHKWQJPPPPQKSJAQXXXXAQKWPPPPJHHHHKJÿ:r,4,JQAKJQAKJQAKJQAPPPPQKJAQKJSQKJASQKJBBBBJQAKJQAHHHHÿ:r,4,JQAKJQAKJQAKJQAPPPPQKJAQKJSQKJASQKJBBBBJQAKJQAHHHHÿ:r,4,JQAKJQAKJQAKJQAPPPPQKJAQKJSQKJASQKJBBBBJQAKJQAHHHHÿ:r,4,KWJQKXXXXAKJQABBBBKJAWQKJHHHHAWQKJSAQPPPPAKWJQAÿ:r,4,KWJQKXXXXAKJQABBBBKJAWQKJHHHHAWQKJSAQPPPPAKWJQAÿ:r,4,#####OOOO#####ÿ:r,5,AQJKAQJKAQJKAQJKAQJXXXXQJAKQJSKQJABBBBKQJASKQJHHHHÿ:r,5,AQJKAQJKAQJKAQJKAQJXXXXQJAKQJSKQJABBBBKQJASKQJHHHHÿ:r,5,AQJKAQJKAQJKAQJKAQJXXXXQJAKQJSKQJABBBBKQJASKQJHHHHÿ:r,5,KWQJKXXXXAKJQABBBBKQJAWKJHHHHAWQKJSAQPPPPAKWJQAÿ:r,5,KWQJKXXXXAKJQABBBBKQJAWKJHHHHAWQKJSAQPPPPAKWJQAÿ:r,5,#####OOOO#####ÿ:r,6,JKAQJKAQJKAQJKXXXXQJKAQJKAQJSAQJKBBBBJQASKJQAPPPPQÿ:r,6,JKAQJKAQJKAQJKXXXXQJKAQJKAQJSAQJKBBBBJQASKJQAPPPPQÿ:r,6,JKAQJKAQJKAQJKXXXXQJKAQJKAQJSAQJKBBBBJQASKJQAPPPPQÿ:r,6,KWJAKXXXXAKJQBBBBKQJAWQKJHHHHAWQKJSAQPPPPAKWJQAÿ:r,6,KWJAKXXXXAKJQBBBBKQJAWQKJHHHHAWQKJSAQPPPPAKWJQAÿ:r,6,#####OOOO#####ÿ:r,7,KQJAKQJXXXXJQKAJQSAJQKAJQKAJQKPPPPQAJSKQAJKQAJHHHHÿ:r,7,KQJAKQJXXXXJQKAJQSAJQKAJQKAJQKPPPPQAJSKQAJKQAJHHHHÿ:r,7,KQJAKQJXXXXJQKAJQSAJQKAJQKAJQKPPPPQAJSKQAJKQAJHHHHÿ:r,7,KWAJKXXXXAKJQBBBBKQJAWQKJHHHHAWQKJSAQPPPPAKWJAQÿ:r,7,KWAJKXXXXAKJQBBBBKQJAWQKJHHHHAWQKJSAQPPPPAKWJAQÿ:r,7,#####OOOO#####ÿ:r,8,KWJQKXXXXAKJQABBBBKJAWQKJHHHHAWQKJSAQPPPPAKWJQAÿ:r,8,JQAKJQAKJQAKJQAPPPPQKJAQKJSQKJASQKJBBBBJQAKJQAHHHHÿ:r,8,JQAKJQAKJQAKJQAPPPPQKJAQKJSQKJASQKJBBBBJQAKJQAHHHHÿ:r,8,JQAKJQAKJQAKJQAPPPPQKJAQKJSQKJASQKJBBBBJQAKJQAHHHHÿ:r,8,KWJQKXXXXAKJQABBBBKJAWQKJHHHHAWQKJSAQPPPPAKWJQAÿ:r,8,#####OOOO#####ÿ:r,9,KWQJKXXXXAKJQABBBBKQJAWKJHHHHAWQKJSAQPPPPAKWJQAÿ:r,9,AQJKAQJKAQJKAQJKAQJXXXXQJAKQJSKQJABBBBKQJASKQJHHHHÿ:r,9,AQJKAQJKAQJKAQJKAQJXXXXQJAKQJSKQJABBBBKQJASKQJHHHHÿ:r,9,AQJKAQJKAQJKAQJKAQJXXXXQJAKQJSKQJABBBBKQJASKQJHHHHÿ:r,9,KWQJKXXXXAKJQABBBBKQJAWKJHHHHAWQKJSAQPPPPAKWJQAÿ:r,9,#####OOOO#####ÿ:r,10,KWJAKXXXXAKJQBBBBKQJAWQKJHHHHAWQKJSAQPPPPAKWJQAÿ:r,10,JKAQJKAQJKAQJKXXXXQJKAQJKAQJSAQJKBBBBJQASKJQAPPPPQÿ:r,10,JKAQJKAQJKAQJKXXXXQJKAQJKAQJSAQJKBBBBJQASKJQAPPPPQÿ:r,10,JKAQJKAQJKAQJKXXXXQJKAQJKAQJSAQJKBBBBJQASKJQAPPPPQÿ:r,10,KWJAKXXXXAKJQBBBBKQJAWQKJHHHHAWQKJSAQPPPPAKWJQAÿ:r,10,#####OOOO#####ÿ:r,11,KWAJKXXXXAKJQBBBBKQJAWQKJHHHHAWQKJSAQPPPPAKWJAQÿ:r,11,KQJAKQJXXXXJQKAJQSAJQKAJQKAJQKPPPPQAJSKQAJKQAJHHHHÿ:r,11,KQJAKQJXXXXJQKAJQSAJQKAJQKAJQKPPPPQAJSKQAJKQAJHHHHÿ:r,11,KQJAKQJXXXXJQKAJQSAJQKAJQKAJQKPPPPQAJSKQAJKQAJHHHHÿ:r,11,KWAJKXXXXAKJQBBBBKQJAWQKJHHHHAWQKJSAQPPPPAKWJAQÿ:r,11,#####OOOO#####ÿ:r,12,KWJQKXXXXAKJQABBBBKJAWQKJHHHHAWQKJSAQPPPPAKWJQAÿ:r,12,KWJQKXXXXAKJQABBBBKJAWQKJHHHHAWQKJSAQPPPPAKWJQAÿ:r,12,JQAKJQAKJQAKJQAPPPPQKJAQKJSQKJASQKJBBBBJQAKJQAHHHHÿ:r,12,JQAKJQAKJQAKJQAPPPPQKJAQKJSQKJASQKJBBBBJQAKJQAHHHHÿ:r,12,JQAKJQAKJQAKJQAPPPPQKJAQKJSQKJASQKJBBBBJQAKJQAHHHHÿ:r,12,#####OOOO#####ÿ:r,13,KWQJKXXXXAKJQABBBBKQJAWKJHHHHAWQKJSAQPPPPAKWJQAÿ:r,13,KWQJKXXXXAKJQABBBBKQJAWKJHHHHAWQKJSAQPPPPAKWJQAÿ:r,13,AQJKAQJKAQJKAQJKAQJXXXXQJAKQJSKQJABBBBKQJASKQJHHHHÿ:r,13,AQJKAQJKAQJKAQJKAQJXXXXQJAKQJSKQJABBBBKQJASKQJHHHHÿ:r,13,AQJKAQJKAQJKAQJKAQJXXXXQJAKQJSKQJABBBBKQJASKQJHHHHÿ:r,13,#####OOOO#####ÿ:r,14,KWJAKXXXXAKJQBBBBKQJAWQKJHHHHAWQKJSAQPPPPAKWJQAÿ:r,14,KWJAKXXXXAKJQBBBBKQJAWQKJHHHHAWQKJSAQPPPPAKWJQAÿ:r,14,JKAQJKAQJKAQJKXXXXQJKAQJKAQJSAQJKBBBBJQASKJQAPPPPQÿ:r,14,JKAQJKAQJKAQJKXXXXQJKAQJKAQJSAQJKBBBBJQASKJQAPPPPQÿ:r,14,JKAQJKAQJKAQJKXXXXQJKAQJKAQJSAQJKBBBBJQASKJQAPPPPQÿ:r,14,#####OOOO#####ÿ:r,15,KWAJKXXXXAKJQBBBBKQJAWQKJHHHHAWQKJSAQPPPPAKWJAQÿ:r,15,KWAJKXXXXAKJQBBBBKQJAWQKJHHHHAWQKJSAQPPPPAKWJAQÿ:r,15,KQJAKQJXXXXJQKAJQSAJQKAJQKAJQKPPPPQAJSKQAJKQAJHHHHÿ:r,15,KQJAKQJXXXXJQKAJQSAJQKAJQKAJQKPPPPQAJSKQAJKQAJHHHHÿ:r,15,KQJAKQJXXXXJQKAJQSAJQKAJQKAJQKPPPPQAJSKQAJKQAJHHHHÿ:r,15,#####OOOO#####ÿ:j,W,1,0,XPHBAKQJÿ:u,APPPP.PP.PP.PPPPÿ:w,S,3,-1,0ÿ:w,S,4,-5,0ÿ:w,S,5,-25,0ÿ:w,X,3,40,0ÿ:w,X,4,100,0ÿ:w,X,5,500,0ÿ:w,P,3,20,0ÿ:w,P,4,60,0ÿ:w,P,5,300,0ÿ:w,H,3,16,0ÿ:w,H,4,40,0ÿ:w,H,5,200,0ÿ:w,B,3,16,0ÿ:w,B,4,40,0ÿ:w,B,5,200,0ÿ:w,A,3,8,0ÿ:w,A,4,32,0ÿ:w,A,5,120,0ÿ:w,K,3,8,0ÿ:w,K,4,32,0ÿ:w,K,5,120,0ÿ:w,Q,3,4,0ÿ:w,Q,4,20,0ÿ:w,Q,5,100,0ÿ:w,J,3,4,0ÿ:w,J,4,20,0ÿ:w,J,5,100,0ÿ:wa,S,3,-1,0,0,0,0:1,-1,0ÿ:wa,S,4,-5,0,0,0,0:1,-1,0ÿ:wa,S,5,-25,0,0,0,0:1,-1,0ÿ:wa,X,3,40,0,0,0,0:1,-1,0ÿ:wa,X,4,100,0,0,0,0:1,-1,0ÿ:wa,X,5,500,0,0,0,0:1,-1,0ÿ:wa,P,3,20,0,0,0,0:1,-1,0ÿ:wa,P,4,60,0,0,0,0:1,-1,0ÿ:wa,P,5,300,0,0,0,0:1,-1,0ÿ:wa,H,3,16,0,0,0,0:1,-1,0ÿ:wa,H,4,40,0,0,0,0:1,-1,0ÿ:wa,H,5,200,0,0,0,0:1,-1,0ÿ:wa,B,3,16,0,0,0,0:1,-1,0ÿ:wa,B,4,40,0,0,0,0:1,-1,0ÿ:wa,B,5,200,0,0,0,0:1,-1,0ÿ:wa,A,3,8,0,0,0,0:1,-1,0ÿ:wa,A,4,32,0,0,0,0:1,-1,0ÿ:wa,A,5,120,0,0,0,0:1,-1,0ÿ:wa,K,3,8,0,0,0,0:1,-1,0ÿ:wa,K,4,32,0,0,0,0:1,-1,0ÿ:wa,K,5,120,0,0,0,0:1,-1,0ÿ:wa,Q,3,4,0,0,0,0:1,-1,0ÿ:wa,Q,4,20,0,0,0,0:1,-1,0ÿ:wa,Q,5,100,0,0,0,0:1,-1,0ÿ:wa,J,3,4,0,0,0,0:1,-1,0ÿ:wa,J,4,20,0,0,0,0:1,-1,0ÿ:wa,J,5,100,0,0,0,0:1,-1,0ÿ:s,0ÿ:i,40ÿ:m,40ÿ:a,0,0ÿ:g,999,1000,-1,false,0,falseÿ:es,0,0ÿ:mbnr,0.0ÿ:fs,0,0,0,0,0ÿbs,0,1,0ÿ:k,nullÿe,40,0,0,-1ÿb,0,0,0ÿs,1ÿr,2,5,3,35,44,59,74ÿrw,0";
            }
        }
        #endregion

        public WinterQueenGameLogic()
        {
            _gameID = GAMEID.WinterQueen;
            GameName = "WinterQueen";
        }

        protected override string buildLineBetString(string strGlobalUserID, double balance)
        {
            return string.Format("\u0006S{0}ÿA0ÿC,100.0,,1,ÿT,0,0,0ÿRÿM,40,3000,40,-1,0ÿI00ÿH,0,0,0,0,0,0ÿY,7200,10ÿ:i,40ÿ:m,40ÿ:b,12,1,2,3,4,5,8,10,15,20,30,40,50ÿ:a,0,0ÿ:g,999,1000,-1,false,0,falseÿ:es,0,0ÿ:mbnr,40.0ÿbs,0,1,0ÿ:k,nullÿe,{1},{2},{3},-1ÿb,1000,1000,0ÿs,1ÿr,2,5,3,35,44,59,74ÿrw,0", balance, !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? this._defaultLine : _dicUserBetInfos[strGlobalUserID].PlayLine, !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? this._defaultBetPerLine : (_dicUserBetInfos[strGlobalUserID].PlayBet / _dicUserBetInfos[strGlobalUserID].PlayLine), !_dicUserBetInfos.ContainsKey(strGlobalUserID) ? Array.IndexOf(_supportLines, this._defaultLine) : Array.IndexOf(_supportLines, _dicUserBetInfos[strGlobalUserID].PlayLine));
        }

        protected override void onDoInit(string strGlobalUserID, GITMessage message, double balance, Currencies currency)
        {
            try
            {
                GITMessage resMessage = new GITMessage((ushort)SCMSG_CODE.SC_GREENTUBE_DOINIT);
                resMessage.Append("%t0ÿq0");
                resMessage.Append(VersionCheckString);
                foreach (string currencyName in SupportCurrencyList)
                {
                    resMessage.Append(currencyName);
                }
                resMessage.Append(buildInitString(strGlobalUserID, balance, currency));
                resMessage.Append("\vGAMEVARIATIONÿ665ÿTICKETSÿ1");
                resMessage.Append(GameUniqueString);

                resMessage.Append("%t0ÿq0");
                resMessage.Append($"\aNATIVEJACKPOTCURRENCYFACTORÿ100.0ÿMAXBUYINTOTALÿ0ÿNEEDSSESSIONTIMEOUTÿ0ÿRELIABILITYÿ0ÿNICKNAMEÿ155258EURÿIDÿ155258ÿISDEEPWALLETÿ0ÿCURRENCYFACTORÿ100.0ÿMINBUYINÿ1ÿSESSIONTIMEOUTMINUTESÿ60ÿJACKPOT_PROGRESSIVE_CAPÿ0.0ÿNATIVEJACKPOTCURRENCYÿ{getCurrencyCode(currency)}ÿEXTUSERIDÿDummyDB_ExternalUserId_155258EURÿFREESPINSISCAPREACHEDÿ0ÿCURRENCYÿ{getCurrencySymbol(currency)}ÿTICKETSÿ0ÿJACKPOT_TOTAL_CAPÿ0.0ÿJACKPOTFEEPERCENTAGEÿ0.0ÿISSHOWJACKPOTCONTRIBUTIONÿ0");
                resMessage.Append(buildLineBetString(strGlobalUserID, balance));

                ToUserMessage toUserMessage = new ToUserMessage((int)_gameID, resMessage);

                Sender.Tell(toUserMessage, Self);
            }
            catch (Exception ex)
            {
                _logger.Error("Exception has been occurred in BaseGreentubeSlotGame::onDoInit GameID: {0}, {1}", _gameID, ex);
            }
        }
        protected override void onBalanceConfirm(string strGlobalUserID, GITMessage message, double balance, Currencies currency)
        {
            try
            {
                GITMessage resMessage = new GITMessage((ushort)SCMSG_CODE.SC_GREENTUBE_BALANCECONFIRM);
                resMessage.Append("%t0ÿq0");
                resMessage.Append($"\aNATIVEJACKPOTCURRENCYFACTORÿ100.0ÿMAXBUYINTOTALÿ0ÿNEEDSSESSIONTIMEOUTÿ0ÿRELIABILITYÿ0ÿNICKNAMEÿ155258EURÿIDÿ155258ÿISDEEPWALLETÿ0ÿCURRENCYFACTORÿ100.0ÿMINBUYINÿ1ÿSESSIONTIMEOUTMINUTESÿ60ÿJACKPOT_PROGRESSIVE_CAPÿ0.0ÿNATIVEJACKPOTCURRENCYÿ{getCurrencyCode(currency)}ÿEXTUSERIDÿDummyDB_ExternalUserId_155258EURÿFREESPINSISCAPREACHEDÿ0ÿCURRENCYÿ{getCurrencySymbol(currency)}ÿTICKETSÿ0ÿJACKPOT_TOTAL_CAPÿ0.0ÿJACKPOTFEEPERCENTAGEÿ0.0ÿISSHOWJACKPOTCONTRIBUTIONÿ0");
                resMessage.Append(buildLineBetString(strGlobalUserID, balance));
                ToUserMessage toUserMessage = new ToUserMessage((int)_gameID, resMessage);

                Sender.Tell(toUserMessage, Self);
            }
            catch (Exception ex)
            {
                _logger.Error("Exception has been occurred in BaseGreentubeSlotGame::onDoInit GameID: {0}, {1}", _gameID, ex);
            }
        }
    }
}
