using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GITProtocol
{
    public enum GameProviders
    {
        NONE        = 0,
        PP          = 1,
        BNG         = 2,
        CQ9         = 3,
        HABANERO    = 4,
        PLAYSON     = 5,
        AMATIC      = 6,
        GREENTUBE   = 7,
        EGT         = 8,
        COUNT       = 9,
    }

    public enum GAMEID : ushort
    {
        #region EGT games

        DiceOfMagic                             = 8001,
        SupremeDice                             = 8002,
        N100Cats                                = 8003,
        N100Dice                                = 8004,
        N100SuperDice                           = 8005,
        N40BurningDice                          = 8006,
        N40SuperDice                            = 8007,
        N50Horses                               = 8008,
        AztecGlory                              = 8009,
        CasinoMania                             = 8010,
        CoralIsland                             = 8011,
        DiceOfRa                                = 8012,
        FastMoney                               = 8013,
        HotDeco                                 = 8014,
        IncaGoldII                              = 8015,
        LikeADiamond                            = 8016,
        MagellanPlus                            = 8017,
        MoreDiceAndRoll                         = 8018,
        MoreLikeADiamond                        = 8019,
        OilCompanyII                            = 8020,
        RetroStyle                              = 8021,
        RollingDice                             = 8022,
        RoyalGardens                            = 8023,
        SummerBliss                             = 8024,
        TheGreatEgypt                           = 8025,
        N20Diamonds                             = 8026,
        N20SuperDice                            = 8027,
        N2Dragons                               = 8028,
        N40MegaClover                           = 8029,
        N5HotDice                               = 8030,
        BurningDice                             = 8031,
        DiceAndRoll                             = 8032,
        FlamingDice                             = 8033,
        GameOfLuck                              = 8034,
        GreekFortune                            = 8035,
        LuckyAndWild                            = 8036,
        LuckyHot                                = 8037,
        MoreLuckyAndWild                        = 8038,
        NeonDice                                = 8039,
        Super20                                 = 8040,
        TheWhiteWolf                            = 8041,
        FlamingHot                              = 8042,
        N100BurningHot                          = 8043,
        N100SuperHot                            = 8044,
        N10BurningHeart                         = 8045,
        N20BurningHot                           = 8046,
        N20HotBlast                             = 8047,
        N40BurningHot                           = 8048,
        N40BurningHot5                          = 8049,
        N40LuckyKing                            = 8050,
        N5BurningHeart                          = 8051,
        AgeOfTroy                               = 8052,
        AmazingAmazonia                         = 8053,
        BlueHeart                               = 8054,
        BookOfMagic                             = 8055,
        BurningHot                              = 8056,
        DazzlingHot                             = 8057,
        DragonReels                             = 8058,
        FlamingHot6                             = 8059,
        FortuneSpells                           = 8060,
        FruitsKingdom                           = 8061,
        GraceOfCleopatra                        = 8062,
        MajesticForest                          = 8063,
        OlympusGlory                            = 8064,
        RiseOfRa                                = 8065,
        RoyalSecrets                            = 8066,
        ShiningCrown                            = 8067,
        SuperHot20                              = 8068,
        SuperHot40                              = 8069,
        SupremeHot                              = 8070,
        TheBigJourney                           = 8071,
        UltimateHot                             = 8072,
        VersaillesGold                          = 8073,
        WirchesCharm                            = 8074,
        ZodiacWheel                             = 8075,
        CandyPalace                             = 8076,
        CavemenAndDinosaurs                     = 8077,
        DiceAndDinosaurs                        = 8078,
        CoinGobblerChristmasEdition             = 8079,
        CandyPalaceChristmasEdition             = 8080,
        CoinGobbler                             = 8081,
        Stoichkov                               = 8082,
        AztecDice                               = 8083,
        KemetsTreasures                         = 8084,
        AztectForest                            = 8085,
        CandyDice                               = 8086,
        FruityTime                              = 8087,
        N20PirateBombs                          = 8088,
        N40WenshiLion                           = 8089,
        LuckyWood                               = 8090,
        SecretsOfAlchemy                        = 8091,
        MythicalTreasure                        = 8092,
        N20GoldenCoins                          = 8093,
        N100GoldenCoins                         = 8094,
        Great27                                 = 8095,
        N100BulkyFruits                         = 8096,
        N40BulkyFruits                          = 8097,
        N40GoldenCoins                          = 8098,
        ExtraCrown                              = 8099,
        N7Crystals                              = 8100,

        #endregion
    }

    public enum CSMSG_CODE : ushort
    {
        CS_HEARTBEAT            = 0,
        CS_LOGIN                = 1,
        CS_ENTERGAME            = 18,
        CS_FORCEOUTUSER         = 26,   //유저강퇴

        CS_EGT_SLOTGAMESTART     = 2300,
        CS_EGT_DOINIT            = 2300,
        CS_EGT_SUBSCRIBE         = 2301,
        CS_EGT_SETTINGS          = 2302,
        CS_EGT_DOSPIN            = 2303,
        CS_EGT_DOCOLLECT         = 2304,
        CS_EGT_DOGAMBLE          = 2305,
        CS_EGT_DOGAMBLEPICK      = 2305,
        CS_EGT_DOGAMBLEHALF      = 2306,
        CS_EGT_JACKPOTSTATE      = 2307,
        CS_EGT_SLOTGAMEEND       = 2308,
        CS_EGT_NOTPROCDRESULT    = 2309,
    }

    public enum SCMSG_CODE : ushort
    {
        SC_HEARTBEAT            = 0,
        SC_LOGIN                = 1,
        SC_ENTERGAME            = 18,

        SC_EGT_SLOTGAMESTART     = 2300,
        SC_EGT_DOINIT            = 2300,
        SC_EGT_SUBSCRIBE         = 2301,
        SC_EGT_SETTINGS          = 2302,
        SC_EGT_DOSPIN            = 2303,
        SC_EGT_DOCOLLECT         = 2304,
        SC_EGT_DOGAMBLE          = 2305,
        SC_EGT_DOGAMBLEPICK      = 2305,
        SC_EGT_DOGAMBLEHALF      = 2306,
        SC_EGT_JACKPOTSTATE      = 2307,
        SC_EGT_SLOTGAMEEND       = 2308,
    }
}
