using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GITProtocol
{
    public enum GameProviders
    {
        NONE        = 0,
        PP          = 1,
        BNG         = 2,
        CQ9         = 3,
        HABANERO    = 4,
        PLAYSON     = 5,
        AMATIC      = 6,
        GREENTUBE   = 7,
        COUNT       = 8,
    }

    public enum GAMEID : ushort
    {
        #region Green games

        SizzlingHotDeluxe                   = 7001,
        BookOfRaDeluxe                      = 7002,
        Katana                              = 7003,
        BookOfRaMagic                       = 7004,
        FairyQueen                          = 7005,
        RoaringForties                      = 7006,
        LordOfTheOceanMagic                 = 7007,
        JustJewelsDeluxe                    = 7008,
        Faust                               = 7009,
        BookOfRaDeluxe6                     = 7010,
        TalesOfDarknessFullMoon             = 7011,
        PowerStars                          = 7012,
        AlwaysHotDeluxe                     = 7013,
        ColumbusDeluxe                      = 7014,
        CaptainVenture                      = 7015,
        MegaJoker                           = 7016,
        SizzlingHot6ExtraGold               = 7017,
        ChiliBomba                          = 7018,
        EyeOfTheDragon                      = 7019,
        BookOfRaClassic                     = 7020,
        LuckyLadysCharmDeluxe               = 7021,
        DolphinsPearlDeluxe                 = 7022,
        LuckyLadysCharmDeluxe10             = 7023,
        Gorilla                             = 7024,
        XtraHot                             = 7025,
        MysticSecrets                       = 7026,
        LuckyLadysCharmDeluxe6              = 7027,
        PlentyOnTwenty                      = 7028,
        RumpelWildspins                     = 7029,
        DiamondLinkMightyBuffalo            = 7030,
        GryphonsGoldDeluxe                  = 7031,
        HotChance                           = 7032,
        UltraHotDeluxe                      = 7033,
        QueenCleopatra                      = 7034,
        ShootingStars                       = 7035,
        BookOfStars                         = 7036,
        PharaohsRing                        = 7037,
        QueenOfHeartsDeluxe                 = 7038,
        SummerQueen                         = 7039,
        SpringQueen                         = 7040,
        AfricanSimba                        = 7041,
        DolphinsPearlClassic                = 7042,
        EmpireOfDead                        = 7043,
        StarsInferno                        = 7044, 
        SizzlingHotDeluxe10                 = 7045,
        PiggyPrizesWandOfRiches             = 7046,
        DynamiteFortunes                    = 7047,
        MagnificentMerlin                   = 7048,
        CashConnectionCharmingLady          = 7049,
        SuperCherry2000                     = 7050,
        N50RedHot7CloverLink                = 7051, 
        CashConnectionBookOfRa              = 7052,
        SuperCherryLockNWin                 = 7053,
        WinterQueen                         = 7054,
        BookOfRaDeluxe10Winways             = 7055,
        DiamondLinkOasisRiches              = 7056,
        N50RedHotBurningCloverLink          = 7057,
        DiamondLinkAlmightyKraken           = 7058,
        N50ExtremeHot                       = 7059,
        TopOTheMoneyPotsOfWealth            = 7060,
        DiamondLinkCopsNRobbers             = 7061,
        AutumnQueen                         = 7062, 
        GoldenArk                           = 7063,
        GreatFortune                        = 7064,
        DiamondLinkMightySanta              = 7065,
        DiamondMysteryFruitiliciousDeluxe   = 7066,
        HaulOfHades                         = 7067,
        FeelinFruityWinWays                 = 7068,
        HotCherry                           = 7069,
        AlmightyJackpotsGardenOfPersephone  = 7070,
        ApolloGodOfTheSun                   = 7071,
        LoneStarJackpot                     = 7072,
        StarlightJackpotsAthenaGoddessOfWar = 7073,
        GreatAmericanWilds                  = 7074,
        DiamondLinkMightySevens             = 7075,
        SmashingSevensWinWays               = 7076,
        CharmingLadysBoom                   = 7077,
        CashConnectionDolphinsPearl         = 7078,
        PrizeOfTheNile                      = 7079,
        DiamondMysteryMegaBlaze             = 7080,
        WishUponAStar                       = 7081,
        DragonBlitz                         = 7082,
        WelcomeFortune                      = 7083,
        TheGreatGambinisNightMagic          = 7084,
        JuicyRiches                         = 7085,
        DiamondLinkMightyElephant           = 7086,
        AChristmasFullOfWilds               = 7087,
        ManicPotions                        = 7088,
        CyberWildz                          = 7089,
        CashConnectionGoldenBookOfRa        = 7090,
        N40SupremeFruits                    = 7091,
        LotusFlower                         = 7092,
        SmokingHot7s                        = 7093,
        RisingJoker                         = 7094,
        CaptainVentureTreasuresOfTheSea     = 7095,
        MythOfMedusaGold                    = 7096,
        ArcticRace                          = 7097,
        DiamondTalesTheEmperorsNewClothes   = 7098,
        CaribbeanHolidays                   = 7099,
        StarSupreme                         = 7100,
        GoldStarFruits                      = 7101,
        N10ImperialCrownDeluxe              = 7102,
        BingoStaxxAmazonFury                = 7103,
        N25RedHot7CloverLink                = 7104,
        RomeoJulietSealedWithAKiss          = 7105,    
        N25RedHotBurningCloverLink          = 7106,
        ClashOfLegendsBattleLinesAnteBet    = 7107,
        RichesOfBabylon                     = 7108,
        ElectricFlamingo                    = 7109,
        FuzanglongFireWilds                 = 7110,
        IrishCoins                          = 7111,
        JokerParty6                         = 7112,
        GoddessOfegypt                      = 7113,
        SilverTrails                        = 7114,
        SuperCircus                         = 7115,
        BurningWild                         = 7116,
        ChilliElToro                        = 7117,
        StarCandy                           = 7118,
        FruitKingSuperCash                  = 7119,
        SantasRiches                        = 7120,
        IslandHeat                          = 7121,
        FortuneFishing                      = 7122,
        RisingTreasures                     = 7123,
        Fruchteparadies10                   = 7124,
        AncientGoddess                      = 7125,
        EyeOfTheQueen                       = 7126,
        EgyptianUnderworld                  = 7127,
        DragonWarrior                       = 7128,
        BookOfRaTempleOfGold                = 7129,
        #endregion
    }

    public enum CSMSG_CODE : ushort
    {
        CS_HEARTBEAT            = 0,
        CS_LOGIN                = 1,
        CS_ENTERGAME            = 18,
        CS_FORCEOUTUSER         = 26, 

        CS_GREENTUBE_SLOTGAMESTART     = 2300,
        CS_GREENTUBE_DOINIT            = 2300,
        CS_GREENTUBE_DOSPIN            = 2301,
        CS_GREENTUBE_DOCOLLECT         = 2302,
        CS_GREENTUBE_DOGAMBLEPICK      = 2303,
        CS_GREENTUBE_DOGAMBLEHALF      = 2304,
        CS_GREEN_SLOTGAMEEND           = 2307,
        CS_GREENTUBE_NOTPROCDRESULT    = 2308,
        CS_GREENTUBE_BALANCECONFIRM    = 3002,
        CS_GREENTUBE_CHANGELINEBET     = 3003,
    }

    public enum SCMSG_CODE : ushort
    {
        SC_LOGIN                = 1,
        SC_ENTERGAME            = 18,

        SC_GREENTUBE_SLOTGAMESTART     = 2300,
        SC_GREENTUBE_DOINIT            = 2300,
        SC_GREENTUBE_DOSPIN            = 2301,
        SC_GREENTUBE_DOCOLLECT         = 2302,
        SC_GREENTUBE_DOGAMBLEPICK      = 2303,
        SC_GREENTUBE_DOGAMBLEHALF      = 2304,
        SC_GREENTUBE_DOHEARTBEAT       = 2305,
        SC_GREENTUBE_SLOTGAMEEND       = 2307,
        SC_GREENTUBE_BALANCECONFIRM    = 3002,
        SC_GREENTUBE_CHANGELINEBET     = 3003,
    }
}
